<?php

/**
 * This is the model base class for the table "adminUser".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminUser".
 *
 * Columns in table "adminUser" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $username
 * @property string $password
 *
 */
abstract class BaseAdminUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'adminUser';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AdminUser|AdminUsers', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password', 'required'),
			array('username', 'length', 'max'=>45),
			array('password', 'length', 'max'=>100),
			array('id, username, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}