/*
 Adform.Bootstrap.js, version 2.1.75212

 Copyright Adform
 http://www.adform.com

 Date: 2014-03-13
*/
(function(a,d,b){function m(a,k){(k?9==k.nodeType?k:k.document:b).write('<script type="text/javascript" src="'+a+'"><\/script>')}function k(b){for(var k=a._prepareBannerDataCB,g={},i="ADFVideoCDN,ADFDomainCDN,ADFDomain,VideoCDN,ADFVideoCDNList,ADFcmpgnID,ADFmembID,ADFtagID,ADFafbanID,ADFBanVer,ADFBanVerBak,ADFbanID,ADFbanPlacID,ADFUnloadID,ADFClientSiteId,ADFGeoData,ADFGroupId,ADFTemplateVersion,ADFTemplateId,ADF_ClickEvent".split(","),e=i.length-1;0<=e;e--)i[e]in d&&(g[i[e]]=d[i[e]]);var o=a.RMBData=
{clicktags:""};a._prepareBannerDataCB=function(){for(var e=i.length-1;0<=e;e--)i[e]in g&&(d[i[e]]=g[i[e]]);a.prepareBannerData(b);for(e in o)a.RMBData[e]="clicktags"!=e?o[e]:a.RMBData[e]+o[e];k&&k()};k||m(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}a.loadResource=a.loadResource||m;a.prepareBannerData=a.prepareBannerData||k})(Adform=window.Adform||{},window,document);
(function(a,d){var b="https:"==d.location.protocol?"https://":"http://";a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={dynamicHost:a.host||b+"track.adform.net",staticHost:a.shost||b+"s1.adform.net",akamaiHost:b+"adformvod-vh.akamaihd.net/i/Banners",level:Math.random(),levels:{Usage:1,BannerFailure:1,OldTemplates:1,EngagementTracker:1,AdMessage:1,CloudFrontNetFailure:1,AdConstructor:1,Socialize:0.1,RestartAnimation:0.1,BannerType_expanding:0.1,
BannerType_tearback:0.1,BannerType_singleExpanding:0.1,BannerType_floating:0.1,BannerType_standard:0.1,BannerType_interstitial:0.1,BannerType_oldInterstitial:0.1,BannerType_videoCube:0.1,ExpandingBehavior_default:0.1,ExpandingBehavior_pushdown:0.1,ExpandingBehavior_sidekick:0.1,ExpandingBehavior_floating:0.1,ExpandingBehavior_takeover:0.1,ExpandingBehavior_slider:0.1,Expanding_expandTime:0.1,Expanding_collapseTime:0.1,SingleExpanding_expandTime:0.1,SingleExpanding_collapseTime:0.1,AssetType_flash:0.1,
AssetType_image:0.1,AssetType_html:0.1,AssetType_video:0.1,VideoType_flash:0.1,VideoType_html:0.1,Unload_total:0.1,Unload_loaded:0.1,Unload_init:0.1,Unload_sent:0.1,Unload_percent:1,Unload_oldAd:0.1,Extensions:1,CREFURL:0.01,CREFURL_Change:0.01},hooks:[function(b,a){-1<a.indexOf("cloudfront.net")&&b.push("CloudFrontNetFailure")},function(b,a){-1<a.indexOf("message: script failed to load")&&b.push("OldTemplates")},function(b){({Adbox:1,AdContent:1})[b[0]]&&b.push("BannerFailure")}]}})(Adform=window.Adform||
{},document);
(function(a,d,b){if(!a.Log){a.SendQueue||(a.SendQueue=[]);var m;a.Log={timeout:5E3,url:a.ENV.dynamicHost+"/jslog/",sender:a.ENV.staticHost+"/banners/scripts/bootstrap/Adform.Sender."+(!d.JSON?"JSON.":"")+"js?"+(a.cache?"version="+a.cache:"rand="+Math.random()),sendMessage:function(a,m,l){try{var g=[];g.push(this.url);g.push("?src=");g.push(encodeURIComponent(a));g.push("&severity=");g.push(encodeURIComponent(m));g.push("&msg=");g.push(encodeURIComponent(l));(d.Image?new Image(1,1):b.createElement("img")).src=g.join("")}catch(i){}},
sendEvent:function(b,a,d){this.pushMessage([],d,{source:b})},pushMessage:function(k,d,l){var g=a.ENV;if(g){var i=g.hooks;if(i&&(e=i.length))for(;e-- >0;)i[e](k,d,l);for(var i=[],e=k.length,g=g.levels,o;e-- >0;)(o=g[k[e]])&&a.ENV.level<o&&i.push(k[e]);if(i.length){a.SendQueue.push([i,d,l]);if(!(location.protocol.indexOf("https")>-1||a.Log.Sender||m)){m=true;k=b.createElement("script");k.type="text/javascript";k.async=true;k.src=a.Log.sender;d=b.getElementsByTagName("script")[0];d.parentNode.insertBefore(k,
d)}}}}}}})(Adform=window.Adform||{},window,document);
(function(a){function d(b){void 0===b&&(b=Math.round(1E5*((new Date).getTime()+Math.random())));this.N=624;this.M=397;this.MATRIX_A=2567483615;this.UPPER_MASK=2147483648;this.LOWER_MASK=2147483647;this.mt=Array(this.N);this.mti=this.N+1;this.init_genrand(b)}d.prototype.init_genrand=function(b){this.mt[0]=b>>>0;for(this.mti=1;this.mti<this.N;this.mti++)b=this.mt[this.mti-1]^this.mt[this.mti-1]>>>30,this.mt[this.mti]=(1812433253*((b&4294901760)>>>16)<<16)+1812433253*(b&65535)+this.mti,this.mt[this.mti]>>>=
0};d.prototype.genrand_int32=function(){var b,a=[0,this.MATRIX_A];if(this.mti>=this.N){var d;this.mti==this.N+1&&this.init_genrand(5489);for(d=0;d<this.N-this.M;d++)b=this.mt[d]&this.UPPER_MASK|this.mt[d+1]&this.LOWER_MASK,this.mt[d]=this.mt[d+this.M]^b>>>1^a[b&1];for(;d<this.N-1;d++)b=this.mt[d]&this.UPPER_MASK|this.mt[d+1]&this.LOWER_MASK,this.mt[d]=this.mt[d+(this.M-this.N)]^b>>>1^a[b&1];b=this.mt[this.N-1]&this.UPPER_MASK|this.mt[0]&this.LOWER_MASK;this.mt[this.N-1]=this.mt[this.M-1]^b>>>1^a[b&
1];this.mti=0}b=this.mt[this.mti++];b^=b>>>11;b^=b<<7&2636928640;b^=b<<15&4022730752;return(b^b>>>18)>>>0};d.prototype.random=function(){return Math.floor(this.genrand_int32()/2)};a.random=function(b){return(new d(b)).random()}})(Adform=window.Adform||{});
(function(a,d,b){function m(){if(n)return n;if(this instanceof m){this.banners={};this.compoundBanners={};try{b.body||b.write("<html><body></body></html>")}catch(c){}var f=navigator,a=screen,p=f.browserLanguage||f.language||0,f=f.systemLanguage||p,d=a?a.width+"X"+a.height:0,a=a?a.colorDepth:0,e=this.getFlashVersion(),h=this.getJSVersion(),o=this.getCT(),j=this.getCPU(),g=this.getWin(),i=50*Math.round(g.w/50),g=50*Math.round(g.h/50),k=this.hasIframeSanbox();this.settings=[escape(f),escape(p),d,e,i,
g,a,h,o,j,k].join("|")}else return n=new m}function k(c,f){var a,p;a=c;"undefined"!=typeof c.URL&&(p=(p=(a=f.hasIframeSanbox())?b.referrer:top.location.href.split("#")[0])?encodeURIComponent(p):c.CREFURL,a=new g(c.URL),a.append.push("&CREFURL="+p),a.CREFURL=p,a.ROTSEQ=c.ROTSEQ);return a}function r(c,f){if(c){(f=f||[]).push(c);for(var a=0;a<c.frames.length;a++)r(c.frames[a],f);return f}}function l(c){return a.random(c+this.id)}function g(c){var c=(c||"").split(";OOBClickTrack="),f=c.shift().split("?");
this._base=f.shift();this._parts=f.join("?").split(";");c.length&&(this.tracks=c);this.append=[];for(var f=0,a=c.length;f<a;f++)this.append.push(";OOBClickTrack="+encodeURIComponent(c[f]))}function i(c,f,a){var b=c.length,f=f+"=",d,e=f.length;for(a||(f=f.toLowerCase());b--&&!(d=c[b].slice(0,e),a||(d=d.toLowerCase()),d===f););return b}if(!a.ADFBannerUtils){var e=Object.prototype.hasOwnProperty,o=null,t=null,h={webkitVisibilityState:"webkitvisibilitychange",mozVisibilityState:"mozvisibilitychange",
msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"},s;for(s in h)s in b&&(o=s,t=h[s]);var u=-1,n,j,h=m.prototype;h.getCompoundBannerInfo=function(c){return this.compoundBanners["c"+c]||null};h.createBanner=function(c){var f=this,d=f.getTagID(),e=f.addNewBanner(d,"undefined"==typeof a.ADFIframe?0:1),c=e.params=k(c,f);c.tracks&&(e.msn=1,e.OOBClickTracks=c.tracks);c.get("singleTag")&&(e.singleTag=!0,c.set("compoundSeqNo",c.get("compoundSeqNo")||1));"prerender"==b[o]&&(c.set("hid",
2),e.prerender=!0,b.addEventListener(t,function(){if(b[o]!="prerender"&&e.prerender){b.removeEventListener(t,arguments.callee,false);f.registerImpression(e)}},!1));var h=Math.floor(11E3*Math.random())+";set",g=c.get("bn"),j=f.getCompoundBannerInfo(g),i=f.getPropByBn("smid",g),m=c.ROTSEQ,n=!1,l=!1;if(c.get("compoundSeqNo")){var q=f.getRotSeed(),n=q.gen(g);q.compound[g]?l=q.compound[g]:m&&(q.compound[g]=m)}c.set("js",1);c.set("adfxid",d);c.set(h,f.settings);n&&c.set("rotseed",n);l&&c.set("rotseq",encodeURIComponent(l));
j&&c.set("rotseqno",j.replace("r",""));i&&c.set("smid",i);a.CDNHost&&c.set("cdnhost",encodeURIComponent(a.CDNHost));a.loadResource(e.params.toString());return e};h.addNewBanner=function(c,f){delete a._beforeScript;return this.banners[c]={id:c,type:f,adfserveLoadTime:this.now()}};h.copyBanner=function(c,f){var a=this.banners[c];if(!a||!a.params)return null;var a=a.params.copy(),b;for(b in f)e.call(f,b)&&a.set(b,f[b]);return this.createBanner(a)};h.wipeOutBanner=function(c){var f=this.banners[c];f&&
(j&&(j.id=a.random(),j.compound&&delete j.compound[f.bn]),delete this.compoundBanners["c"+f.bn],delete this.banners[c])};h.addBannerAttribute=function(c,f,a){(c=this.banners[c])&&(c[f]=a)};h.getTagID=function(){var c=this.getRotSeed();c.xId||(c.xId=0);return++c.xId+"x"};h.getRotSeed=function(){if(!j){for(var c=r(d.top),f=0;f<c.length;f++){var b=c[f];if(b!=d){var e;a:{try{e=b.Adform&&b.Adform.ADFUtilInstance;break a}catch(h){}e=void 0}if(e&&e.getRotSeed){j=e.getRotSeed();break}}}j?j.gen=l:j={compound:{},
id:a.random(),gen:l}}return j};h.getJSVersion=function(){try{b.write('<span id="ADFtemp"></span>');for(var c=1;10>c;c++){var f=b.createElement("script");f.setAttribute("language","javascript1."+c);f.text="ADFJSVersion="+(c+1)+";";try{b.getElementById("ADFtemp").appendChild(f)}catch(a){}}try{b.getElementById("ADFtemp").parentNode.removeChild(b.getElementById("ADFtemp"))}catch(e){}return"undefined"!=typeof ADFJSVersion?ADFJSVersion:1}catch(d){}};h.getFlashVersion=function(){if(-1==u){var c=navigator.plugins,
f=navigator.mimeTypes,a=d.ActiveXObject,b=16,e,c=c&&c["Shockwave Flash"]&&(!f||!f["application/x-shockwave-flash"]||f["application/x-shockwave-flash"].enabledPlugin)&&c["Shockwave Flash"].description||"";if(!c&&a)for(;6<=b--;)try{e=new a("ShockwaveFlash.ShockwaveFlash."+b);6==b&&(e.AllowScriptAccess="always",c="WIN 6.0.21.0");try{c=e.GetVariable("$version").replace(/,/g,".")}catch(h){}break}catch(g){}u=parseFloat(c.replace(/^.*?(\d+[\.,].*$)/,"$1"))||0}return u};h.getWin=function(){var c=b.documentElement,
a=b.body;return{w:d.innerWidth||c&&c.clientWidth||a&&a.clientWidth,h:d.innerHeight||c&&c.clientHeight||a&&a.clientHeight}};h.getCT=function(){var c={lan:"1",modem:"2"},a="3";try{b.body.addBehavior&&(b.body.addBehavior("#default#clientCaps"),a=b.body.connectionType.toLowerCase(),a="undefined"!=typeof c[a]?c[a]:a)}catch(e){}return a};h.getCPU=function(){return navigator.cpuClass?{x86:1,"68k":2,PPC:3,Alpha:4,Arm:5,Other:6}[navigator.cpuClass]||8:7};h.getSettings=function(){return this.settings};h.fireTargAdPixel=
function(c){this.TargAd||(this.TargAd={});this.TargAd.gmtr=Math.floor(9999999999*Math.random());this.TargAd.gmttzd=(new Date).getTimezoneOffset();c=c.replace("{gmtr}",this.TargAd.gmtr);c=c.replace("{gmttzd}",this.TargAd.gmttzd);this.TargAd.gmtimg||(this.TargAd.gmtimg="undefined"==typeof d.Image?b.createElement("img"):new d.Image,this.TargAd.gmtimg.src=c)};h.registerImpression=function(c){if(c&&c.prerender){var a=c.params.copy();a.set("hid",1);c.rotseqno&&a.set("rotseqno",c.rotseqno);var e=b.createElement("script");
e.src=a.toString();e.type="text/javascript";b.body.appendChild(e);delete c.prerender}};h.addCompoundBannerInfo=function(c,a){this.compoundBanners["c"+c]="r"+a};h.setBannerRegisteredStatus=function(c){var b=this.banners[c],e=this.now(),d=e-b.adfserveLoadTime,h=parseInt(b.serverTime,10);this.addBannerAttribute(c,"adfserveLoadTime",d);h&&(h+=Math.round(0.5*d),this.addBannerAttribute(c,"serverTime",h),this.addBannerAttribute(c,"timeDiff",h-e));this.addBannerAttribute(c,"registered",1);try{var g=a.ADFEventsInstance;
g&&g.register(b);for(var c=q,b=0,o=c.length;b<o;b++)c[b].call(this)}catch(j){}};h.onBannerRegisteredStatus=function(c){q.push(c)};h.hasIframeSanbox=function(){var c=this._sandbox;if("number"!=typeof c){c=1;try{d.top.document.getElementById,c=0}catch(a){}this._sandbox=c}return c};h.getPropByBn=function(c,a){var b,e,d=this.banners;for(b in d)if(e=d[b],e.bn==a&&c in e)return e[c]};h.now=function(){return(new Date).getTime()};a.ADFBannerUtils=m.getInstance=m;a.ADFUtilInstance=m();var q=[];h.ADFCreateObjectCallback=
function(c,a){return function(){a.apply(c,arguments)}};h.eventRegister=function(c,a,b,e){b.addEventListener?b.addEventListener(c,this.ADFCreateObjectCallback(eval(e),eval(a)),!1):b.attachEvent&&b.attachEvent("on"+c,this.ADFCreateObjectCallback(eval(e),eval(a)),!1)};h.getPosition=function(c){try{var a={};a.y=c.offsetTop;a.x=c.offsetLeft;for(var b;null!=c.offsetParent;)b=c.offsetParent,a.y+=b.offsetTop,a.x+=b.offsetLeft,c=b;return a}catch(e){}};h.getScrollXY=function(){try{var c={x:0,y:0};if("number"==
typeof d.pageYOffset)c.y=d.pageYOffset,c.x=d.pageXOffset;else if(b.body&&(b.body.scrollLeft||b.body.scrollTop))c.y=b.body.scrollTop,c.x=b.body.scrollLeft;else if(b.documentElement&&(b.documentElement.scrollLeft||b.documentElement.scrollTop))c.y=b.documentElement.scrollTop,c.x=b.documentElement.scrollLeft;return c}catch(a){}};h.getBrowser=function(){try{if(-1!=navigator.appVersion.indexOf("MSIE")&&0>navigator.userAgent.indexOf("Opera"))return"MSIE";if(-1!=navigator.userAgent.indexOf("Safari"))return"Safari";
if(-1!=navigator.userAgent.indexOf("Opera"))return"Opera";if(-1!=navigator.appName.indexOf("Netscape"))return-1!=navigator.product.indexOf("Gecko")&&(-1!=navigator.vendor.indexOf("Firefox")||-1!=navigator.userAgent.indexOf("Firefox"))?"Firefox":"Netscape"}catch(a){}};h=g.prototype;h.copy=function(){var a=new g,b;for(b in this)e.call(this,b)&&(a[b]=this[b]&&this[b].slice?this[b].slice(0):this[b]);return a};h.get=function(a,b){var e=this._parts,d=i(e,a,b);if(~d)return e[d].slice(a.length+1)};h.set=
function(a,b,e){var d=this._parts,e=i(d,a,e);~e?d[e]=d[e].slice(0,a.length+1)+b:d.push(a+"="+b);return this};h.unset=function(a,b){var e=this._parts,d=i(e,a,b);~d&&e.splice(d,1);return this};h.toString=function(){return this._base+"?"+this._parts.join(";")+this.append.join("")}}})(Adform=window.Adform||{},window,document);
(function(a){(a.ADFBanner=function(){try{a.ADFUtilInstance.createBanner(a.ADFBannerParams?a.ADFBannerParams.shift():a.ADFBannerData)}catch(d){}})()})(Adform=window.Adform||{},window,document);
(function(a,d,b){function m(e,g,i,h,k){try{this.notifyAboutEvent.apply(this,arguments)}catch(m){}var n=(new Date).getTime()-this.InitTime,n=0<n?Math.round(n/1E3):0,n=Math.min(n,3600),j=a.ADFBannerUtils&&a.ADFBannerUtils.getInstance(),j=j&&j.banners&&j.banners[e],l=a.adRegister&&a.adRegister[e];if(!j&&l)return l.sendEvent(g,i,h,k);if(j&&j.isEventsEnabled){for(var n=["bn",j.bn,"event",g,"time",n,"banner",j.ban,"innerbanner",j.innerban,"asset",i,"name",h,"imprid",j.unloadID,"icid",j.cookieID,"rnd",Math.floor(1E9*
Math.random())],j=[],l=0,c=n.length,f;l<c;l+=2)(f=n[l+1])&&!isNaN(f)&&j.push(n[l]+"="+f);j=this.Host+"/Serving/Event/?"+j.join("&")+(k||"");(d.Image?new d.Image(1,1):b.createElement("img")).src=j;this.IsDebugConsoleEnabled&&this.debugElem&&(this.debugElem.value="NEW EVENT: "+j+"\n"+this.debugElem.value);return j}}var k=Object.prototype.hasOwnProperty,r=a.ADFBannerUtils&&a.ADFBannerUtils.getInstance(),l={Initialized:!1,InitTime:(new Date).getTime(),IsDebugConsoleEnabled:!1,Host:a.host||("https:"==
b.location.protocol?"https://":"http://")+"track.adform.net",debugElem:null,callbacks:[],sendEvent:m,Initialize:function(){this.Initialized=!0;for(var b=a.ADFBannerUtils&&a.ADFBannerUtils.getInstance(),d=b&&b.banners,g=0;d&&d[g+1+"x"];)++g;(g=g&&g+"x")&&!("isEventsEnabled"in d[g])&&b.addBannerAttribute(g,"isEventsEnabled",1)},showEventsDebugConsole:function(){if(!this.IsDebugConsoleEnabled){this.IsDebugConsoleEnabled=!0;var a=b,d=a.createElement("div");d.innerHTML='<br/><br/><table align="center" style="background:#EEEEEE; color:#000000;border: #EEEEEE 1px solid;"><tr><th align="center"><b>Send Event - Debug Console</b></th></tr><tr><td align="center"><textarea name="debugConsole" id="debugConsole" rows="14" cols="120" readonly style="font-size:12px;background:#EEEEEE"></textarea><br/></td></tr></table>';
a.insertAdjacentHTML?a.insertAdjacentHTML("BeforeEnd",d.innerHTML):a.body.insertBefore(d,a.body.lastChild);this.debugElem=a.getElementById("debugConsole")}},registerCallback:function(a,b){"function"==typeof a&&this.callbacks.push([a,b])},unregisterCallback:function(a){var b=this.callbacks,d=b.length;if("function"==typeof a)for(;d--;)b[d][0]==a&&b.splice(d,1)},notifyAboutEvent:function(){for(var a=this.callbacks.slice(),b=0,d=a.length;b<d;b++)a[b][0].apply(a[b][1]||this,arguments)}},g=a.Events;if(g){for(var i in l)k.call(l,
i)&&!k.call(g,i)&&(g[i]=l[i]);g.sendEvent=m}else g=a.Events=l;a.ADFEvents2||(a.ADFEvents2=g);r.onBannerRegisteredStatus(function(){var b=r.banners,g,i;for(g in b){i="FSCommandID"+g;d[i]!="function"&&function(b,e){d[e]=function(d,e){a.Events.sendEvent(b,e.split("#|#")[1])}}(g,i)}})})(Adform=window.Adform||{},window,document);