/*
 Adform.RMB.js, version 2.1.75212

 Copyright Adform
 http://www.adform.com

 Date: 2014-03-13
*/
(function(a,d,c){function i(w,h){w.super_=h;k.prototype=h.prototype;w.prototype=new k;w.prototype.constructor=w}function k(){}function q(w,h){for(var b in h)h.hasOwnProperty(b)&&(w[b]=h[b]);return w}function l(w,h){return(h=h||c)&&h.getElementById&&h.getElementById(w)}function t(w,h){var b=!h?c:w.substr?l(w):w;return b?b.getElementsByTagName(h||w):[]}function s(w,h){return~(" "+w.className+" ").indexOf(" "+h+" ")}function b(w,h){s(w,h)&&(w.className=(" "+w.className+" ").replace(" "+h+" "," ").slice(1,
-1),b(w,h))}function f(w){var h=w.offsetTop,b=w.offsetLeft,j,a=n.curCSS,f="static"!=a(w,"position");h||(h=(parseFloat(a(w,"marginTop"))||0)+(f?parseFloat(a(w,"top"))||0:0));b||(b=(parseFloat(a(w,"marginLeft"))||0)+(f?parseFloat(a(w,"left"))||0:0));f&&w.getBoundingClientRect&&(j=n.offset(w,!0));!h&&j&&(h=j.top);!b&&j&&(b=j.left);return{top:h,left:b}}function e(w){var h={relativeX:w[z[0]],relativeY:w[z[1]]};if(null==w.pageX&&null!=w.clientX){var b=c.documentElement,j=c.body;h.pageX=w.clientX+(b&&b.scrollLeft||
j.scrollLeft||0);h.pageY=w.clientY+(b&&b.scrollTop||j.scrollTop||0)}else h.pageX=w.pageX,h.pageY=w.pageY;return h}function g(w,h){if(!(w=w.parentNode))return!1;var b=w.ownerDocument,j=b.body,a=n.curCSS,f;h&&(h+=1);if(d.$sf)return!0;if(n.isIE&&(8>b.documentMode||"BackCompat"==b.compatMode))return!1;for(;w&&w!=j;){if("hidden"==a(w,"overflow"))return!1;if("fixed"==a(w,"position"))break;else if(h&&(f=parseInt(a(w,"z-index"),10))&&f<h)return!1;w=w.parentNode}return!0}function o(){for(var w=0,b=[];w<R.length;w++)"complete"!=
R[w].document.readyState&&b.push(R[w]);if(!(R=b).length||3E4<(new Date).getTime()-U){aa=clearInterval(aa);for(w=0;w<h.length;w++)h[w]();h=[];R=[]}}function u(w,h){var b=w.x+w.width,j=w.y+w.height,a=h.x+h.width,f=h.y+h.height,m=Math.max(w.x,h.x),J=Math.max(w.y,h.y),b=Math.min(b,a)-m,j=Math.min(j,f)-J;return 0<b&&0<j?{x:m,y:J,width:b,height:j}:{x:0,y:0,width:0,height:0}}function A(w,h,b,a){var f=function(h){a&&a.apply(h,arguments)},m=t(b,"head"),m=m&&m[0];if(!m)try{throw Error("Can't find head tag.");
}catch(J){f(J)}var e=h.src||h.href,p=e.replace(/[^\da-z_-]/gi,"_"),aa=b.adformId||n.gid("doc_"),c=aa+"|"+p,E=j[c],p=n.byTag(b,w),r=0,g=p.length;b.adformId=b.adformId||aa;if(E)E.loaded?f():E.callbacks.push(f);else{for(;r<g;++r)if(p[r].src==e||p[r].href==e){f();return}j[c]=E={doc:b,src:e,callbacks:[f]};var C=b.createElement(w),d;q(C,h);a&&(d=function(h){C.onload=C.onreadystatechange=C.onerror=null;h?j[c]=null:E.loaded=1;var w=E.callbacks;r=0;for(g=w.length;r<g;++r)w[r](h)},C.onload=function(){d()},
C.onreadystatechange=function(){"complete"==C.readyState&&d()},C.onerror=function(){try{throw Error("Failed to load script: "+e);}catch(h){d(h)}});setTimeout(function(){m.insertBefore(C,m.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var y=a.RMB,n=y.lib||(y.lib={});a.lib||(a.lib=n);n.inherit=i;n.define=function(h,b,j){j&&i(h,b);j(h,h.prototype)};n.gid=function(h){var b=+new Date;return(h||
"")+(b+b*~~(Math.random()*1E4)).toString(36)};n.byId=l;n.byTag=t;n.bind=function(h,b){return function(){return b.apply(h,arguments)}};n.extend=q;n.isMouseLeave=function(h,b){if(!h||h.type!="mouseout")return true;for(var j=h.relatedTarget||h.toElement,a,f=b.length;j;){for(a=0;a<f;a++)if(b[a]==j)return false;j=j.parentNode}return true};n.singleCall=function(h){function b(){m=false;var h=a,w=j,J=f;j=a=f=null;h&&h.apply(w,J)}var j,a,f,m;return function(J,e){j=J;a=e;f=O.call(arguments,2);if(e&&!m)m=setTimeout(b,
h);else if(!e&&m){clearTimeout(m);m=false}}};n.onload=function(w,b){try{do{if(w[J])break;w[J]=true;if(w.document.readyState!="complete"){R.push(w);if(!aa){U=(new Date).getTime();aa=setInterval(o,200)}}}while(w!=w.parent&&(w=w.parent))}catch(j){}aa?h.push(b):setTimeout(b,0)};n.overlap=u;n.overlapElem=function(h,b){var j=n.offset(h),a=n.offset(b);return u({x:j.left,y:j.top,width:h.offsetWidth,height:h.offsetHeight},{x:a.left,y:a.top,width:b.offsetWidth,height:b.offsetHeight})};n.hasClass=s;n.addClass=
function(h,b){if(!s(h,b))h.className=h.className+(" "+b)};n.removeClass=b;n.loadScript=function(h,b,j){A("script",{src:b,type:"text/javascript"},h,j)};n.loadCSS=function(h,b){A("link",{href:b,type:"text/css",rel:"stylesheet"},h)};n.navigator=d.navigator;n.isTMX=function(h){try{var b=h.document,j=b&&b.body;return j&&s(j,"tmx")}catch(a){}return false};n.isolate=function(h,b){var j=h.__adform_isolate;if(!j){var a=h.document,j=t(a,"head")[0],a=a.createElement("script");a.type="text/javascript";a.text=
'function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';j.insertBefore(a,j.firstChild);j.removeChild(a);j=h.__adform_isolate}j?j(b):(new Function("window","("+b+")(window)"))(h)};var O=Array.prototype.slice;n.addEvent=function(h,b,j){return h[K]?h[K](b,j,false):h[F]?h[F]("on"+b,j):false};n.removeEvent=function(h,b,j){return h[M]?h[M](b,j,false):h[G]?h[G]("on"+b,j):false};var K="addEventListener",M="removeEventListener",F="attachEvent",G="detachEvent",x=/([A-Z])/g,N=/^-?\d+(?:px)?$/i,
V=/^-?\d/,a=c.defaultView;n.curCSS=a&&a.getComputedStyle?function(h,b){var j=h.ownerDocument.defaultView;if(j&&(j=j.getComputedStyle(h,null)))return j.getPropertyValue(b.replace(x,"-$1").toLowerCase())||h.style[b]}:c.documentElement.currentStyle&&function(h,b){var j,a,f,m=h.currentStyle&&h.currentStyle[b];if(!N.test(m)&&V.test(m)){j=(f=h.style).left;if(a=h.runtimeStyle&&h.runtimeStyle.left)h.runtimeStyle.left=h.currentStyle.left;f.left=b==="fontSize"?"1em":m||0;m=f.pixelLeft+"px";f.left=j;if(a)h.runtimeStyle.left=
a}return m===""?"auto":m};var Y=function(){function h(){return h}var b=c.body,j=c.createElement("div"),a;a=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();j.innerHTML='<div style="'+a+'visibility:hidden"><div style="'+a+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+a+'"><div style="'+a+'position:fixed;top:20px;"></div></div><div style="'+a+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+
a+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';b.insertBefore(j=j.firstChild,b.firstChild);a=j.childNodes;h.dnab=a[0].firstChild.offsetTop!==5;h.sfp=a[1].firstChild.offsetTop===20;h.sbfonv=a[2].firstChild.offsetTop===-5;h.dabftac=t(j,"td").offsetTop===5;b.removeChild(j);b=j=a=null;return Y=h},S=/^t(?:able|d|h)$/i;n.offsetFromWindow=function(h){var b,j,a,m;j=h&&h.ownerDocument;if(!j)return null;a=j.documentElement;if("getBoundingClientRect"in a){try{b=h.getBoundingClientRect();
m=a.getBoundingClientRect()}catch(J){}if(!b)return{top:0,left:0};if(m.left>0||m.top>0){b.top=b.top-m.top;b.left=b.left-m.left}return{top:b.top,left:b.left}}b=j.defaultView||j.parentWindow;m=j.body;if(h===j.body)return f(h);h=n.offset(h);j=b&&b.pageYOffset||a.scrollTop||m.scrollTop;a=b&&b.pageXOffset||a.scrollLeft||m.scrollLeft;h.top=h.top-j;h.left=h.left-a;return h};n.offset="getBoundingClientRect"in c.documentElement?function(h,b){var j,a=h&&h.ownerDocument;if(!a)return null;if(!b&&h===a.body)return f(h);
try{j=h.getBoundingClientRect()}catch(m){}if(!j)return{top:0,left:0};var J=a.body,a=a.documentElement;return{top:j.top+(a.scrollTop||J.scrollTop)-(a.clientTop||J.clientTop||0),left:j.left+(a.scrollLeft||J.scrollLeft)-(a.clientLeft||J.clientLeft||0)}}:function(h){var b=h&&h.ownerDocument;if(!b)return null;if(h===b.body)return f(h);var j,a=h.offsetParent,m=b.documentElement,J=b.body;j=(b=b.defaultView)?b.getComputedStyle(h,null):h.currentStyle;for(var e=h.offsetTop,p=h.offsetLeft,c=Y();(h=h.parentNode)&&
h!==J&&h!==m;){if(c.sfp&&j.position==="fixed")break;j=b?b.getComputedStyle(h,null):h.currentStyle;e=e-h.scrollTop;p=p-h.scrollLeft;if(h===a){e=e+h.offsetTop;p=p+h.offsetLeft;if(c.dnab&&(!c.dabftac||!S.test(h.nodeName))){e=e+(parseFloat(j.borderTopWidth)||0);p=p+(parseFloat(j.borderLeftWidth)||0)}a=h.offsetParent}if(c.sbfonv&&j.overflow!=="visible"){e=e+(parseFloat(j.borderTopWidth)||0);p=p+(parseFloat(j.borderLeftWidth)||0)}}if(j.position==="relative"||j.position==="static"){e=e+J.offsetTop;p=p+J.offsetLeft}if(c.sfp&&
j.position==="fixed"){e=e+Math.max(m.scrollTop,J.scrollTop);p=p+Math.max(m.scrollLeft,J.scrollLeft)}return{top:e,left:p}};n.client=function(h){var b,j,a,m,h=h.ownerDocument||h;j=h.defaultView||h.parentWindow;a=h.documentElement;m=h.body;if(j.innerWidth){h=j.innerWidth;b=j.innerHeight}else if(a){h=a.clientWidth;b=a.clientHeight;if(!h||m.clientHeight!=m.offsetHeight){h=Math.min(h||123456789,m.clientWidth||123456789);b=Math.min(b||123456789,m.clientHeight||123456789)}}else{h=m.clientWidth;b=m.clientHeight}return{left:j&&
j.pageXOffset||a&&a.scrollLeft||m&&m.scrollLeft||0,top:j&&j.pageYOffset||a&&a.scrollTop||m&&m.scrollTop||0,width:h,height:b}};n.isArray=Array.isArray||function(h){return Object.prototype.toString.call(h)=="[object Array]"};var z=[["offsetX","offsetY"],["layerX","layerY"]];n.getMousePos=function(h){for(var b;b=z.shift();)if(typeof h[b[0]]!="undefined"){z=b;break}b||(z=["x","y"]);n.getMousePos=e;return e(h)};var T=c.createElement("div");n.html=function(h,b){var j=!b&&T||b.createElement("div");j.innerHTML=
h;return j.firstChild&&j.removeChild(j.firstChild)};var a=n.navigator,X=a.vendor,a=a.userAgent,P=/Apple Computer/i.test(X),y=/Google/i.test(X),E=n.isIPad=/iPad/i.test(a),B=n.isIPhone=/iPhone/i.test(a),C=n.isIOS=E||B,D=n.isTouch="ontouchstart"in c.documentElement||"ontouchstart"in d,E=n.isOrientation="orientation"in d,B=n.isAndroid=!C&&(/Android/i.test(a)||D&&!/series60|symbian|windows ce|blackberry/i.test(a));n.isAndroidApp=B&&!/^(?:Opera|Mozilla)/i.test(a);var m;n.isIOSF=C&&(m=/\sos\s(\d+)_\d+/i.exec(a))&&
(m=4<m[1]>>0);var p=n.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||D;m=n.isIE=/msie|Trident/i.test(a);D=n.isFF=/Firefox[\/.]+[^\s]/i.test(a);n.isMACOS=/Mac OS X/i.test(a);n.isWinPhone=m&&p&&/Phone/gi.test(a);var p=n.isOpera=/Opera/i.test(a),r=n.isOperaMobile=/Opera\s(?!Mini)/i.test(a),I=n.isOperaMini=/Opera\sMini/i.test(a),X=n.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(X),C=n.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(C?P:y),P=n.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&
P,y=n.isInternet=B&&!C&&E&&/Safari\/[\.\d]+$/i.test(a)&&y;n.isAfmaSDK=/afma-sdk/i.test(a);var H=m?"msie":D?"firefox":r?"operaMobile":I?"operaMini":p?"opera":X?"operaWebKit":C?"chrome":P?"safari":y?"internet":!1;n.browser=function(){return H};if(n.isIE&&("Microsoft Internet Explorer"==n.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a)))n.ieVersion=parseFloat(RegExp.$1);n.testPlace=n.isIE&&8>n.ieVersion?function(){return false}:g;n.isSafari&&(n.safariVersion=parseFloat(/Version.([\d.]+)/.exec(a)[1]));
var R=[],h=[],J="__adform_onload",aa,U,j={}})(Adform=window.Adform||{},window,document);
(function(a){function d(){var c=a.Data;if(c&&(delete a.Data,c.videoSources&&c.streamingVideo&&!(0>c.clicktags.indexOf("&detectBW=true")))){for(var d=c.videoSources,k=d[0].file.replace(/^[^:]+:\/\/[^\/]+|[^\/]+$/g,""),q={},l,t=0,s=d.length,b,f,e;t<s;t++)if(d[t]&&(b=d[t].file)&&0<=b.indexOf(k)&&(f=b.match(/([^\/]+?)(\d+)\.f[l4]v$/))){e=q[f[1]]||[];e.push(f[2]);if(!l||q[l].length<=e.length)l=f[1];q[f[1]]=e}l&&(q[l].sort(function(b,a){return b-a}),c.clicktags+="&streamBaseName="+encodeURIComponent(l)+
"&streamBitrates="+q[l].join(","))}}a.BWDetect=d;d()})(Adform=window.Adform||{},window,document);
(function(a){function d(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=d;var c=Array.prototype.slice,a=d.prototype;a.emit=function(a){var d=this._events,q=!1,l=arguments;if(d&&(d=d[a]))if("function"==typeof d){switch(l.length){case 1:d.call(this);break;case 2:d.call(this,l[1]);break;case 3:d.call(this,l[1],l[2]);break;case 4:d.call(this,l[1],l[2],l[3]);break;default:d.apply(this,c.call(l,1))}q=!0}else if(d.length){for(var l=c.call(l,1),d=d.slice(),q=0,t=d.length;q<t;q++)d[q].apply(this,l);q=!0}else delete this._events[a];
return q};a.on=function(a,c){this._events||(this._events={});this.emit("newListener",a,c);var d=this._events;d[a]?"function"==typeof d[a]?d[a]=[d[a],c]:d[a].push(c):d[a]=c;return this};a.once=function(a,c){var d=c._once;d?d._times++:(d=c._once=function(){this.off(a,d);1>--d._times&&delete c._once;return c.apply(this,arguments)},d._times=1);return this.on(a,d)};a.off=function(a,c){if(!this._events||!this._events[a])return this;var d=this._events,l=d[a];if(l==c)return delete d[a],this;c&&c._once&&this.off(c._once);
if("function"==typeof l)return this;if(2>l.length&&l[0]==c)return delete d[a],this;for(var t=0,s=l.length,b=[];t<s;t++)l[t]!=c&&b.push(l[t]);b.length!=s&&(b.length?d[a]=b:delete d[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var c=this._events;c[a]?"function"==typeof c[a]&&(c[a]=[c[a]]):c[a]=[];return c[a]}})(Adform=window.Adform||{});
(function(a,d){function c(){c.super_.call(this);this._previous={};this._attributes={};this._sets=[]}a.RMB=a.RMB||{};var i=a.RMB,k=i.lib;i.StateEmitter=c;k.inherit(c,i.EventEmitter);i=c.prototype;i.set=function(a,c){var d=this._sets,s=this._attributes;if("object"==typeof a)for(var b in a)a.hasOwnProperty(b)&&(s[b]=a[b],d.push(b));else s[a]=c,d.push(a);return this.commit()};i.get=function(a){var c=this._attributes;return a?c[a]:c};i.attr=function(a,c){return"object"==typeof a||1<arguments.length?this.set(a,
c):this.get(a)};i.previous=function(a){var c=this._previous;return a?c[a]:c};i.changes=function(a){var c=this._attributes,i=this._previous,s=this._sets;if(a)return c[a]!==i[a]?c[a]:d;for(var b={},f=0;a=s[f];f++)c[a]!==i[a]&&(b[a]=c[a]);return b};i.commit=function(){var a=this._sets;if(this._commit||!a.length)return this;this._commit=!0;for(var c=this._attributes,d=this._previous,s=!1,b=this._changes||(this._changes={}),f=0,e;e=a[f];f++)c[e]!==d[e]&&c[e]!==b[e]&&(b[e]=c[e],s=!0,this.emit("change:"+
e,c[e],d[e],e));if(s){b={};s=!1;for(e in c)c[e]!==d[e]&&(b[e]=c[e],s=!0);s&&this.emit("change",b)}this._commit=!1;a.splice(0,f);if(a.length)return this.commit();this._changes=null;for(e in c)c.hasOwnProperty(e)&&(d[e]=c[e]);return this};i.onchange=function(a,c){return c?this.on("change:"+a,c):this.on("change",a)}})(Adform=window.Adform||{});
(function(a){function d(a){l.push(this);this._doc=a;this._events={};this.dispatchHover=q.bind(this,c)}function c(){for(var a=d._hoverTarget,f=[],c=d._hoverChain,g=s+"hover-",o;a&&"undefined"!=(o=typeof a.className);)"string"==o&&0<=a.className.indexOf(g)&&f.unshift(a),a=a.parentNode;var u=Math.max(f.length,c.length),a=RegExp(g+"\\S+","g");o=[];for(u-=1;0<=u&&c[u]!=f[u];u--){if(c[u])for(var l=i(c[u].className,g,a),k=0;k<l.length;k++)l[k].call(c[u],"hoverout",c[u]);if(f[u]){l=i(f[u].className,g,a);
for(k=0;k<l.length;k++)o.push([l[k],f[u]])}}if(o.length)for(u=0;u<o.length;u++)o[u][0].call(o[u][1],"hoverin",o[u][1]);d._hoverChain=f}function i(a,c,e){a=a.match(e);e=[];if(a){a=("x|"+a.join("|")).split("|"+c).slice(1);for(c=0;c<a.length;c++)t[a[c]]&&e.push(t[a[c]])}return e}function k(a){for(var c=0;c<l.length;c++)if(l[c]._doc==a)return l[c]}a.RMB=a.RMB||{};var a=a.RMB,q=a.lib;a.DOMEvents=d;var l=[],t={},s="adform-domevents-";d.destroy=function(a){var c;if(a)(c=k(a))&&c.destroy();else for(;l.length;)l[0].destroy()};
d.on=function(a,c,e){var g=a.ownerDocument;(d.find(g)||new d(g)).on(a,c,e);return this};d.off=function(a,c,e){var g=d.find(a.ownerDocument);g&&g.off(a,c,e);return this};d.find=k;d.dispatchHover=c;d.dispatchClick=function(a,c){for(var e=s+"click-",d=[],o;a&&"undefined"!=(o=typeof a.className);)"string"==o&&0<=a.className.indexOf(e)&&d.unshift(a),a=a.parentNode;o=RegExp(e+"\\S+","g");for(var l=d.length-1;0<=l;l--)for(var k=i(d[l].className,e,o),q=0;q<k.length;q++)k[q].call(d[l],"click",d[l],c)};d._hoverChain=
[];d._hoverTarget=null;a=d.prototype;a.on=function(a,c,e){var d=e._adform_dom_key;d||(d=e._adform_dom_key=q.gid());d in t||(t[d]=e);e=s+c+"-"+d;0>a.className.indexOf(e)&&(a.className+=" "+e,this.setup(c))};a.off=function(a,c,d){if(d=d._adform_dom_key)a.className=a.className.replace(s+c+"-"+d,"")};a.destroy=function(){var a=this._events,c,e,g,o=this._doc;for(c in a)for(e in g=a[c],g)q.removeEvent(o,e,g[e]);for(a=l.length;0<a--;)if(l[a]==this){l.splice(a,1);break}a=d._hoverChain;a[0]&&a[0].ownerDocument==
o&&(d._hoverChain=[],d._hoverTarget=null);this._doc=this._events=null};a.setup=function(a){if(!this._events[a]){this._events[a]={};var c=this._doc,e=c.defaultView||c.parentWindow,g,o;"hover"==a?(c.addEventListener?(g=function(a){d._hoverTarget!=a.target&&(d._hoverTarget=a.target,d.dispatchHover())},o=function(a){d._hoverTarget!=a.relatedTarget&&(d._hoverTarget=a.relatedTarget,d.dispatchHover())}):(g=function(){e=c.defaultView||c.parentWindow;d._hoverTarget!=e.event.srcElement&&(d._hoverTarget=e.event.srcElement,
d.dispatchHover())},o=function(){e=c.defaultView||c.parentWindow;d._hoverTarget!=e.event.toElement&&(d._hoverTarget=e.event.toElement,d.dispatchHover())}),q.addEvent(c,"mouseover",this._events[a].mouseover=g),q.addEvent(c,"mouseout",this._events[a].mouseout=o),q.addEvent(c,"mousemove",this._events[a].mousemove=g),d._hoverChain=[]):"click"==a&&(g=c.addEventListener?function(a){d.dispatchClick(a.target,a)}:function(a){e=c.defaultView||c.parentWindow;a=e.event;d.dispatchClick(a.srcElement,a)},q.addEvent(c,
"mousedown",this._events[a].mousedown=g))}}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function i(a,b){"string"!=typeof a&&(b=a,a="default");if(this instanceof i)this._id="adfrom-styleSheet-"+a,this._doc=b||c;else return new i(a,b)}a.RMB=a.RMB||{};a=a.RMB;a.StyleSheet=i;var k=a.lib,q,l,t,a=i.prototype;a.node=function(){var a=this._doc,b=this._id,c=k.byId(b,a);c||(c=a.createElement("style"),c.type="text/css",c.id=b,c._rules={},k.byTag(a,"head")[0].appendChild(c));if(!q&&(l=c.sheet?"sheet":"styleSheet",a=c[l]))t=a.insertRule?function(a,b,c,d){a.insertRule(b+" {"+c+"}",
d)}:function(a,b,c,d){a.addRule(b,c,d)},q=a&&a.cssRules?"cssRules":"rules";return c};a.set=function(a,b){var c=this.node(),d=c[l],g,o;try{g=c._rules,o=g[a]}catch(k){}var i=a.split(/\s*,\s*/),y,n;try{if(1<i.length)for(y=i.length-1;0<=y;--y)this.set(i[y],b);else if(o)o.style.cssText+=";"+b;else if(!d||!d[q])c.appendChild(this._doc.createTextNode(a+"{"+b+"}"));else if(b){n=d[q].length;try{t(d,a,b,n)}catch(O){setTimeout(function(){t(d,a,b,n)},0)}g&&(g[a]=d[q][n])}}catch(K){}return this};a.destroy=function(){var a=
k.byId(this._id,this._doc);a&&a.parentNode.removeChild(a);this._doc=null}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(){var a=x.bind;c.super_.call(this);this.cssQueue=[];this.id=x.gid(z);this.set({showing:!1,visible:!0}).onchange("visible",M).onchange("element",M).onchange("zIndex",k).onchange(K);this._contents={};this._pos={};this.findElement=a(this,q);this.repositionPage=a(this,y);this.repositionFloated=a(this,O);this.repositionSticky=a(this,A)}function i(a){var b,c;if(b=this._hub)c=this._hubName,b.emit("element",this,c,a)}function k(a){this.style({zIndex:a})}function q(){this._findCalls||
(this._findCalls=(new Date).getTime()+c.fTimeout);var h=x.byId(this.id,this._doc),b=this.get("frame");if(h)this.handleHover=x.bind(this,l),this.handleClick=x.bind(this,t),V.on(b||h,"hover",this.handleHover),x.addEvent(h,"mousedown",this.handleClick),h.innerHTML="",this.set("element",h),this.css(""),this.style();else if(this._findCalls>(new Date).getTime())setTimeout(this.findElement,0);else throw h=this.content(),a.Log.pushMessage(["Adbox"],"Adbox element not found",{bn:h&&h.options.bn}),Error("Adbox element not found");
}function l(a){var b=this.hovered="hoverin"==a;this.emit("hover",b,this);this.emit(a,b,this)}function t(a){this.emit("click",a||this._win.event)}function s(a){var c=this._doc;var m=this.get(),d=m.element;if(d)for(var m=d.className.match(RegExp(z+m.postype+"(-\\w+)?","g")),j=0;j<m.length;j++){var p=m[j];x.hasClass(d,p)&&x.removeClass(d,p)}d=a.from;c=a.type||(!d?"static":d.window==d?"fixed":d===c?"page":"floated");j=a.position||"";m=R.exec(j);j=H.exec(j);m=m?m[0]:X;j=j?j[0]:D;p=this.get();p.vpos=j;
p.hpos=m;p.postype=c;p.frompos=d;this.resetPosition&&this.resetPosition();b.apply(this,[c,p,a])}function b(a,b,c){var r=this,j=r._win,w=r._doc,C=b.element;C&&(x.addClass(C,z+a+"-"+b.vpos),x.addClass(C,z+a+"-"+b.hpos),x.addClass(C,z+a));r.positionType=a;if("static"==a)this.onchange("x",o).onchange("y",o).onchange("showing",o),this.resetPosition=function(){r.off("change:x",o).off("change:y",o).off("change:showing",o);r.resetPosition=null};else if("fixed"==a){var g=w.documentElement,I=w.body,B=!1,l=
!1,i=function(){var a=g.clientWidth||I.clientWidth,h=g.clientHeight||I.clientHeight,j=b.element,c=j.offsetWidth-b.x,j=j.offsetHeight-b.y;if(l!=a<c){a=(l=a<c)?0:"";r.style({left:a,marginLeft:a,marginRight:a})}if(B!=h<j){a=(B=h<j)?0:"";r.style({top:a,marginTop:a,marginBottom:a})}};this.onchange("showing",i);x.addEvent(j,"resize",i);this.onchange(u);S&&(this.iOSFixed=function(){var a={},h=g.scrollLeft||I.scrollLeft,j=g.scrollTop||I.scrollTop,b=g.clientWidth||I.clientWidth,c=g.clientHeight||I.clientHeight;
if(H=="L")a.left=h+"px";if(H=="C")a.left=h+Math.round(b/2)+"px";if(H=="R")a.right=-h+"px";if(v=="T")a.top=j+"px";if(v=="M")a.top=j+Math.round(c/2)+"px";if(v=="B")a.bottom=-j+"px";r.style(a)},x.addEvent(j,"scroll",this.iOSFixed));this.resetPosition=function(){r.off("change:showing",i).off(u);i&&x.removeEvent(j,"resize",i);r.iOSFixed&&x.removeEvent(j,"scroll",r.iOSFixed);r.css("margin:0;left:auto;top:auto;");r.resetPosition=null}}else if("sticky"==a)this.onchange(A),this.handleResize=x.bind(this,e),
x.addEvent(j,"resize",this.handleResize),x.addEvent(j,"scroll",this.handleResize),x.addEvent(j,"load",this.handleResize),this.handleResize(),setTimeout(this.handleResize,50),this.resetPosition=function(){r.off(A);if(r.handleResize){x.removeEvent(j,"resize",r.handleResize);x.removeEvent(j,"scroll",r.handleResize);x.removeEvent(j,"load",r.handleResize)}};else if("page"==a){this.onchange(y);this.resizeDelay=x.singleCall(100);this.handleResize=x.bind(this,f);x.addEvent(j,"resize",this.handleResize);x.addEvent(j,
"scroll",this.handleResize);x.addEvent(j,"load",this.handleResize);this.handleResize();var k=setInterval(this.handleResize,100);setTimeout(function(){clearInterval(k)},3E3);this.resetPosition=function(){r.off(y);if(r.handleResize){x.removeEvent(j,"resize",r.handleResize);x.removeEvent(j,"scroll",r.handleResize);x.removeEvent(j,"load",r.handleResize)}clearInterval(k)}}else if("floated"==a)this.onchange(O),c.container!=c.from?(this.resizeDelay=x.singleCall(10),this.handleResize=x.bind(this,n),x.addEvent(j,
"resize",this.handleResize),this._fromInt=setInterval(this.handleResize,500),x.onload(d,this.handleResize),setTimeout(this.handleResize,50)):setTimeout(function(){O.call(r)},0),this.resetPosition=function(){r.handleResize&&x.removeEvent(j,"resize",r.handleResize);clearInterval(r._fromInt)};else if("mobile"==a){var v=b.vpos,H=b.hpos,s,F,q,G=j.innerWidth,t=j.innerHeight,Y=G>=t,T=!1,a=function(){r.pos.width=r.pos.height=0},R=function(){if(b.showing&&!T){s=C.getBoundingClientRect();G=j.innerWidth;t=j.innerHeight;
if(Y&&G<t||!Y&&G>=t){Y=G>=t;T=true;setTimeout(function(){T=false},500)}else{Y=G>=t;var a=b.width,h=b.height,c=r._vp,d=r.pos||{},a=r._hp?G*parseFloat(a)/100:a,h=c?t*parseFloat(h)/100:h;F=(parseFloat(d.left)||0)-s.left;q=(parseFloat(d.top)||0)-s.top;var e,w;H==P?e=Math.round(F+(G-a)/2):H==X?e=Math.floor(F):H==E&&(e=Math.ceil(F+(G-a)));v==m?w=Math.round(q+(t-h)/2):v==D?w=Math.floor(q):v==p&&(w=Math.ceil(q+(t-h)));r.setPosition(w,e,0,0,0,0,a,h)}}},N=setInterval(R,100);x.addEvent(j,"resize",R);x.addEvent(j,
"scroll",R);r.onchange("showing",R).onchange("width",a).onchange("height",a);R();this.resetPosition=function(){x.removeEvent(j,"resize",R);x.removeEvent(j,"scroll",R);r.resetPosition=null;clearInterval(N)}}}function f(){this.repositionPage({showing:1})}function e(){this.repositionSticky({showing:1})}function g(a){var b=a.defaultView||a.parentWindow;b.self||(b=d);var c=a.documentElement||a.body;this._doc=a;this._win=b;this.sheet=N("adbox",a);if(!b.__adform_adbox_init){var m=N("adbox-static",a);m.set("."+
z+"hidden","visibility:hidden").set("."+z+"mobile","position:absolute").set("."+z+"static","position:relative").set("."+z+"static-L","margin:0 auto 0 0").set("."+z+"static-C","margin:0 auto").set("."+z+"static-R","margin:0 0 0 auto").set("."+z+"static-I","display:inline-block;*display:inline;zoom:1").set("."+z+"floated","position:absolute;display:block!important").set("."+z+"page,."+z+"fixed,."+z+"sticky","position:fixed;display:block!important").set("."+z+"page-L,."+z+"fixed-L","left:0").set("."+
z+"page-C,."+z+"fixed-C","left:50%").set("."+z+"page-R,."+z+"fixed-R","right:0").set("."+z+"page-T,."+z+"fixed-T","top:0").set("."+z+"page-M,."+z+"fixed-M","top:50%").set("."+z+"page-B,."+z+"fixed-B","bottom:0").set("."+z+"overlay","position:fixed;right:0;bottom:0;width:300%;height:300%").set("."+z+"overlay iframe","display:none;position:absolute;top:0;right:0;width:100%;height:100%").set("* html ."+z+"page,* html ."+z+"fixed","position:absolute").set("* html ."+z+"fixed-L","left:expression(eval(__adform_adbox_fixedLeft(this)))").set("* html ."+
z+"fixed-C","left:expression(eval(__adform_adbox_fixedCenter(this)))").set("* html ."+z+"fixed-R","left:expression(eval(__adform_adbox_fixedRight(this)))").set("* html ."+z+"fixed-T","top:expression(eval(__adform_adbox_fixedTop(this)))").set("* html ."+z+"fixed-M","top:expression(eval(__adform_adbox_fixedMiddle(this)))").set("* html ."+z+"fixed-B","top:expression(eval(__adform_adbox_fixedBottom(this)))").set("* html ."+z+"overlay","position:absolute;top:expression(eval(__adform_adbox_fixedTop(this)));left:expression(eval(__adform_adbox_fixedLeft(this)));width:100%;height:100%");
Y&&"BackCompat"==a.compatMode&&m.set("."+z+"page","position:absolute");b.__adform_adbox_fixedLeft=function(){return c.scrollLeft};b.__adform_adbox_fixedCenter=function(){return c.scrollLeft+Math.round(c.clientWidth/2)};b.__adform_adbox_fixedRight=function(a){return c.scrollLeft+c.clientWidth-a.offsetWidth};b.__adform_adbox_fixedTop=function(){return c.scrollTop};b.__adform_adbox_fixedMiddle=function(){return c.scrollTop+Math.round(c.clientHeight/2)};b.__adform_adbox_fixedBottom=function(a){return c.scrollTop+
c.clientHeight-a.offsetHeight};b.__adform_adbox_init=0}b.__adform_adbox_init++}function o(){var a=this.get();a.showing&&this.style({left:a.x+"px",top:a.y+"px"})}function u(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a)){var a=b.vpos,c=b.width,d=b.height,j="",p=b.y,r=b.x;b.hpos==P&&(this._hp?j+="left:"+(50-parseFloat(c)/2)+"%;":r-=c/2);a==m&&(this._vp?j+="top:"+(50-parseFloat(d)/2)+"%;":p-=d/2);this.css(j+"margin:"+p+"px "+-r+"px "+-p+"px "+r+"px")}}
function A(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a||"stickyOffset"in a)){var c=this._win,d=this._doc,j=b.element,e=this.from(),f=x.offsetFromWindow(e),a=b.stickyOffset||0;!0===a&&(f.top=x.offset(e).top,a=f.top);var g=this._hp,I=this._vp,n=b.x,l=b.y,o=g?j.offsetWidth:b.width||0,i=I?j.offsetHeight:b.height||0,j=f.left,v=f.top,f=e.offsetWidth,e=e.offsetHeight,H=c.innerWidth||d.body.clientWidth,k=c.innerHeight||d.body.clientHeight,D=b.vpos,s=b.hpos,
c=s==T,d=s==P,F=s==E,s=s==B,G=D==C,q=D==m,z=D==p,D=D==r;g&&(o=H*parseFloat(b.width)/100,this.style({width:o+"px"}));I&&(i=k*parseFloat(b.height)/100,this.style({height:i+"px"}));b=l+v+(G?-i:q?(e-i)/2:z?e-i:D?e:0);this.setPosition(b>a?b:a,n+j+(c?-o:d?(f-o)/2:F?f-o:s?f:0),0,0)}}function y(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a)){var c=this._win,d=b.vpos,j=b.hpos,e=b.x,f=b.y,g=b.element,I=this._hp,a=I?g.offsetWidth:b.width,g=this._vp?g.offsetHeight:
b.height,n=j==T,o=j==P,l=j==E,i=j==B,D=d==C,H=d==m,k=d==p,s=d==r;if(this._absolute||"absolute"==x.curCSS(b.element,"position"))this._absolute||(x.removeEvent(c,"resize",this.handleResize),x.removeEvent(c,"scroll",this.handleResize)),this._absolute=!0,f=Math.round(d==m?-(g/2):0)+f,b=Math.round(j==P?-(a/2):0)+e,this.setPosition(null,null,k?0:f,l?0:b,k?-f:0,l?-b:0);else{var j=this._doc,c=j.documentElement,F=j.body;Math.max(c&&c.clientWidth||0,F&&F.clientWidth||0);var j=c&&c.clientHeight||F&&F.clientHeight,
d=Math.max(c&&c.scrollWidth||0,F&&F.scrollWidth||0),G=Math.max(c&&c.scrollLeft||0,F&&F.scrollLeft||0),c=Math.max(c&&c.scrollTop||0,F&&F.scrollTop||0);I&&this.style({width:(a=Math.round(d*parseFloat(b.width)/100))+"px"});b=-G+(n?-a:o?(d-a)/2:l?d-a:i?d:0)+e;f=-c+(D?-g:H?(j-g)/2:k?j-g:s?j:0)+f;e=this._pp||(this._pp={t:0,l:0});(e.t>-g&&e.l>-a||f>-g&&b>-a)&&this.setPosition(f,b,0,0);e.t=f;e.l=b}}}function n(){if(this.get().showing){var a=this.from();if(a){var b=x.offset(a);b.w=a.offsetWidth;b.h=a.offsetHeight;
a=this._lastFromPos;if(!a||a.left!=b.left||a.top!=b.top||a.w!=b.w||a.h!=b.h)this._lastFromPos=b,O.call(this)}}}function O(a){if(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a){var b=this.get();if(b.showing){var c=this.from();if(c){var d=b.vpos,a=b.hpos,j={},e=this._hp,f=this._vp;e&&(j.width=Math.round(c.offsetWidth*parseFloat(b.width)/100)+"px");f&&(j.height=Math.round(c.offsetHeight*parseFloat(b.height)/100)+"px");(e||f)&&this.style(j);var g=b.element,j=b.x,I=b.y,e=e?g.offsetWidth:
b.width,f=f?g.offsetHeight:b.height,g=x.offset(c),b=b.element.parentNode;"static"!=x.curCSS(b,"position")&&(b=x.offset(b),g.top-=b.top,g.left-=b.left);var b=c.offsetWidth,c=c.offsetHeight,n=a==P,o=a==E,l=a==B,i=d==m,D=d==p,H=d==r,b=g.left+(a==T?-e:n?b/2:o?b-e:l?b:0),g=g.top+(d==C?-f:i?c/2:D?c-f:H?c:0),d=Math.round(d==m?-(f/2):0)+I,a=Math.round(a==P?-(e/2):0)+j;this.setPosition(g,b,d,a)}}else this.setPosition(-3E3,-3E3,0,0)}}function K(a){if(("width"in a||"height"in a)&&"mobile"!=this.positionType){var b=
this.get(),a=b.width,b=b.height,c=this._hp="string"==typeof a&&0<a.indexOf("%"),m=this._vp="string"==typeof b&&0<b.indexOf("%");this.style({width:"auto"===a?a:c?a:a+"px",height:"auto"===b?b:m?b:b+"px"})}}function M(){var a=this.get(),b=a.visible,c=this,m=a.element;if(m){var j=this._visibilityTimer;j&&(j=clearTimeout(j));var d=function(){c._visibilityTimer=!1;var a=m.className,h=~a.indexOf(" adform-adbox-hidden");h&&b?m.className=a.replace(" adform-adbox-hidden",""):!h&&!b&&(m.className=a+" adform-adbox-hidden")};
m.addEventListener?Y?d():j=setTimeout(d,b?10:100):d();this._visibilityTimer=j}this.set("showing",b&&!!a.element)}function F(a){this.emit("content:"+(a?"show":"hide"),this.get("element"),this);this.emit(a?"show":"hide")}a.RMB=a.RMB||{};var G=a.RMB,x=G.lib,N=G.StyleSheet,V=G.DOMEvents,Y=x.isIOS,S=Y&&!x.isIOSF,z="adform-adbox-",T="K",X="L",P="C",E="R",B="E",C="Y",D="T",m="M",p="B",r="N",I=[T,X,P,E,B,"I"],H=RegExp([C,D,m,p,r].join("|")),R=RegExp(I.join("|"));G.AdBox=c;c.LEFT_OUT=T;c.LEFT=X;c.CENTER=P;
c.RIGHT=E;c.RIGHT_OUT=B;c.TOP_OUT=C;c.TOP=D;c.MIDDLE=m;c.BOTTOM=p;c.BOTTOM_OUT=r;c.INLINE="I";c.CLASS="adform-adbox";c.PREFIX=z;c.hPosRegExp=R;c.vPosRegExp=H;c.fTimeout=1E4;x.inherit(c,G.StateEmitter);c.toCustom=function(a,b,c){var d=R.exec(c),c=H.exec(c),d=d?d[0]:X,c=c?c[0]:D,j=b.width,e=b.height,f=a.width,a=a.height,g=d==P,I=d==E,n=d==B,o=c==m,l=c==p,i=c==r;return{x:(d==T?-j:g?(f-j)/2:I?f-j:n?f:0)+b.x,y:(c==C?-e:o?(a-e)/2:l?a-e:i?a:0)+b.y}};G=c.prototype;G.css=function(a,b){if(this.sheet){if(this.cssQueue){var c=
this.cssQueue,m=0,j=c.length;for(this.cssQueue=null;m<j;m+=2)this.css(c[m],c[m+1])}this.sheet.set("#"+this.id+(b?" "+a:""),b||a)}else this.cssQueue.push(a,b);return this};G.content=function(a,b,c){!c&&"string"==typeof b&&(c=b,b=!1);c=c||"main";a&&(this._contents[c]=a,a.bind(this),b&&(a=a.data,this.set({width:a.width,height:a.height})));return this._contents[c]};G.setPosition=function(a,b,c,m,j,d,e,p){if(this.get("element")){var a={top:a,left:b,marginTop:c,marginRight:d,marginBottom:j,marginLeft:m,
width:e,height:p},b=this.pos||{},c=!1,m={},f;for(f in a)a[f]!=b[f]&&(c=!0,m[f]=a[f]+"px");c&&(this.pos=a,this.style(m))}};G.from=function(){var a=this.get("frompos");if("string"==typeof a&&(a=x.byId(a,this._doc))){if("OBJECT"==a.nodeName&&30>a.offsetHeight){var b=x.byTag(a,"embed")[0];b&&20<b.offsetHeight&&(a=b)}this.set("frompos",a)}return!a||a.attr&&!(a=a.get("element"))?void 0:a};G.style=function(a){var b=this.get("element");b?(this._styles&&(x.extend(b.style,this._styles),this._styles=null),a&&
x.extend(b.style,a)):this._styles=x.extend(this._styles||{},a);return this};G.reset=s;G.destroy=function(){var a=this.get("element"),b=this.get("frame");if(a){this.emit("content:destroy",a,this);this.clear();this._contents=null;var c=this._win,m=this._doc;V.off(b||a,"hover",this.handleHover);x.removeEvent(a,"mousedown",this.handleClick);this.resetPosition&&this.resetPosition();var j,d;(j=this.handleResize)&&x.removeEvent(c,"resize",j);(d=this._fromInt)&&clearInterval(d);--c.__adform_adbox_init||(N("adbox-static",
m).destroy(),this.sheet.destroy(),c.__adform_adbox_fixedLeft=c.__adform_adbox_fixedCenter=c.__adform_adbox_fixedRight=c.__adform_adbox_fixedTop=c.__adform_adbox_fixedMiddle=c.__adform_adbox_fixedBottom=null);this.sheet=null;this._changes={};this._previous={};this._attributes={};a.parentNode&&a.parentNode.removeChild(a)}};G.draw=function(a,b){var c,m,j,b=b||{};if(c=this._hub)m=this._hubName,c.emit("draw",this,m,b);this.set("frame",b.frame);c=b.container;m=b.before;j=b.from;a=c&&c.ownerDocument||m&&
m.ownerDocument||j&&(j.ownerDocument||j._doc||(j.defaultView||j.parentWindow||j).document)||a;g.call(this,a);s.call(this,b);c=b;m=c.from;j=c.container;var d=c.before,e=this.get(),f=e.postype,p=this._doc,f='<div id="'+this.id+'" class="adform-adbox '+(e.visible?"":z+"hidden ")+z+f+" "+z+f+"-"+e.vpos+" "+z+f+"-"+e.hpos+'">AdBox</div>';if(!m&&!d&&!j)p.write(f);else{try{p.body||p.write("<html><body></body></html>")}catch(r){}if(p.body.insertAdjacentHTML&&x.isIE){var E="afterBegin";m?(j||(j=p.body),"end"==
d&&(E="beforeEnd")):d&&(E="beforeBegin",j=d);try{j.insertAdjacentHTML(E,f)}catch(C){p.write(f)}}else m?(j||(j=p.body),d=null):d&&(j=d.parentNode),j.insertBefore(x.html(f,p),d||j.firstChild)}this.set({x:c.x||e.x||0,y:c.y||e.y||0});this.onchange("showing",F);this.findElement();return this};G.pull=function(a,b){var c=this.get();if(a in c)b.call(this,c[a]);else this.once("change:"+a,b);return this};G.publish=function(a,b){this._hubName=a;this._hub=b;this.pull("element",i);return this}})(Adform=window.Adform||
{},window,document);
(function(a){var d,c;function i(a){var f=q?d:l?c:{},e;for(e in a)a.hasOwnProperty(e)&&f[e]&&(s[f[e]]=a[e])}if(!a.IframeApiWrapper){var k=new a.RMB.EventEmitter,q,l,t,s;t={over:!1,pushdown:!1};d={width:"width",height:"height",left:"offsetLeft",right:"offsetRight",top:"offsetTop",bottom:"offsetBottom"};c={width:"width",height:"height",left:"l",right:"r",top:"t",bottom:"b",pushdown:"push"};s={};k.support=t;k.init=function(a){l=a.$sf&&a.$sf.ext;if(a.inDapMgrIf||a.inDapIF||a.inFIF)try{q=a.$WLXRmAd||a.parent.$WLXRmAd}catch(c){}k.msAPI=
q;k.sfAPI=l;k.hasAPI=!(!q&&!l);q?(t.over=!0,t.pushdown=!1):l&&(a=l.supports(),t.over="1"===a["exp-ovr"],t.pushdown="1"===a["exp-push"])};k.register=function(a){i(a);q?q.init(s):l&&l.register(a.width,a.height,function(a){k.emit(a)})};k.update=i;k.expand=function(a){if(a)k.once("expanded",a);q?(q.expand(),k.emit("expanded")):l&&l.expand(s)};k.collapse=function(a){if(a)k.once("collapsed",a);q?(q.collapse(),k.emit("collapsed")):l.collapse()};a.IframeApiWrapper=k}})(Adform=window.Adform||{});
(function(a,d,c){function i(j){var h=u.extend({},p),E=u.extend({},p),g=u.extend({},r),o=u.extend({},r),i=u.extend({},I),B=u.extend({},H),D=u.extend({},H),k={},v=u.extend({},R),P;try{P=d.MESSENGER||-1<location.host.toLowerCase().indexOf("rad.msn.com")}catch(aa){}v.messenger=P;v.iab=d.inDapMgrIf||d.inDapIF||d.inFIF;v.iframeAPI=a.IframeApiWrapper;v.iframeAPI.init(d);var J=!j.flashvars;v.backCompat=!J;var U=j.clicktags=f(j.clicktags),ha=U.backupClickUrl,Bb=[0,"MC","TC","TL","TR","BL","BR","ML","MR","BC"],
oa,ea,ia;for(ia in j){var Q=m[ia]||ia,L=j[ia],Fa;switch(Q){case "bsrc":!i.poster&&(i.poster=L);case "src":var ua=b(L,U);oa=L.match(X)?h:L.match(T)?B:g;oa.src=L;oa.assetId=ua;!i.assetId&&(i.assetId=ua);break;case "besrc":i.poster=L;case "esrc":ua=b(L,U);oa=L.match(X)?E:L.match(T)?D:o;oa.src=L;(oa.assetId=ua)&&(i.assetId=ua);break;case "width":case "height":h[Q]=g[Q]=k[Q]=B[Q]=L>>0;!i[Q]&&(i[Q]=L>>0);break;case "ewidth":case "eheight":Q=Q.slice(1);E[Q]=o[Q]=i[Q]=D[Q]=L>>0;break;case "wmode":P&&"window"==
L&&(L="opaque");case "version":case "quality":h[Q]=E[Q]=B[Q]=D[Q]=L;break;case "flashvars":ea=h[Q]=E[Q]=B[Q]=D[Q]=L;break;case "link":ha=J?e(encodeURIComponent(L)):L;break;case "css":Fa=L.split("/assets/css/"),v.scriptsBase=a.scriptBase||Fa[0]+"/",L=v.scriptsBase+"assets/css/"+Fa[1];case "sources":v[Q]=i[Q]=L;break;case "ADFPoliteSrc":k.src=L;k.assetId=b(L,U);break;case "showType":v[Q]=0==L?1:2==L?2:0;break;case "hideType":v[Q]=1==L?0:1;break;case "floatPosition":v[Q]=Bb[L];break;case "behavior":v[Q]=
{"0":"default",1:"pushdown",2:"sidekick",3:"floating",takeOver:"takeover",4:"slider"}[L];break;case "zIndex":var ab=parseInt(L,10);v[Q]=isNaN(ab)?v.zIndex:ab;break;default:v[Q]=L}}var Cb=v.bn=U.bn,Db=v.userParams=v.userParams||{},ja=t(),Z=ja&&ja.banners&&ja.banners[v.xId];if(Z){var ka=Z.clickEvent;if(ka&&(ka=ka.match(S))&&(ka=ka[1]))Z.compoundSeqNo=v.seqNo=ea.seqNo=ka&&+ka;Z.cookieID&&(ea.icid=Z.cookieID);var bb=ja.getPropByBn&&ja.getPropByBn("animURL",Cb);bb&&(Db.animURL=bb);var cb=ja.getRotSeed&&
ja.getRotSeed().id;cb&&(ea.hash=cb);var db=Z.rotseqno;db&&(ea.rotseqno=db);var eb=Z.smid;eb&&(ea.smid=eb);var fb=Z.timeDiff;fb&&(ea.timeDiff=fb);if(Z.isDSPTag&&d!=d.parent)try{d.parent.document.getElementById,d.inFIF=v.iab=!0}catch(Rb){a.ADFIframe=1}var gb=Z.unloadScriptVersion;gb&&(v.unloadVersion="v"+gb);Z.sendUnloadData&&(v.sendUnload=!0)}"takeover"==v.behavior&&(v.autoShow=O,v.autoHide=K);P&&(v.showDelay=Math.max(v.showDelay,n),v.restartAnimation=1);v.iframeAPI.msAPI&&!v.showType&&(v.showType=
1);ea.wmode=h.wmode;var hb=d.ADFDomainCDN;hb&&(ea.hvfdomain=hb);var ga=v.type;ga==M&&"slider"==v.behavior&&(ga=v.type=Y);if(ga==G||ga==V)ha=U.clickTAG;if(ha){if(J)for(var ib,ba=3;ba--&&(2>(ib=ha.indexOf("://"))||8<ib);)try{ha=decodeURIComponent(ha)}catch(Sb){ba=0}B.link=D.link=g.link=o.link=i.link=k.link=ha}ga==F&&(v.behavior=F);var Ga=s(),Ha;if(a.ADFIframe)Ha=location.search;else{for(var Eb=RegExp("[?;]bn="+v.bn+"\\b"),jb=v.seqNo&&RegExp("[?;]compoundSeqNo="+v.seqNo+"\\b"),va,Ia=u.byTag(c,"script"),
Ja=Ia.length;Ja--;){var Aa=Ia[Ja].src;if(Aa&&0<Aa.indexOf("adfscript")&&Aa.match(Eb)&&(!jb||Aa.match(jb))){va=Ia[Ja];break}}if(u.isIE){for(var wa=va,kb=c.body;wa&&wa!=kb;)wa=wa.parentNode;wa==kb&&(v.$tag=va)}Ha=va&&va.src}var lb=Ha,Ka=lb&&lb.match(z);Ka&&Ka[1]&&(v.obaId=Ka[1],v.adNotice=1,Ga.link=C);if(Z&&Z.adNotice||v.adNotice)B.adNotice=h.adNotice=g.adNotice=Ga,ga!=M&&(i.adNotice=Ga),v.adNotice=1;if(ga==G&&(v.restartAnimation=1,Z)){Z.floatFrom&&(v.position=Z.floatPosition>>0,v.floatFrom=Z.floatFrom);
var mb=parseInt(Z.showFloat,10);v.showFloat=isNaN(mb)||1<=mb?1:0}ga==N&&(E.src=h.src,D.src=B.src,"sidekick"!=v.behavior&&(v.sideKickAnim=1),!v.sideKickAnim&&(ea.useAsMask=!1));var la=B.flashvars,nb=d.ADFDynamicDomain;la.staticDomain=la.domain;d.ADFDomain&&nb&&(la.domain=encodeURIComponent(nb));var La={};for(ia in la){L=la[ia];try{L=decodeURIComponent(L)}catch(Tb){}La[ia]=L}var ma=j.videoSources,Ma=[],ob=ma,Fb=decodeURIComponent(la.staticDomain),Gb=decodeURIComponent(la.hvfdomain),pb;for(pb in ob){var pa=
ob[pb];pa&&pa.file&&!~pa.file.indexOf("://")&&(pa.file=("true"==pa.isStreaming+""&&Gb||Fb)+pa.file)}if(ma){var qb=ma,Na,Oa,Pa,Ba,Ca,fa,Qa,qa,Ra,Sa,rb,sb,tb;Na=[];Oa=a.ENV&&a.ENV.akamaiHost;sb=/avc1\.(..)(..)(..)/;tb=/mp4a\.40\.(?:2|5)/;for(Pa=qb.length;Pa--;)if(Ba=qb[Pa])if(Ca=Ba.codecs,fa=Ba.file,Ca&&fa&&(fa.indexOf(Oa)||!~fa.indexOf("/master.m3u8")))Ra=(qa=Ca.match(sb))&&qa[1].toLowerCase(),Sa=qa&&parseInt(qa[3],16),qa="42"===Ra&&30>=Sa||"4d"===Ra&&31>=Sa,rb=Ca.match(tb),qa&&rb&&(Qa=fa.indexOf("/Stream/"),
~Qa&&(fa=fa.substr(Qa,fa.length-1),Na.unshift({file:Oa+fa+"/master.m3u8",mime:"application/x-mpegURL",codecs:Ba.codecs})));for(var ma=Na.concat(ma),ba=0,ub,Hb=ma.length;ba<Hb;ba++)(ub=ma[ba])&&Ma.push(ub);Ma.length&&(La.videoSources=i.sources=Ma)}B.flashvars=D.flashvars=La;var xa=v.AdformBgImage&&v,vb=t(),wb=vb&&vb.banners,xb;for(xb in wb){var Ta=wb[xb];if(Ta.bn==v.bn&&Ta.AdformBgImage){xa=Ta;break}}if(xa){var Ua='url("'+xa.AdformBgImage+'")',yb={Color:"",Repeat:"",Scroll:"",HorizontalPosition:"center",
VerticalPosition:"top"},Va;for(Va in yb)Ua+=" "+(xa["AdformBg"+Va]||yb[Va]);v.wallpaper={link:xa.AdformBgLink,background:Ua}}var ra=v.position,Wa=v.expPosition;switch(v.type){case x:var Xa={left:"L",center:"C",right:"R"};v.position=Xa[ra]||(v.backCompat?"I":"C");break;case V:v.fixed=1;var ya=(v.y?"T":"M")+(v.x?"L":"C");v.position=ya;v.x>>=0;v.y>>=0;break;case G:var Ya=v.floatFrom,Ib={1:"M",2:"T",3:"T",4:"T",5:"B",6:"B",7:"M",8:"M",9:"B"},Jb={1:"C",2:"C",3:"L",4:"R",5:"L",6:"R",7:"L",8:"R",9:"C"},
Kb={1:"M",2:"Y",3:"Y",4:"Y",5:"N",6:"N",7:"M",8:"M",9:"N"},Lb={1:"C",2:"C",3:"K",4:"E",5:"K",6:"E",7:"K",8:"E",9:"C"},Mb=Ya?Kb:Ib,Nb=Ya?Lb:Jb;v.x>>=0;v.y>>=0;if(!Ya&&(0>v.x&&(v.x=0),0>v.y))v.y=0;var Ob=Mb[ra]||"M",Pb=Nb[ra]||"C",ya=(v.y?"T":Ob)+(v.x?"L":Pb);v.position=ya;break;case M:case N:Xa={left:"L",center:"C",right:"R"};v.position=v.colPosition=Xa[ra]||ra;v.expPosition={custom:"TL","left-up":"BR",takeOver:"BR",left:"TR","left-down":"TR",up:"BL","right-up":"BL",down:"TL",right:"TL","right-down":"TL"}[Wa]||
Wa;"custom"!=Wa&&(v.expX=v.expY=0);break;case F:ya="2"==""+ra?"TR":"TL",v.position=v.colPosition=v.expPosition=ya}v.disturber=new A;var W={};W.flash=W.colFlash=h;W.expFlash=E;W.image=W.colImage=g;W.expImage=o;W.video=i;W.html=W.colHtml=B;W.expHtml=D;W.polite=k;W.options=v;W.events=new A;var ca=W.options,za={zIndex:ca.zIndex-1};ca.overlayOpacity&&(za.opacity=(ca.overlayOpacity>>0)/100);ca.overlayColor&&(za.background=ca.overlayColor);var Za={bn:ca.bn,closeOnClick:ca.overlayCloseOnClick||1,style:za},
Da=(ca.iab?parent:d).ADFORM_OVERLAY||d.ADFORM_OVERLAY,da;if(ca.type==G&&Da){for(var Ea=0,Qb=Da.length;Ea<Qb;Ea++)if(ca.bn==Da[Ea].bn){da=Da[Ea];break}if(da&&(typeof da.callFrom!=y&&(Za.callFrom=da.callFrom),typeof da.closeOnClick!=y&&(Za.closeOnClick=da.closeOnClick),da.color&&(za.background=da.color),da.opacity))za.opacity=da.opacity}if(da||ca.overlayOpacity)W.overlay=Za;var $={};for(ba in W)if(W[ba].src||W[ba].sources)$[ba]=W[ba];$.options=v;$.events=W.events;W.overlay&&($.overlay=W.overlay);"window"!=
h.wmode&&q($);i.sources&&(i.loop="true"==""+U.loopVideo,i.muted="true"!=""+U.soundOn,i.autoplay="true"==""+U.autoPlay,l(v,i));if(u.isSafari&&6.1<=u.safariVersion&&($.image||$.html||$.expImage||$.expHtml))delete $.flash,delete $.colFlash,delete $.expFlash;return $}function k(a,b){for(var c in b)b.hasOwnProperty(c)&&("object"==typeof b[c]?("object"!=typeof a[c]&&(a[c]={}),k(a[c],b[c])):a[c]=b[c])}function q(a){var b=a.options,c=b.socializeURL;if(c){var c={linkBack:c,css:b.css,position:"BL"},b=b.type,
h=b!=N&&a.expFlash||a.flash,m=b!=N&&a.expHtml||a.html,d=a.expImage||h==a.flash&&a.image,e=a.video;h&&(h.social=u.extend({width:(b==N?a.expFlash:h).width},c));d&&(d.social=u.extend({width:d.width},c));m&&(m.social=u.extend({width:m.ewidth},c));e&&(e.social=u.extend({width:e.width},c),e.social.position="TL"==e.closeButtonAlign?"TLV":"TL")}}function l(a,b){switch(a.type){case M:case N:b.closeButtonAlign={BR:"TL",TR:"BL",BL:"TR",TL:"BR"}[a.expPosition]||b.closeButtonAlign;"TR"==b.closeButtonAlign&&b.adNotice&&
(b.closeButtonAlign="TL");break;case F:b.closeButtonAlign="TL"==a.position?"BR":"BL";break;case G:b.closeButtonAlign=b.adNotice?"TL":"TR"}}function t(){var b=a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()}function s(){return{title:P,linkText:D,text:E,link:B}}function b(a,b){return a&&~a.indexOf(aa)&&a.match(U)[1]||b&&b[J]||0}function f(a){if("string"!=typeof a)return a||{};for(var b={},a=a.split("&"),c=0,h=a.length,m;c<h;c++)m=a[c].split("="),b[m.shift()]=e(m.join("="));return b}function e(a){if(!a)return a;
a=decodeURIComponent(a);0<=a.indexOf("&")||!a.indexOf("http")?a=encodeURIComponent(a):0<=a.indexOf(";CREFURL=")&&(a=a.split(";CREFURL="),a=a.concat(a.pop().split(";C=")),a=a[0]+";CREFURL="+encodeURIComponent(a[1])+(a[2]?";C="+a[2]:""));return a}a.RMB=a.RMB||{};var g=a.RMB,o=g.DataParser||(g.DataParser={}),u=g.lib,A=g.EventEmitter,y="undefined",n=0.5,O=0.01,K=8,M=o.EXPANDING="expanding",F=o.TEARBACK="tearback",G=o.FLOATING="floating",x=o.STANDARD="standard",N=o.SINGLE_EXPANDING="singleExpanding",V=
o.INTERSTITIAL="interstitial",Y=o.SLIDER="slider",S=/compoundSeqNo=(\d+)/,z=/;obaId=([^;]+)/,T=/\.js(\?|$)/i,X=/\.swf(\?|$)/i,P="Adform.com",E="Would you like to know more about why you are seeing this ad?",B="http://www.youronlinechoices.com/",C="http://www.adform.com/site/privacy-policy/",D="Read more";o.getData=function(){if(a.IFrameManager&&a.IFrameManager.bannerData){var b=i(a.IFrameManager.bannerData);b.options.iframeManager=!0;var c=b.options.userParams;if("string"==typeof c){for(var c=c.split("|||"),
m,h={},d=0,e=c.length;d<e;d++)m=c[d].split("="),h[decodeURIComponent(m.shift())]=decodeURIComponent(m.join("="));b.options.userParams=h}if(b.video&&(c=b.video,"string"==typeof c.sources)){m=c.sources.split("|||");for(var h=0,d=m.length,p=[],f,r;h<d;h++)if(m[h])if(0<m[h].indexOf("|")){p.push(f={});r=m[h].split("|");for(e=0;e<r.length;e+=2)f[r[e]]=r[e+1]}else"false"!=m[h]&&p.push({file:m[h]});c.sources=p}return b}b=a.RMBData;a.BannerList&&a.BannerList.length&&(b=a.BannerList.shift());if(b)return i(b)};
o.parseFlashvars=f;o.fixFlashvarsValue=e;o.applyHooks=function(a,b){var c=a.options,m=c.bn,e=t(),p=((c.iab?parent:d)._adform||[]).slice(0);c.iab&&p.push.apply(p,d._adform||[]);e&&e.getPropByBn&&(e=e.getPropByBn("multiPanel",m))&&p.push.apply(p,e);if(u.isArray(p)&&p.length){for(var c=b||["",m,"#"+c.seqNo,m+"#"+c.seqNo,c.xId],m={},f=c.length,r=p.length,e=0;e<f;e++)m[c[e]]={};for(var E=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,g,C,I,i,n,e=0;e<r;e++)if(g=p[e][0].match(E),C=m[g[1]||""]){I=p[e][1];
if(g[2]){g=g[2].split(".");for(n=i={};1<g.length;)i=i[g.shift()]={};i[g[0]]=I;I=n}if(g=I.on)for(var o in g){if("function"==typeof g[o])a.events.on(o,g[o])}else if(I.init)a.events.on("init",I.init);g={};for(i in I)h[i]&&(g[i]=I[i]);k(C,g)}p=m[c[0]];for(e=1;e<f;e++)k(p,m[c[e]]);for(e in h)if(e in p){g=h[e].split(".");for(n=i={};1<g.length;)i=i[g.shift()]={};i[g[0]]=p[e];k(a,n)}}i=(a.html||a.flash||a.image||a.video||{}).adNotice||s();if(p=a.options._adNotice){for(var B in p)p.hasOwnProperty(B)&&(i[B]=
p[B]);delete a.options._adNotice}(!a.flash||"window"!=a.flash.wmode)&&q(a);a.video&&l(a.options,a.video);return a};var m={ADFInitFlash:"src",ADFFlash:"src",ADFTearFlash:"esrc",tearWidth:"ewidth",tearHeight:"eheight",fVer:"version",ADFVer:"version",clicktags:"flashvars",ADFBuckup:"bsrc",bclickUrl:"link",backupClickURL:"link",ADFBuckupClickURL:"link",videoSources:"sources",bannerAlign:"position",expandsTo:"expPosition",adfxid:"xId",ADFid:"xId",expandDelay:"showDelay",expandTime:"showTime",collapseTime:"hideTime",
autoShowAfter:"autoShow",showTimeout:"autoShow",autoCloseAfter:"autoHide",closeTimeout:"autoHide",showOnRollOut:"showType",closeOnRollOut:"hideType",keepCollapsed:"keepCollapsed",politeTimeout:"loadDelay",expandedX:"expX",expandedY:"expY","":""},p={src:"",width:0,height:0,version:7,play:!0,menu:!1,loop:!0,quality:"autohigh",wmode:"opaque",bgcolor:null,allowScriptAccess:"always",allowFullScreen:!0,flashvars:{}},r={src:"",width:0,height:0,link:""},I={width:0,height:0,poster:"",css:null,closeButtonAlign:null,
loop:"false",muted:"true",autoplay:"false",link:null,assetId:0},H={src:"",width:0,height:0,flashvars:{}},R={position:"L",colPosition:"C",expPosition:"TL",x:0,y:0,expX:0,expY:0,xId:"1x",zIndex:1E5,fixed:0,restartAnimation:0,clickEvent:"",showDelay:0,showType:0,hideType:0,autoShow:0,autoHide:0,behavior:"default",frameRate:0,showTime:0,hideTime:0,loadDelay:0,type:"none",keepCollapsed:0,sideKickAnim:1,landingPageTarget:"_blank",showFloat:1},h={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",
x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",panel:"panel"},J="ADFassetID",aa=J+"=",U=RegExp(aa+"(\\d*)")})(Adform=window.Adform||{},window,document);
(function(a,d){function c(a,b,c){for(var a=a.replace(/[\r\n]+/g,b),d={},a=a.split(b),e=a.length,f,g,b=0;b<e;b++){g=a[b].split(c);f=g.shift();var i=d;g=g.join(c);i[f]=!g?null:"true"===g||"false"===g?"true"===g:1*g==g?1*g:g}return d}function i(a){var b=a.options,c=a.panel.from,e;!{standard:1,expanding:1,singleExpanding:1}[b.type]||"floating"==b.behavior?g.AdConstructor.initialize(a):("number"==typeof c?b=k(a):"string"==typeof c?(b=o.byId(a.panel.from,(a.options.iab?d.parent:d).document))?(l(a,{container:b},
!0),b=void 0):b=!0:(l(a,{before:a.options.iab&&d.frameElement},!0),b=void 0),e=b);e?(y.push(a),n||(n=setTimeout(q,100))):y.length&&i(y.shift())}function k(a){var b=O[a.options.bn+"#"+a.panel.from];if(!b||!b.box)return!0;var c=a.panel,d=f(c.position,!0),e=b.settings,g=e.image||e.html||e.video||e.flash,e=(e=e.panel)&&e.space,i;if(e&&g&&"C"!=d&&(i=e.width>>0))i=0.5*(i-g.width),c.x=(c.x||0)+("L"==d?-1:1)*i;b.box.pull("element",function(){l(a,{from:b.box})})}function q(){n=0;y.length&&i(y.shift())}function l(a,
b,c){function e(d){var g=I?"stickyBox":"box";r=B[g]=(new A).publish("panel-"+g,a.events);R&&r.set("zIndex",q.zIndex=R);r.set({width:h,height:C?J:"auto",x:!I&&u.x||0,y:!I&&u.y||0,visible:!u.hidden}).set(D?{stickyOffset:u.sticky}:{}).pull("element",i).draw(E,{type:D&&"sticky",position:I?"":f(u.position,c),container:m,before:p,from:d||b.from})}function i(b){b.innerHTML="<span></span>";q.iab=!1;q.window=y;q.$tag=b.firstChild;b={item:B,settings:a,content:k};q.panel=b.exports={set:o.bind(b,t),get:o.bind(b,
s)};b.constructor=H=g.AdConstructor.initialize(a);H._panel_show=H.show;H._panel_hide=H.hide;H.show=n;H.hide=l}function n(){var a=b.from;a&&a.pull&&!a.get("visible")?setTimeout(n,100):(I&&I.set("visible",!0),r.set("visible",!0),H._panel_show())}function l(){H._panel_hide();r.set("visible",!1);I&&I.set("visible",!1)}var k=a.image||a.html||a.flash,q=a.options,u=a.panel,y=q.iab?d.parent:d,E=y.document,B=O[q.bn+"#"+q.seqNo],C=!!b.from,D="sticky"in u&&!1!==u.sticky,m=b.container,p=b.before,r,I,H,R="z"in
u?u.z:D||C?1E4:null,h=k.width,J=k.height;q.hidden?u.hidden=q.hidden:u.hidden&&(q.hidden=u.hidden);D&&!C?(m=p=null,(I=B.box=new A).publish("panel-box",a.events).set({width:h,height:J,visible:!u.hidden,x:u.x||0,y:u.y||0}).pull("element",e).draw(E,{position:f(u.position,c),before:b.before,container:b.container})):e()}function t(a,b){var c=this.item,d=c.box,c=c.stickyBox,a=M[a]||a;if("string"!==typeof a)for(b in a)t.call(this,b,a[b]);else"zIndex"==a?((c||d).set(a,b),this.constructor.setZIndex(b)):c&&
"stickyOffset"==a?c.set(a,b):d.set(a,b);c&&c.repositionSticky()}function s(a){var b=this.item,c=b.box,a=M[a]||a;if("width"==a||"height"==a)a=this.content[a];else{if("zIndex"==a||"stickyOffset"==a)c=b.stickyBox||c;a=c.get(a)}return a}function b(a,b){var c=b.options,d=b.panel,e={options:{iab:c.iab},events:b.events};u.applyHooks(e,["#"+a,c.bn+"#"+a]);e.panel&&(d?o.extend(d,e.panel):b.panel=e.panel)}function f(a,b){var a=(a||"").toLowerCase(),c,d={r:"E",ri:"R",l:"K",li:"L"}[(c=a.match(/[rl]i?/))&&c[0]]||
"C",e={t:"Y",ti:"T",b:"N",bi:"B"}[(c=a.match(/[tb]i?/))&&c[0]]||"M";return b?{E:"R",K:"L"}[d]||d:d+e}function e(){}if(!a._panels){a._panels=!0;var g=a.RMB,o=g.lib,u=g.DataParser,A=g.AdBox,y=[],n,O={},K={},M={z:"zIndex",sticky:"stickyOffset"};(_adform=d._adform||[]).push(["on.setup",function(f){var g=a.ADFUtilInstance,n=f.options,l=n.bn;if(g&&g.getPropByBn){var k=f.panel,q=f.events,s=n.seqNo,u=1==s,t;t=K[l];if(!t)for(var y=o.byTag("script"),A=y.length,E,B;0<A--;)if(E=y[A],(B=E.getAttribute("data-panels"))&&
E.src&&~E.src.indexOf("?bn="+l)){var y=c(B,";","="),A={length:0},C=B=E=void 0,D={w:"width",h:"height",pos:"position",p:"position",f:"from",s:"sticky"},m=void 0;for(m in y)if(m){E=y[m]?c(y[m],",",":"):{};B={};for(var p in E)p&&(C=D[p]||p,B[C]="hidden"==C||null===E[p]||E[p]);A["#"+m]=B;A.length++}B=A;B.length&&(t=K[l]=B);break}if(t&&(u&&!g.getPropByBn("syncMembersCount",l)&&g.addBannerAttribute(n.xId,"syncMembersCount",t.length),t=t["#"+s]))k=f.panel=o.extend(k||{},t);k&&(n.iab&&(d.frameElement.style.display=
"none"),O[l+"#"+s]={settings:f},u&&(k.id=k.id||"top"),k.id&&(q.clear("setup"),b(k.id,f),q.emit("setup",f)),f.preventInitialization=!0,i(f));if(u&&g.getPropByBn("singleTag",l)){g=a.ADFUtilInstance;f=f.options;n=g.getPropByBn("syncMembersCount",f.bn);l={options:{iab:f.iab,bn:f.bn},events:{on:e}};for(k=1;k++<(n||10);){if(!n){b(k,l);if(!l.panel)break;delete l.panel}g.copyBanner(f.xId,{compoundSeqNo:k,compoundImpr:0})}}}}])}})(Adform=window.Adform||{},window,document);
(function(a){function d(a,d,k){this._dur=k;this._int=d||25;this._fn=a;this._pos=0;var q=this;this.frame=function(a){q._frame(a)}}a.RMB=a.RMB||{};a.RMB.Tween=d;a=d.prototype;a.duration=function(a){this._dur=a;return this};a.forward=function(a){this.start(a)};a.backward=function(a){this.start(a,!0)};a.frame=function(a){a=!0===a?0:this._dur?(new Date-this._time)/this._dur:1;1<=a&&(a=1,this.stop());this._fn(this._back?1-a:a,this._back);this._pos=a};a._frame=a.frame;a.start=function(a,d){this.stop();"undefined"!=
typeof a?this._pos=a:a=this._pos;this._back!=d&&(a=1-a);this._back=!!d;this._time=new Date-this._dur*a;this._timer=setInterval(this.frame,this._int);this.frame(!a)};a.stop=function(){clearInterval(this._timer)}})(Adform=window.Adform||{});
(function(a,d,c){function i(b){if(!y)if(y=a.ADFEventsInstance){if(!y.getItem)return y=null;y.on("destroy",s);y.subscribe(t);t()}else b&&!A&&(A=1,o=a.scriptBase+o+a.cache,e.loadScript(c,o.split("{version}").join(g)));return y}function k(a){var b=i();return b&&b.getItem(a)}function q(a){if(this instanceof q)throw Error('This function cannot be used with operator "new".');return u[a]||(u[a]=new b(a))}function l(a){a&&(g=a)}function t(){for(var a in u)u[a].refresh()}function s(){for(var a in u)u[a].emit("destroy")}
function b(a){this.xId=a;this._queue=[];this._attributes={};this.set("visible",!1);this.set("loaded",!1);this.set("percent",0);this.set("clicksCount",0);this.refresh();this._changes=null;if(!i())this.once("newListener",f)}function f(){i(!0)}a.RMB=a.RMB||{};d=a.RMB;if(!d.EngagementAPI){d.EngagementAPI=q;var e=d.lib,d=d.EventEmitter,g="v13",o="unload/EngagementTracker.{version}.js?",u={},A,y,n;i()||(n=a._etCallback,a._etCallback=function(){i();(a._etCallback=n)&&n()});q.version=l;q.load=function(a){l(a);
i(true)};e.inherit(b,d);d=b.prototype;d.set=function(a,b){var c=k(this.xId),d=this.get(a),e=this._changes;if(c)c.attr(a,b);else{this._attributes[a]=b;this._queue.push([a,b])}if(d!==b){if(!e)e=this._changes={};e[a]=b;this.emit("change:"+a,b,d)}return this};d.get=function(a){if(this["get_"+a])return this["get_"+a]();var b=k(this.xId);return b?b.attr(a):this._attributes[a]};d.get_visibleTime=function(){var a=k(this.xId);return a&&a.visibility.time};d.refresh=function(){var a;a=k(this.xId);var b=0,c=
this._queue,d=c.length;if(a){if(d){for(;b<d;b++)a.attr(c[b][0],c[b][1]);c.length=0}this.set("visible",a.visibility.active);this.set("percent",a.data.currentVisibleArea);this.set("clicksCount",a.clicks.length);if(a=this._changes){this._changes=null;this.emit("change",a)}}return this}}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function i(c){var e=this.options=c.options;this.settings=c;e.BANNER_TYPE=this.BANNER_TYPE;var g=d;e.iab?(g=parent,e.iframe=d.frameElement):e.iframeManager?(g=parent.parent,e.iframe=q(g,parent)):e.window&&(g=e.window);this.win=g;n.isolate(g,s);a.adRegister=g.Adform.adRegister;t.call(this);(this._wallpaper=e.wallpaper&&e.wallpaper.background&&!n.isTMX(g))&&this.setupWallpaper();var i=c.events;this.on=function(){i.on.apply(i,arguments);return this};this.off=function(){i.off.apply(i,
arguments);return this};this.once=function(){i.once.apply(i,arguments);return this};this.emit=function(){var a=this._events;this._events=i._events;i.emit.apply(this,arguments);this._events=a;return this};this._clearEvents=function(a){i.clear(a)};n.isolate(g,b);d.ADFReload=g.ADFReload;d.ADFcall=d.ADFCall=g.ADFCall;c=n.bind(this,l);n.addEvent(d,"unload",c);if(g!=d&&(n.isolate(g,f),n.isOpera||9>n.ieVersion))(!g.Adform||!g.Adform.trackIframe)&&n.isolate(g,k),g.Adform.trackIframe(e.iframe,c)}function k(a){function b(){for(var a=
d.length;a--;)d[a][0].parentNode||(d[a][1](),d.splice(a,1));d.length||(c=clearInterval(c))}var c,d=[];(a.Adform=a.Adform||{}).trackIframe=function(a,e){d.push([a,e]);c||(c=setInterval(b,200))}}function q(a,b){for(var c=a.document.getElementsByTagName("iframe"),d=c.length;0<d--;)try{if(c[d].contentWindow==b)return c[d]}catch(m){}}function l(){var a=this.options.xId,b=this.getUtils();n.removeEvent(d,"unload",arguments.callee);this.emit("destroy");this.destroy&&this.destroy();O.destroy();t.call(this,
!0);this._clearEvents();this._wallpaper&&(this.toggleWallpaper(),delete this._wallpaper);b&&b.wipeOutBanner&&b.wipeOutBanner(a);this.options=null}function t(b){var c=this.options,d=c.bn,e=c.xId,c=c.seqNo,c=d+(c?"#"+c:""),m=a.adRegister,f=this.win.Adform.adRegister;b?(delete m[c],delete m[d],delete m[e],delete f[c],delete f[d],delete f[e]):m[c]=m[d]=m[e]=f[c]=f[d]=f[e]=this}function s(a){a=a.Adform=a.Adform||{};a.adRegister=a.adRegister||{}}function b(a){function b(c,d){var e=[].slice,f=a.Adform.adRegister;
if(f[c]){var g=[f[c]];if(!/x|#/.test(c))for(var i in f)g[0]!=f[i]&&!i.indexOf(c)&&g.push(f[i]);f=arguments;f=2<f.length?e.call(f,2):!1;for(e=0;e<g.length;e++){i=g[e];var n="string"==typeof d?i[d]:d;"function"==typeof n&&(f?n.apply(i,f):n.call(i))}}}a.ADFReload=function(a){setTimeout(function(){b(a||"1x","reload")},0)};a.ADFcall=a.ADFCall=b}function f(a){var b=a.Adform;b.Events=b.Events||{sendEvent:function(b,c,d,e,f){a.ADFCall(b,"sendEvent",c,d,e,f)}}}function e(a){return(new A.Type[z[a.options.type]](a)).emit("init",
a)}function g(b){var d=b;b||(b=F.shift());var f=b.options,g=f.type,m=z[g],p=A.Type[m],r=a.Log,i=f.bn;if(p&&!b._beforeScript){if(r&&(g===K.SLIDER&&(g=K.EXPANDING),r.pushMessage(["BannerType_"+g],"",{bn:i}),g===K.EXPANDING||g===K.SINGLE_EXPANDING))r.pushMessage(["ExpandingBehavior_"+f.behavior],"",{bn:i}),d=g.charAt(0).toUpperCase()+g.slice(1)+"_",f.showTime&&r.pushMessage([d+"expandTime"],"",{bn:i}),f.hideTime&&r.pushMessage([d+"collapseTime"],"",{bn:i});K.applyHooks(b);b.events.emit("setup",b);b.preventInitialization||
e(b)}else if(d)delete b._beforeScript,p&&(m="NextTick"),F.push(b),c.write('<script src="'+f.scriptsBase+"rmb/Adform."+m+".js?bv="+a.cache+'"><\/script>');else throw r&&r.pushMessage(["AdConstructor"],"Construct failed",{bn:i}),Error("Construct failed!");}function o(){var a=n.html('<iframe frameborder="0" allowtransparency="true" style="position:absolute;top:0;left:0;width:100%;height:100%"></iframe>'),b=c.body;n.isIE&&9>n.ieVersion?(b.appendChild(a),a=a.contentWindow,a.name=V,a.document.location.href=
N):(a.name=V,a.src=N,b.appendChild(a))}function u(a,b){if(this._hovered!=a){this._hovered=a;this.interacted=!0;if(a){var c=b.content().assetId;this._eventDelay(this,this.sendEvent,G,c,x)}else this._eventDelay();if(this.onEngage)this.onEngage()}}var A=a.RMB=a.RMB||{};A.Type=A.Type||{};if(!A.AdConstructor){A.AdConstructor=i;var y=A.EngagementAPI,n=A.lib,O=A.DOMEvents,K=A.DataParser,M=A.StyleSheet,F=[],G="141",x="Mouse Over on Banner",N,V,Y,S={Expanding:[K.EXPANDING,K.TEARBACK],Slider:[K.SLIDER],SingleExpanding:[K.SINGLE_EXPANDING],
Floating:[K.FLOATING],Standard:[K.STANDARD],Interstitial:[K.INTERSTITIAL]},z={},T,X,P;for(T in S)if((P=S[T]).push)for(X=P.length;0<X--;)z[P[X]]=T;i.build=function(){a.BWDetect&&a.BWDetect();var b=K.getData(),e=b&&b.options;if(e){var f=e.type,i;if(i=a.ADFIframe){if(f=f==K.EXPANDING||f==K.SINGLE_EXPANDING||f==K.SLIDER)a:{f=a.RMBData;i=b.options;if(!i.messenger){var m=b.options.xId,p=a.ADFBannerUtils;m&&p&&p.getInstance&&(p=p.getInstance().banners[m]);if(p&&d!=d.parent&&(m=!i.iab&&"stubFileURL"in p&&
decodeURIComponent(p.stubFileURL))){m+=(m.match(/\?/)?"&":"?")+"version="+d.ADFBanVer;p=c.referrer;if(!/^[a-z]{3,}\:\/\/\w+/i.test(m)&&p&&(p=p.match(/^https?\:\/\/[^\/]+\//i)))m=m.replace(/^\/*/,p[0]);(p=location.search.match(/\bADFstubFileURL=([^&]+)/))&&p[1]&&(m=m.replace(/\/\/[^\/]+\//,"//"+p[1]+"/"));f=n.extend({},f);delete f.__parsed;f.host=a.CDNHost||a.host;i.adNotice&&(f.adNotice=1);i.obaId&&(f.obaId=i.obaId);f.bclickUrl&&(f.bclickUrl=K.fixFlashvarsValue(f.bclickUrl));p=K.parseFlashvars(f.clicktags);
delete f.clicktags;var r=f.clickEvent,l=r;r&&"string"==typeof r&&r.match(/\S/)?l=encodeURIComponent(r):r=l=!1;for(var o in p)l&&"string"==typeof p[o]&&(p[o]=p[o].replace(r,"#base#").replace(l,"#base#")),f["ct_"+o]=p[o];if(p=f.videoSources){r=[];o=0;for(l=p.length;o<l;o++){r[o]=[];for(var k in p[o])r[o].push(k,p[o][k]);r[o]=r[o].join("|")}f.videoSources=r.join("|||")}if(p=f.userParams){r=[];for(k in p)r.push(encodeURIComponent(k)+"="+encodeURIComponent(p[k]));f.userParams=r.join("|||")}k=["format=expanding"];
f.rmbPath=i.scriptsBase+"rmb/Adform.RMB.js?bv="+a.cache;for(o in f)k.push(encodeURIComponent(o)+"="+encodeURIComponent(f[o]));N=m;V=k.join("&");Y=b.options.css.replace(/\/assets\/.*/,"/assets/");c.write('<script src="'+Y+'cached.js"><\/script>');f=!0;break a}}f=void 0}i=f}i||(y[e.sendUnload?"load":"version"](e.unloadVersion),b._beforeScript=a._beforeScript,delete a._beforeScript,g(b),e.errorTimeout&&clearTimeout(e.errorTimeout))}};i.ibuild=g;i.checkCache=function(){if("1e963d1013e5525f3107134e9e9d4df5"!=d.CACHE){var a=
'<iframe src="'+Y+"recache.html?"+(new Date).getTime()+'" frameborder="0" style="position: absolute; left: -9999px;"></iframe>',a=n.html(a),b=0,e=0,f=function(){if(2===(e||b))a.onload=null,a.onreadystatechange=null,c.body.removeChild(a),o()};a.onload=function(){b++;f()};a.onreadystatechange=function(){"complete"===a.readyState&&(e++,f())};c.body.appendChild(a)}else o()};i.initialize=e;S=i.prototype;S.BANNER_TYPE="";S.setupUtils=function(a,b){var c=this.getUtils(),d=this.options.xId;"string"==typeof a&&
(a=[a]);c&&(c.addBannerAttribute(d,"relativeTargetSWFID",a[0]),c.addBannerAttribute(d,"trackElements",a),b&&c.addBannerAttribute(d,"trackHeatMap",b))};S.setupEngagement=function(a){var b=this,c=n.singleCall(0);b._eventDelay=n.singleCall(1E3);b._hovered=!1;a.length||(a=[a]);for(var d=0;d<a.length;d++)a[d].on("hover",function(a,d){c(b,u,a,d)})};S.sendEvent=function(b,c,d,e){return a.Events&&a.Events.sendEvent?(a.Events.sendEvent(this.options.xId,b,c,d,e||"",this.BANNER_TYPE),!0):!1};S.getUtils=function(){var b=
a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()};S.setupWallpaper=function(){var a=this.options,b=a.wallpaper,c=this.win.document,d=b.cssClass="adform-wallpaper-"+a.bn,e=b.element||"",e="html"==e?"":!e.indexOf("#")?" "+e:c.documentElement?" body":"";b.target=a.landingPageTarget;M("adform-wallpaper",c).set("."+d+e,"background: "+b.background);("undefined"==typeof b.autoShow||b.autoShow)&&this.toggleWallpaper(!0)};S.toggleWallpaper=function(a){function b(a){a=a||e.event;a=a.target||a.srcElement;
return o&&a.id==o?!0:/^(html|body)$/i.test(a.nodeName)}function c(a){i.style.cursor=b(a)?"pointer":""}if(this._wallpaper){var a="string"==typeof a?"true"==""+a:a,d=this.options,e=this.win;try{var f=e.document,g,i=f.documentElement||f.body;if((g=e.__adform_wallpaper)&&(a||g.cssClass==d.wallpaper.cssClass))n.removeClass(i,g.cssClass),g.link&&(n.removeEvent(f,"mousemove",g._move),n.removeEvent(f,"mouseover",g._cursor),n.removeEvent(f,"click",g._click)),i.style.cursor="",e.__adform_wallpaper=null;if((g=
d.wallpaper)&&a){n.addClass(i,g.cssClass);if(g.link){var o=g.element,o=o&&!o.indexOf("#")?o.slice(1):"";n.addEvent(f,"mousemove",g._move=function(a){n.removeEvent(f,"mousemove",arguments.callee);c(a)});n.addEvent(f,"mouseover",g._cursor=c);n.addEvent(f,"click",g._click=function(a){b(a)&&e.open(g.link,g.target)})}e.__adform_wallpaper=g}}catch(l){}}};S.setupGateway=function(b,c){if(b.get("element")){if(a.Wallpaper&&a.Wallpaper.setup&&!b.get("frompos")){var d=b.get("element"),e=(e=this.getUtils())&&
e.banners&&e.banners[this.options.xId];a.Wallpaper.setup({bn:this.options.bn,element:d,utils:e,width:b.get("width"),height:b.get("height"),callback:c})}}else{var f=this;b.onchange("element",function(){b.off("change:element",arguments.callee);f.setupGateway(b,c)})}};S.adDestroy=l;S.reload=function(){this.adBox&&this.adBox.emit("content:reload")};S.setZIndex=function(a){a=parseInt(a,10);if(!isNaN(a)){var b=this.options,c=z[b.type],d="adBox,collapsed,expanded,wallpaper,container,overlay".split(","),
e,f,g,i=d.length;for(this.zIndex=a;i--;)if((f=d[i])&&(e=this[f]))g=a,!("container"==f&&"floating"!=b.behavior)&&!("collapsed"==f&&"SingleExpanding"==c)&&("expanded"==f&&"Expanding"==c&&(g+=1),"overlay"==f&&(g-=1),e.set("zIndex",g))}}}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(b,f){function e(){g.emit(l)}var g=this;c.super_.call(g);g.created=0;g.options=b;g.data=f;g.container=t.bind(g,g.container);g.show=t.bind(g,g.show);g.hide=t.bind(g,g.hide);g.clear=t.bind(g,g.clear);g.reload=t.bind(g,g.reload);var i=b.loadDelay;if(i)setTimeout(e,1E3*i);else t.onload(d,e);g.on(q,function(){s(b.xId).set(q,!0)});f.social&&(g.setupExtra(g.social=new k.Socialize(b,f.social)),a.Log&&a.Log.pushMessage(["Socialize"],"",{bn:b.bn}));f.adNotice&&"window"!=f.wmode&&g.setupExtra(g.adNotice=
new k.AdNotice(b,f))}a.RMB=a.RMB||{};var i=a.RMB,k=i.Content=a.Content||{};i.AdContent=c;var q="loaded",l="pageLoadComplete";a.PAGE_LOAD_COMPLETE=l;var t=i.lib,s=i.EngagementAPI;t.inherit(c,i.EventEmitter);i=c.prototype;i.container=function(a){var c=this.doc=a.ownerDocument;this.win=c.defaultView||c.parentWindow;this._element=a};i.show=function(){};i.hide=function(){};i.reload=function(){var a=this instanceof k.AdNotice;!(this instanceof k.Socialize)&&!a&&(this.destroy(),this._adbox.get("showing")&&
this.show())};i.destroy=function(){};i.element=function(a,c){var d=this._elem;!1!==c?(d||(d=t.html('<div style="position:relative;width:100%;height:100%;overflow:hidden">',c&&c.ownerDocument)),d&&(c&&c.appendChild(d),"string"==typeof a&&(d.innerHTML=a))):d&&(d.parentNode&&d.parentNode.removeChild(d),d=null);return this._elem=d};i.bind=function(b){if(!this._adbox){var c=this.options,d,g;this._adbox=b;b.once("content:show",function(b){d=setTimeout(function(){for(var d=["img","object","embed","iframe"],
e,g;e=d.pop();){if((e=t.byTag(b,e)[0])&&0<e.offsetWidth&&0<e.offsetHeight)return;e&&(g=e)}a.Log.pushMessage(["AdContent"],"Banner did not render correctly",{bn:c.bn,node:g&&g.nodeName})},3E3)});b.once("content:hide",function(){clearTimeout(d)});b.once("content:destroy",function(){clearTimeout(d)});b.on("change:element",this.container);b.on("content:show",this.show);b.on("content:hide",this.hide);b.on("content:destroy",this.clear);b.on("content:reload",this.reload);(g=b.get("element"))&&this.container(g);
b.get("showing")&&this.show()}};i._clear=i.clear;i.clear=function(){var a=this._adbox;a&&(a.off("change:element",this.container),a.off("content:show",this.show),a.off("content:hide",this.hide),a.off("content:destroy",this.clear),a.off("content:reload",this.reload),this.destroy(),this._clear(),this._adbox=this.doc=this.win=this._element=null)};i.style=function(a){var c=this.element();c&&t.extend(c.style,a);return this};i.setupExtra=function(a){var c=this.bind,d=this.clear;this.bind=function(d){var e=
c.call(this,d);a.bind(d);return e};this.clear=function(){a.clear(this._adbox);return d.call(this)}}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(a,b){c.super_.call(this,a,b.adNotice);var d=this.data;d.width=b.width;d.height=b.height;this.id=k.gid(t+"button-");this.base=a.scriptsBase+"assets/images/OBA/"}a.RMB=a.RMB||{};var i=a.RMB;i.Content.AdNotice=c;var k=i.lib,q=i.DOMEvents,l=i.StyleSheet,t="adform-adnotice-",s={};k.inherit(c,i.AdContent);i=c.prototype;c.supported=function(){return!0};c.READY="ready";i.show=function(){this._element&&!this.created&&this.write()};i.write=function(){var a=this;a.created=(new Date).getTime();
var b=a._element,c=a.doc,i=a.win;i.self||(i=a.win=d);var s=a.statics=l("adbox-static",c);s.adNoticeStyles||(s.adNoticeStyles=!0,s.set(".adform-adnotice","z-index:1;position:absolute!important;top:0!important;right:0!important;left:auto!important;padding:0!important;margin:0!important"));a._elem=k.html('<div class="adform-adnotice" id="'+a.id+'">',c);var t=a.options,y=t.obaId;y?i.$ADP?a.setupAdPlayer(y,b):(s=t.scriptsBase+"adplayer/js/adplayer.min.js",k.loadCSS(c,t.scriptsBase+"adplayer/css/adplayer.min.css"),
k.loadScript(c,s,function(c){c||!i.$ADP?a.setupDefault(b):a.setupAdPlayer(y,b)})):a.setupDefault(b);q.on(a._elem,"hover",function(a){t.disturber.emit("hover",a=="hoverin")})};i.destroy=function(){this.element("",!1);this.created=0};i.getOBAImage=function(a){a=a.toLowerCase().match(/^(bg|cs|da|de-at|de-ch|de|el|es|fi|fr-be|fr-ch|fr|ga|hu|it-ch|it|nl-be|nl|no|pl|ro|sk|sv|uk|en)/);a=(a&&a[0]||"en")+".png";return this.base+a};i.getOBASuffix=function(a){var a=a.toLowerCase(),b=a.match(/(de-at|fr-be|nl-be|bg|cs|da|fi|fr-ch|fr|et|de-ch|de|hu|ga|it-ch|it|lv|lt|lb|mt|nl|no|pl|pt|ro|sk|sl|es|sv|en-gb)$/),
a={"de-at":"at","nl-be":"be-nl","fr-be":"be-fr",cs:"cz",da:"den",et:"ee",ga:"ie",lb:"lu",mt:"ma",no:"nor",sv:"se","fr-ch":"ch-fr","de-ch":"ch-de","it-ch":"ch-it","en-gb":"uk"}[a]||b&&b[0]||"";return a.length?a+"/":a};i.setupAdPlayer=function(a,b){var c=this.win,d=c.$ADP.Registry,i=this.id,l=this.data,k=this.options;this.element("",b);if(!s[a]){var n=[{title:l.title,text:l.text,url:l.link,linkText:l.linkText,usePopup:!!(c.Adform&&c.Adform.ADFIframe||k.iframeManager||k.iab)}];c.ADFCall(k.xId,function(){this.emit("setupADP",
n)});if(n){c=0;for(l=n.length;c<l;++c)d.register(a,n[c])}s[a]=!0}d.createPlayer(a,{domId:i});this.emit("ready")};i.setupDefault=function(a){var c=this.data,d=this.id,i=this.statics,l=105<=c.width&&0.1>1575/(c.width*c.height);i.set(".adform-adnotice a","display:block;width:19px;height:15px;margin:0!important;padding:0!important;position:static!important;background:url("+this.base+"oba.png) no-repeat;").set(".adform-adnotice img","display:none;border:none;margin:0!important;padding:0!important;position:static!important");
l&&i.set("#"+d+" a:hover","width:auto;position:absolute;top:0;right:0;background-position:0 -100px").set("#"+d+" a:hover img","display:block;");this.element('<a href="'+c.link+this.getOBASuffix(b)+'" target="_blank">'+(l?'<img src="'+this.getOBAImage(b)+'" alt="">':"")+"</a>",a);this.emit("ready")};var b=navigator.userLanguage||navigator.language||""})(Adform=window.Adform||{},window,document);
(function(a,d){function c(a,d){c.super_.call(this,a,d);this.id=l.gid(s+"button-");this.on(b,function(){this.sendEvent(145,"Hide Social Bar")}).on(f,function(){this.sendEvent(140,"Facebook Like Button Press")})}function i(){this.emit(f);d.open(this.data.linkBack);return!1}function k(){this.emit(b);this.destroy()}a.RMB=a.RMB||{};var q=a.RMB;q.Content.Socialize=c;var l=q.lib,t=l.addEvent,s="adform-social-",b="collapsed",f="liked";l.inherit(c,q.AdContent);q=c.prototype;c.supported=function(){return!0};
c.READY="ready";c.COLLAPSED=b;c.LIKED=f;q.show=function(){this.destroyed||(this.created&&this.style({display:""}),this._element&&!this.created&&this.write())};q.hide=function(){this.style({display:"none"})};q.write=function(){this.created=(new Date).getTime();var a=this._element,b=this.doc,c=this.data,d=this.id;this._elem=l.html('<div id="'+d+'" class="'+[s+"container",s+"container-"+c.position].join(" ")+'" style="display:none;">',b);this.element('<div class="'+s+'bg"></div><div id="'+d+'-bar" class="'+
s+'bar"></div>',a);a=l.byId(d+"-bar",b);d=this.closeButton=l.html('<div class="'+s+'close">',b);this.close=l.bind(this,k);t(d,"click",this.close);var f=this.linkButton=l.html('<div class="'+s+'link">Like us on Facebook.</div>',b);this.like=l.bind(this,i);t(f,"click",this.like);a.appendChild(f);a.appendChild(d);l.loadCSS(b,c.css);123>c.width&&this.style({width:c.width-("TLV"==c.position?30:2)+"px",overflow:"hidden"});this.emit("ready")};q.destroy=function(){this.closeButton&&l.removeEvent(this.closeButton,
"click",this.close);this.linkButton&&l.removeEvent(this.linkButton,"click",this.like);this.bar=this.linkButton=this.like=this.closeButton=this.close=null;this.element("",!1);this.created=0;this.destroyed=!0};q.sendEvent=function(b,c){if(a.Events&&a.Events.sendEvent){var d=this.options;a.Events.sendEvent(d.xId,b,0,c,"",d.BANNER_TYPE);return!0}return!1}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(b,d){c.super_.call(this,b,d);q.call(this);this.cube3D=this.video=!1;this.created=0;this.keepAlive=b.keepAlive;this.restartAnim=b.restartAnimation;var e=a.Log,f=b.bn;e&&(this.restartAnim&&e.pushMessage(["RestartAnimation"],"",{bn:f}),e.pushMessage(["AssetType_flash"],"",{bn:f}));e=o.gid("Adform");f=this.flashvars=d.flashvars;d=o.extend({},d);f.adId=e;f.expandTime=b.showTime||0;f.collapseTime=b.hideTime||0;f.behavior=b.behavior;f.landingPageTarget=b.landingPageTarget;var g=
[],l;for(l in f)f.hasOwnProperty(l)&&g.push(l+"="+f[l]);var h=b.userParams;if(h)for(l in h)if(h.hasOwnProperty(l)){var n=encodeURIComponent(l);n in f||g.push(n+"="+encodeURIComponent(h[l]+""))}d.flashvars=g.join("&");d.id=this.id="ad"+e;this.data=d;this.assetId=d.assetId||0;this._inScreenLast=0;this.on(T,i)}function i(){var a=u(this.options.xId);if(!this._lastInScreen)a.on("change",o.bind(this,k));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};k.call(this,a)}function k(a){var b=
this,c=+new Date,d=b._inScreenTimer,e=b._lastInScreenChanges;e&&(a=o.extend(e,a));d&&(clearTimeout(d),b._inScreenTimer=0);b._lastInScreen>c-500?(b._lastInScreenChanges=a,b._inScreenTimer=setTimeout(function(){k.call(b,a)},b._lastInScreen+500-c)):(b._lastInScreen=c,b._lastInScreenChanges=null,b.callSwfMethod(X,a))}function q(){var a=!1,b=!1,c=this,d;c.on(M,function(){var e=+new Date;b=!0;a&&((!d||500<e-d)&&c.callSwfMethod(y),d=e)});c.on(y,function(){c.off(y,arguments.callee);a=!0;b&&c.callSwfMethod(y)})}
function l(b,c){function e(a,c,d,h,f){b.emit(a,{x:parseInt(c,10)+i.x,y:parseInt(d,10)+i.y,width:parseInt(h,10),height:parseInt(f,10)})}function f(a){b.emit(a);d.IABcloseAD&&d.IABcloseAD()}for(var g=b.win,i={x:0,y:0},h=b.emit,h=[["initPoliteMode",h,M],["initVideoMode",function(c){b.video=!0;a.Log&&a.Log.pushMessage(["VideoType_"+("undefined"===typeof c||c?"flash":"html")],"",{bn:b.options.bn})}],["initCube3D","cube3D",!0],["initExtender",h,P],["initInScreen",h,T],["startDrag",h,E],["endDrag",e,B],
["updateBox",e,Y],["expandComplete",h,S],["collapseComplete",h,z],["close",f,F],["superClose",f,x],["expand",h,G],["rollOutAd",h,N],["videoPlayStartHandler",h,"video:start"],["videoCompleteHandler",h,"video:end"]],l=h.length;0<l--;)(function(a,d,e){function h(){var a=C.call(arguments);"undefined"!==typeof e&&a.unshift(e);d.apply(b,a)}function f(){b[d]=e}c[a]="function"==typeof d?h:f}).apply(b,h[l]);c.initScroll=function(){var a=b.options.iab?g.parent:g;o.addEvent(a,"scroll",function(){o.removeEvent(a,
"scroll",arguments.callee);b.callSwfMethod("scroll")})};c.initSingleExpanding=function(a,c){b.emit("expandSettings",i={x:-parseInt(a,10),y:-parseInt(c,10)})};c.toggleFullScreen=function(a){b.emit(V,"true"==""+a)}}function t(a){var b=a.id,c,d,e="Handlers"+a.options.xId;d=a.win;o.isolate(d,s);c=d.Adform.swfCallbacks;d=d.Adform.VideoInterstitialHandlers;d=d[e]=c[b]=c[b]||{};l(a,d)}function s(a){function b(a,d){if(a&&(a=c["ad"+a])&&a[d])a[d]()}var c="swfCallbacks",d="VideoInterstitialHandlers",e=a.Adform=
a.Adform||{};if(!e[c]||!e[d])c=e[c]=e[c]||{},d=e[d]=e[d]||{},a.ADFClose=function(a){b(a,"close")},a.ADFSuperClose=function(a){b(a,"superClose")},a.ADFExpand=function(a){b(a,"expand")}}function b(a){var b=['classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"','codebase="'+location.protocol+"//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version="+a.version+',0,0,0"'],c=[],d=['type="'+A+'"','pluginspage="'+location.protocol+'//www.macromedia.com/go/getflashplayer"'],e;for(e in a)a.hasOwnProperty(e)&&
!~"object|undefined".indexOf(typeof a[e])&&("id"==e||"width"==e||"height"==e?b.push(e+'="'+a[e]+'"'):"src"==e?c.push('<param name="movie" value="'+a[e]+'" />'):c.push('<param name="'+e+'" value="'+a[e]+'" />'),"id"==e?d.push('name="'+a[e]+'"'):d.push(e+'="'+a[e]+'"'));return"<object "+b.join(" ")+">"+c.join("")+"<embed "+d.join(" ")+" /></object>"}function f(a,b){var c=o.byId(a,b);c&&"OBJECT"==c.nodeName&&("msie"==o.browser()?(c.style.display="none",function(){if(4==c.readyState){var d=o.byId(a,b);
if(d){try{for(var e in d)if("function"==typeof d[e])try{d[e]=null}catch(f){}}catch(h){}d.parentNode.removeChild(d)}}else setTimeout(arguments.callee,10)}()):c.parentNode.removeChild(c))}function e(a,b){var c=o.byId(a,b);return c&&o.byTag(c,"embed")[0]}a.RMB=a.RMB||{};var g=a.RMB;g.Content.FlashTag=c;var o=g.lib,u=g.EngagementAPI,A="application/x-shockwave-flash",y="pageLoadComplete",n="loaded",O="percentLoaded",K="canceled",M="politeReady",F="hide",G="show",x="close",N="rollOut",V="fullScreen",Y=
"updateBox",S="expandComplete",z="collapseComplete",T="initInScreen",X="updateInScreen",P="extender",E="startDrag",B="endDrag";o.inherit(c,g.AdContent);g=c.prototype;c.supported=function(a){return D>=(a||1)};c.observe=function(a){var b=c._timer,d=c._toObserve=c._toObserve||[];d.push(a);b||(b=setInterval(function(){for(var a=d.length;a--;)d[a]()&&d.splice(a,1);d.length||(clearInterval(b),delete c._timer)},500),c._timer=b)};c.READY="ready";c.PERCENT=O;c.LOADED=n;c.CANCELED=K;c.POLITE_READY=M;c.HIDE=
F;c.CLOSE=x;c.SHOW=G;c.ROLL_OUT=N;c.EXPAND_SETTINGS="expandSettings";c.EXPAND_UPDATE=Y;c.EXPAND_END=S;c.COLLAPSE_END=z;c.FULL_SCREEN=V;c.LOAD_COMPLETE=y;c.INSCREEN_INIT=T;c.INSCREEN_UPDATE=X;c.EXTENDER=P;c.START_DRAG=E;c.END_DRAG=B;c.setCallbacks=l;c.setupPolite=q;g.write=function(){var a=this,d=a._element,e=b(a.data);t(a);a.element(e,d);a.created=new Date;a.emit("ready");setTimeout(function(){function b(){var c=o.byId(a.id,a.doc),d=c&&o.byTag(c,"embed")[0];try{return c.PercentLoaded(),c}catch(e){try{return d.PercentLoaded(),
d}catch(h){}}}function d(){try{var b=e.PercentLoaded();a.emit(O,b);100==b&&(a.emit(n),h=clearInterval(h))}catch(c){a.emit(K),h=clearInterval(h)}}var e,h;(e=b())?h||(h=setInterval(d,100)):c.observe(function(){var c;if(!(c=!a.created))if(c=e=b())h||(h=setInterval(d,100)),c=!0;return c})},100)};g.destroy=function(){this.video&&this.callSwfMethod("pauseVideo");var a=this.id,b=this.win;(b=b&&b.Adform||d.Adform)&&b.swfCallbacks&&b.swfCallbacks[a]&&delete b.swfCallbacks[a];f(this.id,this.doc);this.element("");
this.created=0};g.callSwfMethod=function(a){function b(){if(!l[a]&&(!n||!n[a]))0<k--?setTimeout(b,100):c.emit("failed:"+a,j);else{try{"undefined"!=typeof l[a]?e.Adform_swfCallFix?e.Adform_swfCallFix(g,a,j):l[a].apply(l,j):"undefined"!=typeof n[a]&&n[a].apply(n,j)}catch(d){}c.emit("called:"+a,j)}}var c=this;if(c.created){var e=c.win,f=c.doc,g=c.id,h=c._elem;if(e!=d&&!f.addEventListener){var i=f.createElement("script");i.text="function Adform_swfCallFix(a,b,c){a=document.getElementById(a);return a[b].apply(a,c);}";
h.parentNode.insertBefore(i,h)}var l=o.byId(g,f),n=o.byTag(l,"embed")[0],j=C.call(arguments,1),k=20;c.emit("call:"+a,j);200>new Date-c.created?setTimeout(b,"safari"==o.browser()?100:0):b()}};g.show=function(){this._element&&!this.created&&(this.write(),this.forceRender())};g.hide=function(){if(this._element&&this.created){var a=e(this.id,this.doc);a&&a.blur&&a.blur();this.video&&!this.restartAnim?(this.callSwfMethod("pauseVideo"),this.cube3D&&this.callSwfMethod("resetCube3D"),this.forceRender()):
this.keepAlive?this.forceRender():this.destroy()}};g.forceRender=function(){if(!d.opera){var a=e(this.id,this.doc);if(a){var b=this.data.width;setTimeout(function(){a.width=b+1},0);setTimeout(function(){a.width=b},0)}}};var C=Array.prototype.slice,D=function(){var a=navigator.plugins,b=navigator.mimeTypes,c=d.ActiveXObject,e=16,f,a=a&&a["Shockwave Flash"]&&(!b||!b["application/x-shockwave-flash"]||b["application/x-shockwave-flash"].enabledPlugin)&&a["Shockwave Flash"].description||"";if(!a&&c)for(;6<=
e--;)try{f=new c("ShockwaveFlash.ShockwaveFlash."+e);6==e&&(f.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=f.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(h){}return parseFloat(a.replace(/^.*?(\d+[\.,].*$)/,"$1"))||0}()})(Adform=window.Adform||{},window,document);
(function(a,d,c){function i(c,d){i.super_.call(this,c,d);this.assetId=d.assetId||0;this.xId=c.xId;this.restartAnim=c.restartAnimation;var e=a.Log,f=c.bn;e&&(e.pushMessage(["VideoType_html"],"",{bn:f}),e.pushMessage(["AssetType_video"],"",{bn:f}),this.restartAnim&&a.Log.pushMessage(["RestartAnimation"],"",{bn:f}));e=b.gid("Adform");d.id=this.id="ad"+e}function k(a){function c(){var a=k.currentTime,b=k.duration,e=+new Date,f=e-t,g=a-u;t=e;u=a;if(b){e=!1;if(g&&(g=f/(1E3*g)))e=2<Math.round(Math.abs(k.playbackRate/
g));a/=b;p!=a?(p=a,m=5,i.emit("timeupdate",p,e)):"playing"==o&&!--m&&0.9<p&&(d({type:"ended"}),m=5)}}function d(b){if("ended"==b.type&&a.loop)g(0),k.play();else if("ended"==b.type&&(g(0),k.pause()),b=k.paused||"ended"==b.type?!p||1===p?"stoped":"paused":"playing",b!=o)i.playbackState=o=b,i.emit("state",b)}function f(a){var b=a.total||k.duration;if(0<b)try{var c=(a.loaded||k.buffered&&k.buffered.end(0)||0)/b;c>r&&(r=c,i.emit("loadProgress",r))}catch(d){}}function g(a){try{k.currentTime=a*k.duration}catch(b){}}
var i=this,l=a.document;"undefined"==typeof N&&(N=l.createElement("video"));var n=s(a.sources);i.source=n;var k=b.html("<video "+q(a)+' preload="none" style="float:left"><source src="'+n.src+'"></video>',l);k.loop=!1;i.element=k;var o,m,p=-1,r=-1,t=0,u=0;e(k,"timeupdate",c);setInterval(function(){c()},500);l="play,pause,playing,seeking,seeked,stalled,ended,timeupdate".split(",");for(n=0;n<l.length;n++)e(k,l[n],d);d({});if(k.buffered)var y=setInterval(function(){f({});1<=r&&clearInterval(y)},500);
else e(k,"progress",f);i.setProgress=g;a.autoplay&&k.play()}function q(a){for(var b=[],c=0,d,e;c<V.length;c++)d=V[c],(e=a[d])&&(!0===e?b.push(d):b.push(d+'="'+e+'"'));return b.join(" ")}function l(a){function c(a){a=(b.getMousePos(a).pageX-s.pageX+s.relativeX)/m.offsetWidth;d(a)}function d(a){a=0>a?0:1<a?1:a;n(a);k.emit("seek",a)}function i(){g(o,"mousemove",c);g(o,"mouseup",i);g(o,"mouseout",l);k.emit("endSeek")}function l(a){for(a=a.relatedTarget;a&&a!=k;)a=a.parentNode;a!=k&&i()}function n(a){r.style.width=
100*a+"%"}var k=this;f.call(k);var o=a.container,s=null,q=b.html('<div class="'+u+'seek"><div class="'+u+'seek-border"><div class="'+u+'seek-background"><div class="'+u+'seek-loaded"></div><div class="'+u+'seek-played"></div></div></div></div>',o.ownerDocument),m=q.firstChild.firstChild,p=m.firstChild,r=p.nextSibling;r.style.width=0;k.element=q;e(q,"mousedown",function(a){k.emit("startSeek");a.preventDefault?a.preventDefault():a.returnValue=!1;s=b.getMousePos(a);d(s.relativeX/q.offsetWidth);e(o,"mousemove",
c);e(o,"mouseup",i);e(o,"mouseout",l)});k.setProgress=n;k.setLoadProgress=function(a){p.style.width=100*a+"%"}}function t(a){var c=this;f.call(c);var d=a.className,a=c.element=b.html('<div class="'+d+'"></div>',a.document);e(a,"click",function(a){a.preventDefault?a.preventDefault():a.returnValue=!1;c.emit("buttonClick",d)})}function s(a){if(a&&a.length)for(var b=N,c=0;c<a.length;c++){var d=a[c];if(d){var e=d.file;if(e){var f=!1;if(d.mime&&d.codecs)d=d.mime+'; codecs="'+d.codecs+'"';else{f=e.match(/\.(mp4|webm|mkv|ogv|ogg|avi)/i);
if(!f)continue;f=f[1].toLowerCase();d={mp4:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',avi:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',mkv:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',webm:'video/webm; codecs="vp8, vorbis"',ogv:'video/ogg; codecs="theora, vorbis"',ogg:'video/ogg; codecs="theora, vorbis"'}[f]}if(d){var g;try{var i;if(!(i=b.canPlayType(d))){var l;if(l=f)l=M&&("mp4"==f||"m4v"==f)||K&&"m3u8"==f?"maybe":void 0;i=l}g=i}catch(k){}if("probably"==g||"maybe"==g)return{src:e,type:d}}}}}}a.RMB=
a.RMB||{};d=a.RMB;d.Content.VideoTag=i;var b=d.lib,f=d.EventEmitter,e=b.addEvent,g=b.removeEvent;b.inherit(i,d.AdContent);var d=i.prototype,o={progr0:{id:"25",name:"Video Play Start"},progr25:{id:"26",name:"Played 25% Of Video"},progr50:{id:"27",name:"Played 50% Of Video"},progr75:{id:"28",name:"Played 75% Of Video"},progr100:{id:"29",name:"Video Playback Complete"},play:{id:"30",name:"Play Button Press"},pause:{id:"31",name:"Pause Button Press"},stop:{id:"32",name:"Stop Button Press"},soundOn:{id:"33",
name:"Sound ON Button Press"},soundOff:{id:"34",name:"Sound OFF Button Press"},close:{id:"23",name:"Close Button Press"}},u="adform-video-",A=u+"state-",y=u+"sound-",n=b.isIPad,O=b.isIPhone,K=O||n,M=b.isAndroid,F=b.isWinPhone,G=O||F,x,N;i.supported=function(a){"undefined"==typeof x&&(N=c.createElement("video"),x=!!N.canPlayType);return!x?!1:!s(a)?!1:!0};i.READY="ready";i.LOADED="loaded";i.HIDE="hide";d.write=function(){function a(){r.play()}function c(a){var b=r.muted;d(!b);d(b);w=a;p.className=p.className.replace(zb,
" "+A+a)}function d(a){K||(r.muted=a,p.className=p.className.replace(Ab," "+y+(a?"off":"on")))}function f(a,b){if(na.length||ta){if(!b&&a!=sa){var c=100*sa,d=100*(0.5<sa-a?1.1:a);0>=c&&0<d?(ta=ta||s.list($a).length,s.emit($a)):100>=c&&100<d&&(ta=ta||s.list(v).length,s.emit(v));for(var e=0,h=na.length;e<h;e++)if(na[e]>=c&&na[e]<d){s.sendEvent(o["progr"+na[e]]);na.splice(e,1);break}}sa=a}}var s=this,q=s.data,x=s.options,B=s._element,C=q.document=s.doc,D=new k(q);b.loadCSS(C,q.css);var m=q.closeButtonAlign;
s.element('<div class="'+u+"container "+u+"device-"+(O?"iphone":n?"ipad":M?"android":"default")+'"></div>',B);var B=s._elem,p=B.firstChild,r=D.element;p.appendChild(r);var I,H=["width:"+q.width+"px","height:"+q.height+"px"];q.poster&&(H.push("background-image:url('"+q.poster+"')"),H.push("background-size:contain"));var F=b.html('<a class="adform-video-poster" style="'+H.join(";")+'"></a>');p.appendChild(F);var h,J,N,U;if(G){F.style.position="relative";r.style.position="absolute";r.style.top="-100000px";
var H=0.25*Math.min(q.width,q.height)/90,H="scale("+H+", "+H+");",j=b.html('<div style="'+["-ms-transform:"+H,"-webkit-transform:"+H,"-o-transform:"+H,"-moz-transform:"+H].join("")+'" class="adform-video-big-play"></div>');F.appendChild(j);e(F,"click",a);q.link&&q.poster&&(I=function(){g(F,"click",a);F.removeChild(j);F.href=q.link;F.target=x.landingPageTarget})}else h=u+"play-pause",J=u+"stop",N=u+"sound",h=new t({className:h,document:C}),J=new t({className:J,document:C}),N=new t({className:N,document:C}),
U=new l({container:p}),q.link?(F.href=q.link,F.target=x.landingPageTarget):F.style.cursor="auto",I=function(){F.style.opacity=0},p.appendChild(h.element),p.appendChild(J.element),p.appendChild(N.element),p.appendChild(U.element);if(I)D.on("state",function(a){if(a=="playing"){D.off("state",arguments.callee);I()}});m&&(H=new t({className:u+"close",document:C}),H.element.appendChild(b.html('<div><div class="adform-video-close-icon">&times;</div></div>',C)),p.className+=" "+u+"stopAlign-"+m,p.appendChild(H.element),
H.on("buttonClick",function(){r.pause();s.emit(i.HIDE);s.sendEvent(o.close)}));var w=D.playbackState,V=!1,zb=RegExp("\\s*"+A+"\\S+|$"),Ab=RegExp("\\s*"+y+"\\S+|$");d(s.data.muted);c("stoped");D.on("state",function(a){V||c(a)});var sa=0,na=[0,25,50,75,100],ta=!1,$a="video:start",v="video:end";G?(D.on("timeupdate",f),e(r,"ended",function(){sa=0.9;f(0)}),M&&e(r,"click",function(){r.play()})):(e(r,"volumechange",function(){d(r.muted)}),D.on("timeupdate",function(a){if(!V){f(a);U.setProgress(a)}}),D.on("loadProgress",
U.setLoadProgress),h.on("buttonClick",function(){if(w=="playing"){r.pause();s.sendEvent(o.pause)}else{r.play();s.sendEvent(o.play)}}),J.on("buttonClick",function(){w=="playing"&&r.pause();D.setProgress(0);s.sendEvent(o.stop)}),U.on("seek",function(a){D.setProgress(a);f(a,true)}),U.on("startSeek",function(){V=true;r.pause()}),U.on("endSeek",function(){V=false;w=="playing"&&r.play()}),N.on("buttonClick",function(){d(!r.muted);r.muted?s.sendEvent(o.soundOff):s.sendEvent(o.soundOn)}));s.pause=function(){r.pause()};
s.play=function(){if(!r.src){r.src=D.source.src;r.load()}r.play()};B.appendChild(p);s.created=!0;s.emit("ready");s.emit("loaded")};d.show=function(){this._element&&!this.created&&this.write()};d.hide=function(){this.created&&(this.restartAnim?this.destroy():this.pause())};d.destroy=function(){this.pause();this.element("",!1);this.created=0};d.sendEvent=function(b){b&&a.Events&&a.Events.sendEvent&&a.Events.sendEvent(this.xId,b.id,this.assetId,b.name,"")};b.inherit(k,f);var V="id,class,width,height,controls,autoplay,poster".split(",");
b.inherit(l,f);b.inherit(t,f)})(Adform=window.Adform||{},window,document);
(function(a){function d(c,l){d.super_.call(this,c,l);this.created=!1;this.data=l;this.adId=i.gid("Adform");this.data.id=this.id="ad"+this.adId;this.assetId=l.assetId||0;a.Log&&a.Log.pushMessage(["AssetType_image"],"",{bn:c.bn})}a.RMB=a.RMB||{};var c=a.RMB;c.Content.ImageTag=d;var i=c.lib,k=i.addEvent;i.inherit(d,c.AdContent);c=d.prototype;d.supported=function(){return!0};d.READY="ready";d.LOADED="loaded";d.HIDE="hide";c.show=function(){this._element&&!this.created&&this.write()};c.hide=function(){};
c.write=function(){var a=this,c=a.data,d=a._element,s=a.options,b=c.useClose,f='<img src="'+c.src+'" border="0" id="'+c.id+'" width="'+c.width+'" height="'+c.height+'" alt="" style="cursor:pointer" />';c.link&&(f='<a href="'+c.link+'" target="'+s.landingPageTarget+'">'+f+"</a>");b&&(f+='<img src="'+s.scriptsBase+'assets/images/close-sprite.png" style="width:50px!important;height:50px!important;position:absolute!important;top:0!important;right:0!important;padding:0!important;margin:0!important;cursor:pointer;">');
a.element(f,d);c=i.byTag(a._elem,"img");k(c[0],"load",function(){a.emit("loaded")});b&&k(c[1],"click",function(){a.emit("hide",!0)});a.created=!0;a.emit("ready")};c.destroy=function(){if(this._elem){var a=i.byTag(this._elem,"img")[0];a.src=a.src}this.element("",!1);this.created=!1}})(Adform=window.Adform||{},window,document);
(function(a){function d(c,b){var f=this;d.super_.call(f,c,b);f.id="ad"+k.gid("Adform");l.setupPolite.call(f);f.video=!1;l.setCallbacks(f,f.external={});f.external.resize=function(a,c){b.height=a;b.width=c;var d=f.element();if(d&&(d=k.byTag(d,"iframe")[0]))d.height=d.width="100%";f._adbox&&f._adbox.set({width:a,height:c})};f.external.setLayout=function(a){f.external.resize(a.width,a.height);var b=a.type&&k.isMobile&&(k.isIOS||k.isAndroid);f._adbox&&b&&f._adbox.reset(a)};f.sharedEvents=new q;var e=
f.flashvars=b.flashvars,b=k.extend({},b);e.expandTime=c.showTime||0;e.collapseTime=c.hideTime||0;e.behavior=c.behavior;var g=c.landingPageTarget;e.landingPageTarget="_self"==g?"_parent":g;if(g=c.userParams)for(var o in g)g.hasOwnProperty(o)&&!(o in e)&&(e[o]=g[o]);b.id=f.id;f.data=b;f.assetId=b.assetId||0;f.state(t);f.once(a.PAGE_LOAD_COMPLETE,f.write);a.Log&&a.Log.pushMessage(["AssetType_html"],"",{bn:c.bn});var u;f.on(l.INSCREEN_INIT,function(){var a=i(c.xId),b=l.INSCREEN_UPDATE;u||(u=!0,a.on("change",
function(a){f.callSwfMethod(b,a)}));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};f.callSwfMethod(b,a)})}a.RMB=a.RMB||{};var c=a.RMB;c.Content.HTML=d;var i=c.EngagementAPI,k=c.lib,q=c.EventEmitter,l=c.Content.FlashTag,t="initial";k.inherit(d,c.AdContent);d.READY="ready";d.supported=function(){return!k.isIOS&&!k.isAfmaSDK&&(k.isAndroid||k.isMobile&&!k.isIE)?k.isSafari||k.isChrome||k.isOperaMobile||k.isFF||k.isInternet||k.isAndroidApp||k.isOperaWebKit:!0};c=d.prototype;
c.show=function(){var a=this._element;this.write();setTimeout(function(){a&&(a.style.background="")},100);this.element().style.width=this._width;this.state("visible")};c.hide=function(){var a=this._element;this.state("hidden");a&&this.created&&(this.callSwfMethod("pauseVideo"),a=this.element().style,this._width=a.width,a.width=0)};c.write=function(){var c=this,b=c._element;if(b&&!c.created){var d=c.options,e=c.data,g=c.win,i=k.gid("AdformWin"),l=e.src.replace(/[^\/]+$/,"");g[i]=function(b){function e(){g.close()}
c._contentWindow=b;var g=b.document,i=c.flashvars;b._Adform=a;b._AdformContent=c;var l=c.options.scriptsBase;b.API_URL=l+"rmb/Adform.DHTML.js?bv="+i.bv;var o='<script src="'+l+"rmb/Adform.WriteHelper.js?bv="+i.bv+'"><\/script>',q=[],t,u=function(a){g._write(a+"<script>document._finish();<\/script>")};g._write=g.write;g.write=k.isIE?function(a){var a=a+"",b;q.length?q.splice(-1,0,a):(b=a.match(/(<\!--[\s\S]*?--\>)|(<script(?:\s+[^>]*)?>[\s\S]*?<\/script>)/i))?(a=b[2],b=RegExp.leftContext+b[0],q.unshift(RegExp.rightContext),
a?g._write(b+(a.match(/^<script[^>]+?src/i)?o:"<script>document._continue();<\/script>")):(g._write(b),g._continue())):u(a)}:u;g._continue=function(){var a=q.join("");q.length=0;g.write(a)};g._writeln=g.writeln;g.writeln=function(a){g.write(a+"\r\n")};g._finish=function(){clearTimeout(t);t=setTimeout(e,10)};var A;k.addEvent(b,"load",function(){if(!A){A=!0;k.removeEvent(b,"load",arguments.callee);var e=a.ADFEventsInstance;if(e&&e.addElement){var i=g.documentElement.id=k.gid("adform-dhtml-");e.addElement(d.xId,
[i],b)}c.emit("loaded")}})};var q="t"+i;g[q]=function(a){var b=a.contentWindow.document;b.close();(!b||!k.byTag(b,"base")[0])&&setTimeout(function(){b.open();b.write('<!DOCTYPE html><base href="'+l+'"><script>parent.'+i+"&&parent."+i+'(window)<\/script><script src="'+e.src+'"><\/script>')},0)};b=c.element('<iframe onload="'+q+"&&"+q+'(this)" width="'+e.width+'" height="'+e.height+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>',
b).style;c._width=b.width;b.width=0;c.created=(new Date).getTime();c.emit("ready")}};c.destroy=function(){if(this._elem&&this.created){this.state("destroyed");var c=k.byTag(this._elem,"iframe")[0],b=c.contentWindow||this._contentWindow,d=a.ADFEventsInstance;d&&d.removeElement&&b.document&&d.removeElement(this.options.xId,[b.document.documentElement.id],b);this.docCloseTimer=clearTimeout(this.docCloseTimer);b.cleanupAdform&&b.cleanupAdform();b._AdformContent=b._Adform=null;this.sharedEvents.clear();
k.isIE&&(c.src="about:blank");this.element("",!1);this.created=0}};c.callSwfMethod=function(a){var b=this.sharedEvents;b.emit.apply(b,arguments);this.emit("call:"+a)};c.state=function(a){var b=this._state,c;a&&a!=b&&(this._state=a,(c=this.sharedEvents).emit("changed:state",a),"visible"==a?c.emit("show"):"visible"==b&&c.emit("hide"));return this._state}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function i(a){var g=this;i.super_.call(g,a);var k,u=!1,A=a.flash,y=a.video,n=a.image,O=a.polite,K=a.html,a=a.options;if(A&&q.supported(A.version))k=new q(a,A),u=!0;else if(K&&s.supported())k=new s(a,K);else if(y&&l.supported(y.sources))k=new l(a,y);else if(n&&t.supported())k=new t(a,n),u=!A;else return;var M=g.adBox=(new b).publish("adBox",g);a.hidden&&g.hide();O&&t.supported()?(O=new t(a,O),O.style({position:"absolute",top:0,left:0,zIndex:1}),M.content(O,!0),O.on(f,function(){O.off(f,
arguments.callee);M.content(k);if(k instanceof q)k.on(q.LOADED,function(){O.clear()});else O.clear()})):M.content(k,!0);g.onEngage=function(){g.onEngage=null;M.content().emit(f)};g.setupEngagement(M);A=k.data;a.iab&&(y=d.frameElement.style,y.width=A.width+"px",y.height=A.height+"px");y=a.iframeAPI;y.hasAPI&&y.register(A);A={position:a.position};a.$tag&&(A.before=a.$tag);M.draw(c,A);g.setupUtils(M.id,u?M.id:null);g.setupGateway(M)}a.RMB=a.RMB||{};var k=a.RMB;k.Type.Standard=i;var q=k.Content.FlashTag,
l=k.Content.VideoTag,t=k.Content.ImageTag,s=k.Content.HTML,b=k.AdBox,f=a.PAGE_LOAD_COMPLETE;k.lib.inherit(i,k.AdConstructor);a=i.prototype;a.BANNER_TYPE="Standard Banner";a.destroy=function(){this.adBox&&this.adBox.destroy();this.adBox=null};a.show=function(){this._hidden&&(this._hidden=!1,this.adBox.set("visible",!0))};a.hide=function(){this._hidden||(this._hidden=!0,this.adBox.set("visible",!1),this.reload())}})(Adform=window.Adform||{},window,document);Adform.RMB.AdConstructor.build();