/*
 EngagementTracker.v13.js, version 2.1.75212

 Copyright Adform
 http://www.adform.com

 Date: 2014-03-13
*/
(function(b,e,p){function l(E,a){E.super_=a;i.prototype=a.prototype;E.prototype=new i;E.prototype.constructor=E}function i(){}function m(a,f){for(var c in f)f.hasOwnProperty(c)&&(a[c]=f[c]);return a}function g(a,f){return(f=f||p)&&f.getElementById&&f.getElementById(a)}function z(a,f){var c=!f?p:a.substr?g(a):a;return c?c.getElementsByTagName(f||a):[]}function n(a,f){return~(" "+a.className+" ").indexOf(" "+f+" ")}function q(a,f){n(a,f)&&(a.className=(" "+a.className+" ").replace(" "+f+" "," ").slice(1,
-1),q(a,f))}function j(a){var f=a.offsetTop,c=a.offsetLeft,d,k=h.curCSS,b="static"!=k(a,"position");f||(f=(parseFloat(k(a,"marginTop"))||0)+(b?parseFloat(k(a,"top"))||0:0));c||(c=(parseFloat(k(a,"marginLeft"))||0)+(b?parseFloat(k(a,"left"))||0:0));b&&a.getBoundingClientRect&&(d=h.offset(a,!0));!f&&d&&(f=d.top);!c&&d&&(c=d.left);return{top:f,left:c}}function r(a){var f={relativeX:a[A[0]],relativeY:a[A[1]]};if(null==a.pageX&&null!=a.clientX){var c=p.documentElement,d=p.body;f.pageX=a.clientX+(c&&c.scrollLeft||
d.scrollLeft||0);f.pageY=a.clientY+(c&&c.scrollTop||d.scrollTop||0)}else f.pageX=a.pageX,f.pageY=a.pageY;return f}function v(a,f){if(!(a=a.parentNode))return!1;var c=a.ownerDocument,d=c.body,k=h.curCSS,b;f&&(f+=1);if(e.$sf)return!0;if(h.isIE&&(8>c.documentMode||"BackCompat"==c.compatMode))return!1;for(;a&&a!=d;){if("hidden"==k(a,"overflow"))return!1;if("fixed"==k(a,"position"))break;else if(f&&(b=parseInt(k(a,"z-index"),10))&&b<f)return!1;a=a.parentNode}return!0}function u(){for(var a=0,f=[];a<F.length;a++)"complete"!=
F[a].document.readyState&&f.push(F[a]);if(!(F=f).length||3E4<(new Date).getTime()-Q){I=clearInterval(I);for(a=0;a<J.length;a++)J[a]();J=[];F=[]}}function s(a,f){var c=a.x+a.width,d=a.y+a.height,k=f.x+f.width,h=f.y+f.height,b=Math.max(a.x,f.x),j=Math.max(a.y,f.y),c=Math.min(c,k)-b,d=Math.min(d,h)-j;return 0<c&&0<d?{x:b,y:j,width:c,height:d}:{x:0,y:0,width:0,height:0}}function w(a,f,c,d){var k=function(a){d&&d.apply(a,arguments)},b=z(c,"head"),b=b&&b[0];if(!b)try{throw Error("Can't find head tag.");
}catch(j){k(j)}var q=f.src||f.href,o=q.replace(/[^\da-z_-]/gi,"_"),C=c.adformId||h.gid("doc_"),t=C+"|"+o,i=N[t],o=h.byTag(c,a),g=0,l=o.length;c.adformId=c.adformId||C;if(i)i.loaded?k():i.callbacks.push(k);else{for(;g<l;++g)if(o[g].src==q||o[g].href==q){k();return}N[t]=i={doc:c,src:q,callbacks:[k]};var r=c.createElement(a),A;m(r,f);d&&(A=function(a){r.onload=r.onreadystatechange=r.onerror=null;a?N[t]=null:i.loaded=1;var f=i.callbacks;g=0;for(l=f.length;g<l;++g)f[g](a)},r.onload=function(){A()},r.onreadystatechange=
function(){"complete"==r.readyState&&A()},r.onerror=function(){try{throw Error("Failed to load script: "+q);}catch(a){A(a)}});setTimeout(function(){b.insertBefore(r,b.firstChild)},400)}}b.Log||(b.Log={});b.Log.pushMessage||(b.Log.pushMessage=function(){});b.Log.sendMessage||(b.Log.sendMessage=function(){});b.RMB=b.RMB||{};var o=b.RMB,h=o.lib||(o.lib={});b.lib||(b.lib=h);h.inherit=l;h.define=function(a,f,c){c&&l(a,f);c(a,a.prototype)};h.gid=function(a){var f=+new Date;return(a||"")+(f+f*~~(Math.random()*
1E4)).toString(36)};h.byId=g;h.byTag=z;h.bind=function(a,f){return function(){return f.apply(a,arguments)}};h.extend=m;h.isMouseLeave=function(a,f){if(!a||a.type!="mouseout")return true;for(var c=a.relatedTarget||a.toElement,d,k=f.length;c;){for(d=0;d<k;d++)if(f[d]==c)return false;c=c.parentNode}return true};h.singleCall=function(a){function f(){h=false;var a=d,b=c,E=k;c=d=k=null;a&&a.apply(b,E)}var c,d,k,h;return function(b,j){c=b;d=j;k=x.call(arguments,2);if(j&&!h)h=setTimeout(f,a);else if(!j&&
h){clearTimeout(h);h=false}}};h.onload=function(a,f){try{do{if(a[R])break;a[R]=true;if(a.document.readyState!="complete"){F.push(a);if(!I){Q=(new Date).getTime();I=setInterval(u,200)}}}while(a!=a.parent&&(a=a.parent))}catch(c){}I?J.push(f):setTimeout(f,0)};h.overlap=s;h.overlapElem=function(a,f){var c=h.offset(a),d=h.offset(f);return s({x:c.left,y:c.top,width:a.offsetWidth,height:a.offsetHeight},{x:d.left,y:d.top,width:f.offsetWidth,height:f.offsetHeight})};h.hasClass=n;h.addClass=function(a,f){if(!n(a,
f))a.className=a.className+(" "+f)};h.removeClass=q;h.loadScript=function(a,f,c){w("script",{src:f,type:"text/javascript"},a,c)};h.loadCSS=function(a,f){w("link",{href:f,type:"text/css",rel:"stylesheet"},a)};h.navigator=e.navigator;h.isTMX=function(a){try{var f=a.document,c=f&&f.body;return c&&n(c,"tmx")}catch(d){}return false};h.isolate=function(a,f){var c=a.__adform_isolate;if(!c){var d=a.document,c=z(d,"head")[0],d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';
c.insertBefore(d,c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(f):(new Function("window","("+f+")(window)"))(a)};var x=Array.prototype.slice;h.addEvent=function(f,d,k){return f[a]?f[a](d,k,false):f[c]?f[c]("on"+d,k):false};h.removeEvent=function(a,c,k){return a[f]?a[f](c,k,false):a[d]?a[d]("on"+c,k):false};var a="addEventListener",f="removeEventListener",c="attachEvent",d="detachEvent",k=/([A-Z])/g,t=/^-?\d+(?:px)?$/i,y=/^-?\d/,b=p.defaultView;h.curCSS=b&&b.getComputedStyle?function(a,f){var c=
a.ownerDocument.defaultView;if(c&&(c=c.getComputedStyle(a,null)))return c.getPropertyValue(f.replace(k,"-$1").toLowerCase())||a.style[f]}:p.documentElement.currentStyle&&function(a,f){var c,d,k,h=a.currentStyle&&a.currentStyle[f];if(!t.test(h)&&y.test(h)){c=(k=a.style).left;if(d=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;k.left=f==="fontSize"?"1em":h||0;h=k.pixelLeft+"px";k.left=c;if(d)a.runtimeStyle.left=d}return h===""?"auto":h};var B=function(){function a(){return a}
var f=p.body,c=p.createElement("div"),d;d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
f.insertBefore(c=c.firstChild,f.firstChild);d=c.childNodes;a.dnab=d[0].firstChild.offsetTop!==5;a.sfp=d[1].firstChild.offsetTop===20;a.sbfonv=d[2].firstChild.offsetTop===-5;a.dabftac=z(c,"td").offsetTop===5;f.removeChild(c);f=c=d=null;return B=a},D=/^t(?:able|d|h)$/i;h.offsetFromWindow=function(a){var f,c,d,k;c=a&&a.ownerDocument;if(!c)return null;d=c.documentElement;if("getBoundingClientRect"in d){try{f=a.getBoundingClientRect();k=d.getBoundingClientRect()}catch(b){}if(!f)return{top:0,left:0};if(k.left>
0||k.top>0){f.top=f.top-k.top;f.left=f.left-k.left}return{top:f.top,left:f.left}}f=c.defaultView||c.parentWindow;k=c.body;if(a===c.body)return j(a);a=h.offset(a);c=f&&f.pageYOffset||d.scrollTop||k.scrollTop;d=f&&f.pageXOffset||d.scrollLeft||k.scrollLeft;a.top=a.top-c;a.left=a.left-d;return a};h.offset="getBoundingClientRect"in p.documentElement?function(a,f){var c,d=a&&a.ownerDocument;if(!d)return null;if(!f&&a===d.body)return j(a);try{c=a.getBoundingClientRect()}catch(k){}if(!c)return{top:0,left:0};
var h=d.body,d=d.documentElement;return{top:c.top+(d.scrollTop||h.scrollTop)-(d.clientTop||h.clientTop||0),left:c.left+(d.scrollLeft||h.scrollLeft)-(d.clientLeft||h.clientLeft||0)}}:function(a){var f=a&&a.ownerDocument;if(!f)return null;if(a===f.body)return j(a);var c,d=a.offsetParent,k=f.documentElement,h=f.body;c=(f=f.defaultView)?f.getComputedStyle(a,null):a.currentStyle;for(var b=a.offsetTop,q=a.offsetLeft,o=B();(a=a.parentNode)&&a!==h&&a!==k;){if(o.sfp&&c.position==="fixed")break;c=f?f.getComputedStyle(a,
null):a.currentStyle;b=b-a.scrollTop;q=q-a.scrollLeft;if(a===d){b=b+a.offsetTop;q=q+a.offsetLeft;if(o.dnab&&(!o.dabftac||!D.test(a.nodeName))){b=b+(parseFloat(c.borderTopWidth)||0);q=q+(parseFloat(c.borderLeftWidth)||0)}d=a.offsetParent}if(o.sbfonv&&c.overflow!=="visible"){b=b+(parseFloat(c.borderTopWidth)||0);q=q+(parseFloat(c.borderLeftWidth)||0)}}if(c.position==="relative"||c.position==="static"){b=b+h.offsetTop;q=q+h.offsetLeft}if(o.sfp&&c.position==="fixed"){b=b+Math.max(k.scrollTop,h.scrollTop);
q=q+Math.max(k.scrollLeft,h.scrollLeft)}return{top:b,left:q}};h.client=function(a){var f,c,d,k,a=a.ownerDocument||a;c=a.defaultView||a.parentWindow;d=a.documentElement;k=a.body;if(c.innerWidth){a=c.innerWidth;f=c.innerHeight}else if(d){a=d.clientWidth;f=d.clientHeight;if(!a||k.clientHeight!=k.offsetHeight){a=Math.min(a||123456789,k.clientWidth||123456789);f=Math.min(f||123456789,k.clientHeight||123456789)}}else{a=k.clientWidth;f=k.clientHeight}return{left:c&&c.pageXOffset||d&&d.scrollLeft||k&&k.scrollLeft||
0,top:c&&c.pageYOffset||d&&d.scrollTop||k&&k.scrollTop||0,width:a,height:f}};h.isArray=Array.isArray||function(a){return Object.prototype.toString.call(a)=="[object Array]"};var A=[["offsetX","offsetY"],["layerX","layerY"]];h.getMousePos=function(a){for(var f;f=A.shift();)if(typeof a[f[0]]!="undefined"){A=f;break}f||(A=["x","y"]);h.getMousePos=r;return r(a)};var S=p.createElement("div");h.html=function(a,f){var c=!f&&S||f.createElement("div");c.innerHTML=a;return c.firstChild&&c.removeChild(c.firstChild)};
var b=h.navigator,C=b.vendor,b=b.userAgent,K=/Apple Computer/i.test(C),o=/Google/i.test(C),O=h.isIPad=/iPad/i.test(b),L=h.isIPhone=/iPhone/i.test(b),G=h.isIOS=O||L,M=h.isTouch="ontouchstart"in p.documentElement||"ontouchstart"in e,O=h.isOrientation="orientation"in e,L=h.isAndroid=!G&&(/Android/i.test(b)||M&&!/series60|symbian|windows ce|blackberry/i.test(b));h.isAndroidApp=L&&!/^(?:Opera|Mozilla)/i.test(b);var H;h.isIOSF=G&&(H=/\sos\s(\d+)_\d+/i.exec(b))&&(H=4<H[1]>>0);var P=h.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(b)||
M;H=h.isIE=/msie|Trident/i.test(b);M=h.isFF=/Firefox[\/.]+[^\s]/i.test(b);h.isMACOS=/Mac OS X/i.test(b);h.isWinPhone=H&&P&&/Phone/gi.test(b);var P=h.isOpera=/Opera/i.test(b),T=h.isOperaMobile=/Opera\s(?!Mini)/i.test(b),U=h.isOperaMini=/Opera\sMini/i.test(b),C=h.isOperaWebKit=/OPR/i.test(b)&&/Opera Software/i.test(C),G=h.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(b)&&(G?K:o),K=h.isSafari=!/Chrome|CriOS|Skyfire/i.test(b)&&/Safari+\/[\.\d]+$/i.test(b)&&K,o=h.isInternet=L&&!G&&O&&/Safari\/[\.\d]+$/i.test(b)&&
o;h.isAfmaSDK=/afma-sdk/i.test(b);var V=H?"msie":M?"firefox":T?"operaMobile":U?"operaMini":P?"opera":C?"operaWebKit":G?"chrome":K?"safari":o?"internet":!1;h.browser=function(){return V};if(h.isIE&&("Microsoft Internet Explorer"==h.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(b)||/rv:(\d+[\.\d]*)/i.exec(b)))h.ieVersion=parseFloat(RegExp.$1);h.testPlace=h.isIE&&8>h.ieVersion?function(){return false}:v;h.isSafari&&(h.safariVersion=parseFloat(/Version.([\d.]+)/.exec(b)[1]));var F=[],J=[],R="__adform_onload",
I,Q,N={}})(Adform=window.Adform||{},window,document);
(function(b){function e(){}b.RMB=b.RMB||{};b.RMB.EventEmitter=e;var p=Array.prototype.slice,b=e.prototype;b.emit=function(b){var i=this._events,m=!1,g=arguments;if(i&&(i=i[b]))if("function"==typeof i){switch(g.length){case 1:i.call(this);break;case 2:i.call(this,g[1]);break;case 3:i.call(this,g[1],g[2]);break;case 4:i.call(this,g[1],g[2],g[3]);break;default:i.apply(this,p.call(g,1))}m=!0}else if(i.length){for(var g=p.call(g,1),i=i.slice(),m=0,e=i.length;m<e;m++)i[m].apply(this,g);m=!0}else delete this._events[b];
return m};b.on=function(b,i){this._events||(this._events={});this.emit("newListener",b,i);var m=this._events;m[b]?"function"==typeof m[b]?m[b]=[m[b],i]:m[b].push(i):m[b]=i;return this};b.once=function(b,i){var m=i._once;m?m._times++:(m=i._once=function(){this.off(b,m);1>--m._times&&delete i._once;return i.apply(this,arguments)},m._times=1);return this.on(b,m)};b.off=function(b,i){if(!this._events||!this._events[b])return this;var m=this._events,g=m[b];if(g==i)return delete m[b],this;i&&i._once&&this.off(i._once);
if("function"==typeof g)return this;if(2>g.length&&g[0]==i)return delete m[b],this;for(var e=0,n=g.length,q=[];e<n;e++)g[e]!=i&&q.push(g[e]);q.length!=n&&(q.length?m[b]=q:delete m[b]);return this};b.clear=function(b){b?this._events&&this._events[b]&&delete this._events[b]:delete this._events;return this};b.list=function(b){this._events||(this._events={});var i=this._events;i[b]?"function"==typeof i[b]&&(i[b]=[i[b]]):i[b]=[];return i[b]}})(Adform=window.Adform||{});
(function(b){function e(b){g.push(this);this._doc=b;this._events={};this.dispatchHover=m.bind(this,p)}function p(){for(var b=e._hoverTarget,j=[],g=e._hoverChain,i=n+"hover-",m;b&&"undefined"!=(m=typeof b.className);)"string"==m&&0<=b.className.indexOf(i)&&j.unshift(b),b=b.parentNode;var s=Math.max(j.length,g.length),b=RegExp(i+"\\S+","g");m=[];for(s-=1;0<=s&&g[s]!=j[s];s--){if(g[s])for(var w=l(g[s].className,i,b),o=0;o<w.length;o++)w[o].call(g[s],"hoverout",g[s]);if(j[s]){w=l(j[s].className,i,b);
for(o=0;o<w.length;o++)m.push([w[o],j[s]])}}if(m.length)for(s=0;s<m.length;s++)m[s][0].call(m[s][1],"hoverin",m[s][1]);e._hoverChain=j}function l(b,j,g){b=b.match(g);g=[];if(b){b=("x|"+b.join("|")).split("|"+j).slice(1);for(j=0;j<b.length;j++)z[b[j]]&&g.push(z[b[j]])}return g}function i(b){for(var j=0;j<g.length;j++)if(g[j]._doc==b)return g[j]}b.RMB=b.RMB||{};var b=b.RMB,m=b.lib;b.DOMEvents=e;var g=[],z={},n="adform-domevents-";e.destroy=function(b){var j;if(b)(j=i(b))&&j.destroy();else for(;g.length;)g[0].destroy()};
e.on=function(b,j,g){var i=b.ownerDocument;(e.find(i)||new e(i)).on(b,j,g);return this};e.off=function(b,j,g){var i=e.find(b.ownerDocument);i&&i.off(b,j,g);return this};e.find=i;e.dispatchHover=p;e.dispatchClick=function(b,j){for(var g=n+"click-",i=[],m;b&&"undefined"!=(m=typeof b.className);)"string"==m&&0<=b.className.indexOf(g)&&i.unshift(b),b=b.parentNode;m=RegExp(g+"\\S+","g");for(var e=i.length-1;0<=e;e--)for(var w=l(i[e].className,g,m),o=0;o<w.length;o++)w[o].call(i[e],"click",i[e],j)};e._hoverChain=
[];e._hoverTarget=null;b=e.prototype;b.on=function(b,j,g){var i=g._adform_dom_key;i||(i=g._adform_dom_key=m.gid());i in z||(z[i]=g);g=n+j+"-"+i;0>b.className.indexOf(g)&&(b.className+=" "+g,this.setup(j))};b.off=function(b,j,g){if(g=g._adform_dom_key)b.className=b.className.replace(n+j+"-"+g,"")};b.destroy=function(){var b=this._events,j,i,n,p=this._doc;for(j in b)for(i in n=b[j],n)m.removeEvent(p,i,n[i]);for(b=g.length;0<b--;)if(g[b]==this){g.splice(b,1);break}b=e._hoverChain;b[0]&&b[0].ownerDocument==
p&&(e._hoverChain=[],e._hoverTarget=null);this._doc=this._events=null};b.setup=function(b){if(!this._events[b]){this._events[b]={};var g=this._doc,i=g.defaultView||g.parentWindow,n,p;"hover"==b?(g.addEventListener?(n=function(b){e._hoverTarget!=b.target&&(e._hoverTarget=b.target,e.dispatchHover())},p=function(b){e._hoverTarget!=b.relatedTarget&&(e._hoverTarget=b.relatedTarget,e.dispatchHover())}):(n=function(){i=g.defaultView||g.parentWindow;e._hoverTarget!=i.event.srcElement&&(e._hoverTarget=i.event.srcElement,
e.dispatchHover())},p=function(){i=g.defaultView||g.parentWindow;e._hoverTarget!=i.event.toElement&&(e._hoverTarget=i.event.toElement,e.dispatchHover())}),m.addEvent(g,"mouseover",this._events[b].mouseover=n),m.addEvent(g,"mouseout",this._events[b].mouseout=p),m.addEvent(g,"mousemove",this._events[b].mousemove=n),e._hoverChain=[]):"click"==b&&(n=g.addEventListener?function(b){e.dispatchClick(b.target,b)}:function(b){i=g.defaultView||g.parentWindow;b=i.event;e.dispatchClick(b.srcElement,b)},m.addEvent(g,
"mousedown",this._events[b].mousedown=n))}}})(Adform=window.Adform||{},window,document);
(function(b,e){var p=b.ET=b.ET||{};if(!p.ActiveTab){var l=b.RMB,i=l&&l.lib||b.lib,m=Date.now||function(){return(new Date).getTime()},g=new l.EventEmitter;p.ActiveTab=g;g.init=function(e){function n(){var a,f=i.removeEvent;u=!0;l.clear();t&&(a=e.top.document,f(e.top,"scroll",t),f(a,"mousemove",t),f(a,"keydown",t),f(a,"mousedown",t),f(a,"mouseup",t),t=null)}function q(){var a=f&&c,b;b=m();var g=b-d;o?f=!w[o]:h?(d=b,g>y&&l.emit(l.IDLE,g)):s&&(f=g<B);k&&(c=b-k<D);b=f&&c;a!=b&&l.emit(l.VISIBLE,b);l.wasActive||
(l.wasActive=b);return b}function j(){u||(d=m(),s(j))}function p(a){k=m();t=function(f){var f=f||a.event,c=!(f&&"mousemove"==f.type),h=b,g=d;c||(b=f.screenX,d=f.screenY,c=b!=h||d!=g);c&&(k=m())};var f=a.document,c=i.addEvent,b,d;setTimeout(function(){c(a.top,"scroll",t);c(f,"mousemove",t);c(f,"keydown",t);c(f,"mousedown",t);c(f,"mouseup",t)},100)}var l=g;l.isActive=q;l.update=q;l.destroy=n;var u;n();u=!1;for(var s=e.webkitRequestAnimationFrame,w=e.document,o,h=i.isIOS,x=["hidden","mozHidden","msHidden",
"webkitHidden"],a=x.length;a--;)if(x[a]in w){o=x[a];break}var f=!0,c=!0,d=m(),k,t,y=1E3,B=250,D=3E4;!o&&!h&&s&&s(j);if(!i.isTouch&&!b.ADFIframe)try{e.top.document.getElementById,p(e.top)}catch(A){}};g.IDLE="idle";g.VISIBLE="visible";g.init(e)}})(Adform=window.Adform||{},window,document);
(function(b){function e(b){this._delay=b||0;this._diff=this._start=this._count=this._partial=0;this.active=!1;this.count=this.time=0;this._list=[]}function p(){this.exposure=this._exp=this._exposure=this._mod=0;p.super_.apply(this,arguments)}var l=b.ET=b.ET||{};if(!l.Timer){var b=(b=b.RMB)&&b.lib,i=Date.now||function(){return(new Date).getTime()};l.Timer=e;l.ExposureTimer=p;e.calculateEngagement=function(){for(var b=arguments,g=[],e=i(),n=0;n<b.length;n++)for(var l=b[n]._list,j=0;j<l.length;j+=2)g.push([l[j],
l[j+1]||e]);g.sort(function(b,g){return b[0]-g[0]});b=0;if(g.length){e=[[g[0][0],g[0][1]]];n=1;j=0;for(l=g.length;n<l;n++)e[j][1]<g[n][0]?e[++j]=[g[n][0],g[n][1]]:e[j][1]<g[n][1]&&(e[j][1]=g[n][1]);n=0;for(l=e.length;n<l;n++)b+=e[n][1]-e[n][0]}return b};l=e.prototype;l.update=function(){this.active=!1;this._diff=0;var b=this._list,g=this._start,e=this._paused,n=b.length%2;if(g){var l=(e||i())-g;l>=this._delay&&(this.active=!e,this.count=this._count+1,this.time=this._partial+l,this._diff=l,!n&&!e&&
b.push(g))}n&&(!g||e)&&b.push(i());return this};l.start=function(){this._start||(this._start=i(),this.update());return this};l.stop=function(){this._start&&(this.update(),this._count=this.count,this._partial=this.time,this._start=0,this.update());return this};l.paused=function(b){b&&!this._paused?(this._paused=i(),this.update()):!b&&this._paused&&(this.update(),this._paused=0,this._partial=this.time,this._start&&(this._start=i()),this.update());return this};b.inherit(p,e);l=p.prototype;l._update=
l.update;l.update=function(){this._update();this._exp=this._exposure+this._mod*this._diff;this.exposure=Math.round(this._exp);return this};l._stop=l.stop;l.stop=function(){this._start&&(this.update(),this._exposure=this._exp);return this._stop()};l.modifier=function(b){b!=this._mod&&this.active&&(this.stop(),this._mod=b,this.start());this._mod=b}}})(Adform=window.Adform||{},window,document);
(function(b){function e(b){this.minPercent=b;var e=this.visibility=new i;this.mouse=(new i(1E3)).paused(!0);this.video=new i;this.expand=new i;var n=this.exposure=new m;l.on(l.IDLE,function(b){0<e._start&&(e._start+=b);0<n._start&&(n._start+=b)})}function p(b){var i=this.exposure,e=this.mouse,m=this.visibility,j=m.active;b&&!j?(i.start(),m.start(),e.paused(!1)):!b&&j&&(i.stop(),m.stop(),e.paused(!0))}b=b.ET=b.ET||{};if(!b.Counter){var l=b.ActiveTab,i=b.Timer,m=b.ExposureTimer;b.Counter=e;b=e.prototype;
b.update=function(b,i,e){b=this.visiblePercent=Math.round(100*i/b);this.exposure.modifier(i/e||0);p.call(this,b>=this.minPercent)};b.action=function(b){if("stop"===b)return p.call(this,!1);if((b={over:1,out:2,expand:3,collapse:4,videoPlay:5,videoStop:6}[b])&&b--)[this.mouse,this.expand,this.video][b>>1][b%2?"stop":"start"]()}}})(Adform=window.Adform||{},window,document);
(function(b){function e(i,e){function g(){x.length=2}function l(a,f,b){q(a,f,"check",b)}function n(a,f,b,c){q(a,f,"change",c,b)}function q(a,f,b,c,d){if(w&&w[b])if(j(a,f),x[0]=a,x[1]=f,x[2]=c,"undefined"!=typeof d)w[b](d);else w[b]();else setTimeout(function(){q(a,f,b,c,d)},100)}function j(a,f){B.x=a;B.y=f;k.left=a+"px";k.top=f+"px";k.width=k.height=0;d.offsetWidth;k.width=v+"px";k.height=u+"px";d.offsetWidth}function r(a){t?a&&a(!h):a&&(y=a);return this}var v=e.width||1,u=e.height||1,s=e.debug||
0,w,o=("flash_"+(Date.now()+Math.random())).replace(".","_"),h=!1,x=[],a=b.scriptBase+"assets/flash/fr.swf?1e963d1013e5525f3107134e9e9d4df5",f=i.document,c=e.container||f.body,d=f.createElement("div"),k=d.style;k.position="fixed";k.zIndex=1E4;k.width=v+"px";k.height=u+"px";p.isIE||(k.visibility="hidden");c.appendChild(d);var t=!1,y,B={move:j,init:r,destroy:function(){d.innerHTML="";d.parentNode.removeChild(d);x.length=0;i[D]=d=k=null}},D=o+"demand";i[D]=function(a){var f=x[0],b=x[1],c=x[2];g();c&&c(f,b,a)};var s=
{debug:s,callback:D,changeInterval:100,limit:2},o=[],A;for(A in s)s.hasOwnProperty(A)&&o.push(A+"="+s[A]);d.innerHTML='<object type="application/x-shockwave-flash" data="'+a+'" width="'+v+'" height="'+u+'" style="position:absolute;top:0;left:0;width:100%;height:100%"><param name="movie" value="'+a+'"><param name="allowscriptaccess" value="always"><param name="wmode" value="transparent"><param name="flashvars" value="'+o.join("&")+'"></object>';w=d.firstChild;l(-1E4,-1E4,function(a,f,b){B.check=l;
B.reset=g;B.change=n;h=b;t=true;r(y)});return B}var p=b.lib,l=b.ET=b.ET||{};l.flashVisibilityOverlay||(l.flashVisibilityOverlay=function(i){function m(){return o}function g(){var b=i.innerWidth,d=i.innerHeight;if(f!==b||c!==d)f=b,c=d,t=[[0,0],[f-a,c-a],[f-a,0],[0,c-a],[(f-a)/2,(c-a)/2]]}function l(){--B||n(p)()}function n(a){g();for(var f=y.length;f--;)y[f].reset();return a}function p(){for(var a=t.length,f=a;a--;)(function(a,b){b[2]=!1;y[a].check(b[0],b[1],function(a,c,d){b[2]=d;(!--f||!d)&&n(j)()})})(a,
t[a])}function j(){var a=t[0][2];if(t[1][2]&&a)o={x:0,y:0,width:f,height:c},n(r)();else{for(var a=t.length,b=[];a--;)t[a][2]&&b.push(t[a]);b.length?n(u)(b):(o={x:0,y:0,width:0,height:0},n(r)())}}function r(){var b=[];if(o.width&&o.height){var d=o.x,k=o.y,h=o.x+o.width,i=o.y+o.height;b.push([d,k,!0]);b.push([h-a,i-a,!0]);0<d&&b.push([d-a,k,!1]);0<k&&b.push([d,k-a,!1]);h<f&&b.push([h,i-a,!1]);i<c&&b.push([h-a,i,!1])}else for(d=t.length;d--;)b[d]=[t[d][0],t[1],!1];for(d=b.length;d--;)y[d].change(b[d][0],
b[d][1],!b[d][2],v)}function v(){n(p)()}function u(a){d=k=null;for(var f=a.length,b;0<f--;)b=a[f],w(b[0],b[1],!0);s()}function s(){function a(f,b,c){w(f,b,c);--t||s()}var f=d.minX,b=d.minY,c=d.maxX,h=d.maxY,i=f-k.minX,g=b-k.minY,e=k.maxX-c,o=k.maxY-h,j=Math.max(i+e,g+o),t=Math.round(Math.min(y.length,j));if(1>=j)d=k=null,n(r)();else{var m=j===i+e,l=[];m?o=e:i=g;j=Math.round(t*i/j);e=t-j;i/=j+1;o/=e+1;g=Math.floor((m?b+h:f+c)/2);if(m){for(;j--;)l.push([Math.floor(f-i*(j+1)),g]);for(;e--;)l.push([Math.floor(c+
o*(e+1)),g])}else{for(;j--;)l.push([g,Math.floor(b-i*(j+1))]);for(;e--;)l.push([g,Math.floor(h+o*(e+1))])}for(f=l.length;f--;)y[f].check(l[f][0],l[f][1],a)}}function w(b,h,i){var g=d,e=k;d||(g=d={minX:b,minY:h,maxX:b+a,maxY:h+a},e=k={minX:0,minY:0,maxX:f,maxY:c});if(i)g.minX=Math.min(g.minX,b),g.minY=Math.min(g.minY,h),g.maxX=Math.max(g.maxX,b+a),g.maxY=Math.max(g.maxY,h+a);else if(b<g.minX&&(e.minX=Math.max(e.minX,b+a)),h<g.minY&&(e.minY=Math.max(e.minY,h+a)),b>g.maxX&&(e.maxX=Math.min(e.maxX,b)),
h>g.maxY)e.maxY=Math.min(e.maxY,h);0.2>((e.maxX-e.minX)*(e.maxY-e.minY)-(g.maxX-g.minX)*(g.maxY-g.minY))/(f*c)&&(b=Math.floor((g.minX+e.minX)/2),h=Math.floor((g.minY+e.minY)/2),o={x:b,y:h,width:Math.floor((g.maxX+e.maxX)/2)-b,height:Math.floor((g.maxY+e.maxY)/2)-h})}if(i.__flash_visibility)return i.__flash_visibility(i);var o;m.destroy=function(){for(var a=y.length;a--;)y[a].destroy();y=[];i.__flash_visibility=null};for(var h=0,x=i;x.parent!=x;)h++,x=x.parent;i.__flash_visibility=m;if(10.3>b.ADFUtilInstance.getFlashVersion())return o=
!1;for(var a=1,f,c,d,k,t,y=[],B=h=6;h--;)y[h]=e(i,{width:a,height:a,debug:0}).init(l);g()},l.FlashMonitor=e)})(Adform=window.Adform||{},window,document);
(function(b,e){var p,l,i,m;function g(b){for(var g=b.length,h=b[g-1],i=0,a=0,f=h.width,c=h.height;0<g--;)h=b[g],i=Math.max(0,i),a=Math.max(0,a),f=Math.min(h.width,f),c=Math.min(h.height,c),i+=h.x,a+=h.y,f+=h.x,c+=h.y;return i<f&&a<c&&{x:i,y:a,width:f-i,height:c-a}||{x:0,y:0,width:0,height:0}}function z(){var b,g,h,i,a,f,c,d;if((b=e.$sf)&&(b=b.ext)&&(b=b.geom()))return g=b.self,h=b.par,b=+g.t,i=+g.r,a=+g.b,g=+g.l,f=+h.t,c=+h.r,d=+h.b,h=+h.l,h=Math.max(g,h),f=Math.max(b,f),i=Math.min(i,c),a=Math.min(a,
d),{x:h-g,y:f-b,width:i-h,height:a-f}}function n(b){var g,h=b.document,e=h.documentElement.msContentZoomFactor,a,f=b.screen,c=f.availLeft||f.left||0,d=f.availTop||f.top||0,k=f.availWidth,f=f.availHeight;e&&1!==e&&(k/=e,f/=e);var e=c+k,t=d+f;l=Math.min(l,c);p=Math.max(p,e);m=Math.min(m,d);i=Math.max(i,t);"mozInnerScreenX"in b?a=[b.mozInnerScreenX,b.mozInnerScreenY]:"screenX"in b&&b===b.top?a=[b.screenX,b.screenY]:h.fireEvent&&h.attachEvent&&(g=j.byId("adform-inscreen-detector",h),g||(g=h.createElement("div"),
g.id="adform-inscreen-detector",g.style.position="absolute",g.style.top="-9999px",h.body.insertBefore(g,h.body.firstChild)),g.attachEvent("onmouseleave",function(f){f=f||b.event;f.cancelBubble=true;g.detachEvent("onmouseleave",arguments.callee);l=Math.min(l,f.screenX);p=Math.max(p,f.screenX);m=Math.min(m,f.screenY);i=Math.max(i,f.screenY);a=[f.screenX-f.clientX,f.screenY-f.clientY]}),g.fireEvent("onmouseleave"));"screenX"in b&&"outerWidth"in b&&(h=b.screenX,c=b.screenY,d=h+b.outerWidth,e=c+b.outerHeight,
l>=d-8&&(l=Math.floor(h/k)*k),p<=h+8&&(p=Math.ceil(d/k)*k),m>=e-8&&(m=Math.floor(c/f)*f),i<=c+8&&(i=Math.ceil(e/f)*f));return a}var q=b.ET=b.ET||{};if(!q.ViewUtil){var j=b.RMB.lib,r=q.flashVisibilityOverlay,v=q.ActiveTab,u=j.isSafari&&!("webkitRequestAnimationFrame"in e);l=0;p=screen.availWidth;m=0;i=screen.availHeight;q.ViewUtil={inView:function(b){var e,h,q,a;for(a=[];b;){h=j.client(b);e=j.offset(b);e={x:e.left,y:e.top,width:b.offsetWidth,height:b.offsetHeight};q||(q=e,q.area=q.width*q.height,q.visible=
!0);if(!e.height||"hidden"==j.curCSS(b,"visibility"))return q.visible=!1,q;a.unshift({x:e.x-h.left,y:e.y-h.top,width:e.width,height:e.height});a.unshift({x:0,y:0,width:h.width,height:h.height});e=b.ownerDocument;e=e.defaultView||e.parentWindow;if(s===e)break;try{e.parent&&e.parent.document.getElementById,b=e.frameElement}catch(f){s=e;break}}var c,d,k,b={x:0,y:0,width:0,height:0},t=n(e);k={x:0,y:0,width:p-l,height:i-m};"screenX"in e&&"outerWidth"in e&&(c={x:e.screenX-l,y:e.screenY-m,width:e.outerWidth,
height:e.outerHeight});if(t)q.optimize=!0,a.unshift(h={x:t[0]-l,y:t[1]-m,width:h.width,height:h.height}),e===e.top?h=g([k,h]):c?(a[0].x-=c.x,a[0].y-=c.y,a.unshift(c),h=g([k,c])):h=k,!j.isIOS&&!j.isAndroid&&a.unshift(k);else{if(k=z())d=k;else if(v.isActive()&&(!u||11<=j.ieVersion))d=r(e);d?(q.voidSend=!1,q.optimize=!0,a[0].x=-d.x,a[0].y=-d.y,b={x:0,y:0,width:d.width,height:d.height}):(!1===d&&(q.optimize=!0),q.voidSend=!0);a.unshift(b);c&&(h=c)}q.visible&&(a=g(a),a.area=a.width*a.height,q.overlap=
a,q.client=h);return q},getOverlap:g,safeFrame:z,getScreenXY:n};var s=e.top}})(Adform=window.Adform||{},window,document);
(function(b,e,p){function l(b){this.settings=b;b.ufcEnabled&&(this.ufc={visibility:[2E3,3E3,5E3,1E4,15E3,3E4],exposure:[200,400,600,1E3,2E3,4E3]});var c=b.visibilityArea||50;"object"!=typeof c&&(c=[c]);for(var d=this.counters=[],k=0;k<c.length;k++)d.push(new h(c[k]));d=d[0];this.visibility=d.visibility;this.mouse=d.mouse;this.video=d.video;this.expand=d.expand;this.exposure=d.exposure;this.clicks={length:0};this.flashClicksCount=this.jsClicksCount=0;this.hmClicks=[];this.jsClicks=[];this.flashClicks=
[];this.children=[];this.dimensions=[{width:b.width,height:b.height}];this.bannerProperties={};this.status="NOT VISIBLE";for(var k=0,e;k<a.length;k++)if((e=b[a[k]])&&"undefined"!=e)this[a[k]]=e;this.objectId||(this.objectId="FlashID"+this.id);this.data={visibilityT:0,mouseO:0,activeT:0,exposure:0,visibilityArea:c[0],maxVisibility:0,currentVisibleArea:0};this.hoverDelay=u.singleCall(0);this.hover=u.bind(this,g);this.click=u.bind(this,i);this.hmClick=u.bind(this,m);this._attributes={};this._syncChild=
1<(b.compoundSeqNo||0);this._logger=j(this)}function i(){this.jsClicksCount++;this.updateData()}function m(a,b,d){(a="object"==b.nodeName.toLowerCase()&&u.byTag(b,"embed")[0])&&20<a.offsetHeight&&(b=a);b=u.offset(b);d=u.getMousePos(d);this.hmClicks.push({x:Math.floor(d.pageX-b.left),y:Math.floor(d.pageY-b.top)})}function g(a){this.hoverDelay(this,z,"hoverin"==a)}function z(a){n(this.counters,a?"over":"out");this.updateData()}function n(a,b,d,k,e){for(var g=a.length;g--;)d&&a[g].update(d,k,e),b&&a[g].action(b)}
function q(a){for(var b=r.EngagementTracker().windows,d=0,k=b.length,e,g;d<k;d++)if((g=b[d].document)&&(e=u.byId(a,g)))return e}function j(a){function b(){return!0}if(this instanceof j){var d=a.data,e=a.settings,g=a.visibility,h=r.EngagementTracker(),i=[],l=[],m=[],o=[],n=[];a._syncChild?m.push(this.make("EngagementTracker","Unload string has not been send for SYNC banner",b,function(){return{compoundSeqNo:e.compoundSeqNo,xId:e.id,version:h.version}})):(i.push(this.make("Unload_total","Banner is registered for in-view tracking",
b)),i.push(this.make("Unload_init","Banner is registered for in-view tracking",function(){return a.ufc||u.isFF||u.isIE||u.isChrome||u.isSafari||u.isOperaWebKit})),i.push(this.make("Unload_sent","Banner is registered for in-view tracking",function(){return!a._syncChild&&!a.doNotSendData&&a.unloadID&&a.bn&&a.object})),l.push(this.make("Unload_loaded","Banner is fully loaded",function(){return a.fullyLoaded})));o.push(this.make("Unload_percent","Unload string has incorrect percent",function(){return(e.visibilityArea||
50)>d.maxVisibility&&g.time>0},function(){return{expected:e.visibilityArea||50,actual:d.maxVisibility,time:g.time}}));n.push(this.make("Unload_oldAd","Old banner detected",function(){return a._oldCompatibility}));this.info={bn:e.bn,iframeSandbox:!h.friendly,browser:u.browser()};this.list={stats:i,loaded:l,sync:m,percent:o,old:n};this.update()}else return new j(a)}var r=b.ET=b.ET||{};if(!r.EngagementItem){var v=b.RMB,u=v&&v.lib,s=v&&v.DOMEvents,w=r.ActiveTab,o=r.Timer,h=r.Counter,x=r.ViewUtil,a="bn,unloadID,cookieID,id,width,height,sendUnloadData".split(",");
r.EngagementItem=l;v=l.prototype;v.attr=function(a,b){var d=this._attributes,e=arguments.length;return 1<e?d[a]=b:e?d[a]:d};v.update=function(){var a=(this._elements||this.elements()).slice(),b=this.fullyLoaded=this.attr("loaded"),d,e=[],g=this.children;if(g.length)for(var h=0;h<g.length;h++)a.push.apply(a,g[h]._elements||g[h].elements(this));if(!this.optimizeLoop||w.isActive())for(var h=0,i;h<a.length;h++)if(g=a[h]){var j="object"==g.nodeName.toLowerCase()&&u.byTag(g,"embed")[0];j&&20<j.offsetHeight&&
(g=j);try{i=x.inView(g)}catch(l){setTimeout(function(){throw l;},0);return}"voidSend"in i&&(this.doNotSendData=i.voidSend);i.optimize&&(this.optimizeLoop=!0);d||(d=i);i.visible&&e.push(i)}if(b&&w.isActive()&&e.length){d=e[0];for(var g=i=b=a=0,j=d.client.width*d.client.height,h=0,m=e.length;h<m;h++){a+=e[h].overlap.area;i+=e[h].area;for(var o=h+1,p;o<m;o++)p=u.overlap(e[h].overlap,e[o].overlap),b+=p.width*p.height,p=u.overlap(e[h],e[o]),g+=p.width*p.height}n(this.counters,null,i-g,a-b,j||0);e=this.data.currentVisibleArea=
this.counters[0].visiblePercent;this.data.maxVisibility=Math.max(this.data.maxVisibility,e)}else n(this.counters,"stop");d&&(this.data.x=Math.floor(d.x),this.data.y=Math.floor(d.y));this.updateData();this._logger.update()};v.elements=function(a){var c=this.settings,d=[],g,h=c.trackElements;if(h){for(var i=!0,j=0;j<h.length;j++){var l=q(h[j]);l?d.push(l):i=!1}if(c=c.trackHeatMap)if(l=q(c))s.on(l,"click",this.hmClick);else i=!1;i&&(this._elements=d)}else{var m="undefined"!==typeof inDapMgrIf||"undefined"!==
typeof inDapIF,i=(m?parent:self).document,j=c.flashID||c.objectId||"FlashID"+this.id,c=c.object?c.object:u.byId(c.holderID||j,i);if(!c&&m&&!b.RMB.DataParser){g=u.byId(j,p);if(p.body.id)j=p.body.id;else{a:{try{var o;if(e===parent)o=!1;else{var n;if(!(n=e.frameElement))b:{try{var r=parent.document.getElementsByTagName("iframe");e._iframe_test_var=Math.random();for(c=0;c<r.length;c++)try{if(r[c].contentWindow._iframe_test_var===e._iframe_test_var){delete e._iframe_test_var;n=r[c];break b}}catch(v){}}catch(w){}n=
void 0}o=n}l=o;break a}catch(x){}l=void 0}l&&l.id&&(j=l.id)}c=u.byId(j,i)}c&&c.nodeType&&d.push(c);if(!c||c.id!=j)c=u.byId(j,i),d.push(c);d[0]&&(this._oldCompatibility=!0)}this.object=d[0];for(j=0;j<d.length;j++)if(l=d[j])if(s.on(l,"hover",(a||this).hover),s.on(l,"click",(a||this).click),!h)s.on(g||l,"click",this.hmClick);return d};v.flashClick=function(a,b){this.flashClicksCount++;this.flashClicks.push({x:parseInt(a,10),y:parseInt(b,10)});this.updateData()};v.engage=function(a){n(this.counters,a)};
v.updateData=function(){var a=this.data,b=this.visibility.update();this.status=b.active?"VISIBLE":"NOT VISIBLE";a.visibilityT=b.time;b=this.mouse.update();a.activeT=b.time;a.mouseO=b.count;a.exposure=this.exposure.update().exposure;this.clicks.length=Math.max(this.jsClicksCount,this.flashClicksCount)};v.checkUFC=function(){var a=this.ufc;if(a){for(var b=this.visibility.update().time,d=a.visibility,e=d.length;d.length&&b>=d[0];)d.shift();for(var b=this.exposure.update().exposure,a=a.exposure,g=a.length;a.length&&
b>=a[0];)a.shift();!e&&!g&&(this.ufc=null);return d.length<e||a.length<g}};v.toUnloadString=function(a){if(!this._syncChild&&!this.doNotSendData&&this.unloadID&&this.bn&&this.object&&this.sendUnloadData){for(var b=this.data,d=this.visibility.update(),e=this.mouse.update(),g=this.video.update(),h=this.expand.update(),i=this.exposure.update(),j=this.settings,l=this.hmClicks.length?this.hmClicks:this.flashClicks,m=[],n=0,p=l.length;n<p;n++)m.push((0<l[n].x?l[n].x:0)+":"+(0<l[n].y?l[n].y:0));l=o.calculateEngagement;
g=[g];h=[h];p=this.children;for(n=0;n<p.length;n++)g.push(p[n].video.update()),h.push(p[n].expand.update());n=l.apply(o,g);p=l.apply(o,h);l=l.apply(o,[e].concat(g,h));g=this.counters;b=[b.maxVisibility,d.time,e.count,b.x,b.y,e.time,n,l,p,m.join(";"),i.exposure,r.EngagementTracker().friendly?0:1,j.rtbInventorySourceId||"",j.rtbReqId||"",g[1]?g[1].visibility.update().time:"",g[2]?g[2].visibility.update().time:"",w.wasActive?1:0];d=this.bn+","+this.unloadID+",";e=d+b.join("|");a=r.EngagementTracker().queryLimit-
(a||100);if(e.length>a){for(var e=0,i=m.length,q;e<i;)b[9]=m.slice(0,q=e+i>>1).join(";"),(d+b.join("|")).length>a?i=q:e=q+1;b[9]=m.slice(0,q).join(";");e=d+b.join("|")}return e}};v.addChild=function(a){this.dimensions.push({width:a.width,height:a.height});this.children.push(a);a._attributes=this._attributes};v.destroy=function(){this._elements=this.object=null};v=j.prototype;v.update=function(){if(b.Log){var a=this.list,c=this.info,d,e;for(d in a){for(;a[d]&&a[d].length&&a[d][0].condition();)e=a[d].shift(),
e.info&&(c=u.extend(c,e.info())),b.Log.pushMessage([e.title],e.message,c);(!a[d]||!a[d].length)&&delete a[d]}}};v.make=function(a,b,d,e){return{title:a,message:b,condition:d,info:e}}}})(Adform=window.Adform||{},window,document);
(function(b,e){function p(){var a=this;if(p._instance)return p._instance;if(!(a instanceof p))return new p;p._instance=b.ADFEventsInstance=a;a.maxTime=6E5;a.items=a.events={};a.version=14;a.windows=[];a.byBN={};a._items={};a.startTime=o();a.friendly=!1;try{top.document.getElementById,a.friendly=!0}catch(f){}a.queryLimit=2E3;a.update=r.bind(a,z);a.optimized=r.bind(a,q);r.addEvent(e,"unload",function(){a.send();a.destroy()});setTimeout(r.bind(a,m),54E4);a.setupWindow(e);try{parent!=self&&parent.document.getElementById&&
a.setupWindow(parent)}catch(c){}try{e.MESSENGER_POPUP&&a.setupWindow(MESSENGER_POPUP)}catch(d){}a.registerAll();a.registerInEvents()}function l(){var a=g();if(a)for(var b in a)this.register(a[b])}function i(a){var b=g();b&&(a=this.register(b[a]))&&a.update()}function m(){o()-this.startTime<=this.maxTime&&(r.isFF||r.isIE||r.isChrome||r.isSafari||r.isOperaWebKit)&&this.sendQuery(this.query())}function g(){var a=b.ADFUtilInstance;return a&&a.banners}function z(){s.update();var a=[],b=this.items,c;for(c in b){var d=
b[c];d.update&&(d.update(),d.checkUFC()&&a.push(d))}a.length&&this.sendQuery(this.query(a,"&ufc=1"));this.emit("update")}function n(a,b){var c=this._items[a];if(c){var b=","+b+",",d=x,e;for(e in d)d[e]&&~d[e].indexOf(b)&&c.engage(e)}}function q(){var a=o();100<a-h&&(h=a,this.update())}if(!b.ADFEvents){var j=b.RMB,r=j&&j.lib||b.lib,v=j&&j.DOMEvents,u=b.ET,s=u.ActiveTab,w=u.EngagementItem,o=Date.now||function(){return+new Date};r.inherit(p,j.EventEmitter);u.EngagementTracker=p.getInstance=b.ADFEvents=
p;var h=0,x={expand:[21,22],collapse:[143],videoPlay:[30],videoStop:[31,32,29,21,22,23,143]},j=p.prototype;j.subscribe=function(a){this.on("update",a)};j.unsubscribe=function(a){this.off("update",a)};j.getItem=function(a){var b=this._items;if(b&&(b=b[a]))return this.byBN[b.bn]||b};j.registerAll=l;j.registerAllBanners=l;j.register=function(a){if(a&&!this._items[a.id]&&1==a.registered){var b=this._items[a.id]=new w(a);this.byBN[a.bn]?this.byBN[a.bn].addChild(b):(this.byBN[a.bn]=this.items[a.id]=b,b.update());
this.cookieID||(this.cookieID=b.cookieID)}return this._items[a.id]};j.addObjectEvents=i;j.addStandardEvent=i;j.checkVisibility=function(a){a&&a.update&&a.update()};j.registerBannerProperties=function(){};j.addClick=function(a,b,c){(a=this.items[a])&&a.flashClick&&a.flashClick(b,c)};j.registerInEvents=function(){var a=b.Events;if(a&&a.registerCallback){var f=x,c;for(c in f)f[c].join&&(f[c]=","+f[c].join(",")+",");a.registerCallback(n,this)}};j.query=function(a,b){var c=["version="+this.version+(b||
"")+"&unload="+this.cookieID],d,e,a=a||this.items,g;for(g in a)if((d=a[g])&&d.toUnloadString)(e=d.toUnloadString())&&c.push(e);if(1<c.length)return c.join("@@")};j.send=m;j.sendQuery=function(a){if(a){var a=b.host+"/serving/unload/?"+a,f=this.queryLimit;if(a.length>f){for(var a=a.split("@@"),c=a.shift(),d=c+"@@"+a[0],e=1;e<a.length;e++)(d+"@@"+a[e]).length>f&&((new Image).src=d,d=c),d+="@@"+a[e];(new Image).src=d}else(new Image).src=a}};j.addElement=function(a,b,c){if(a=this._items[a]){c&&this.setupWindow(c);
var c=a.settings.trackElements,d=c.length;c.push.apply(c,b);a._elements=null;a.update();c.length=d;a._elements=null}};j.removeElement=function(a,b,c){if(this._items&&(a=this._items[a])&&c)this.removeWindow(c),a._elements=null};j.setupWindow=function(a){for(var b=this.windows,c=0;c<b.length;c++)if(b[c]==a)return;try{var d=a.document;b.push(a);var e=this.update,g=this.optimized,h=r.addEvent;h(a,"resize",e);h(a,"load",e);h(a,"scroll",g);h(d,"mousemove",g);h(d,"mousedown",g);h(d,"mouseup",g);this._winInterval||
(this._winInterval=setInterval(g,100))}catch(i){}};j.removeWindow=function(a){try{var b=a.document,c=this.update,d=this.optimized,e=r.removeEvent;e(a,"resize",c);e(a,"load",c);e(a,"scroll",d);e(b,"mousemove",d);e(b,"mousedown",d);e(b,"mouseup",d);v.destroy(b)}catch(g){}b=this.windows;for(c=b.length;c--;)if(b[c]==a){b.splice(c,1);break}};j.destroy=function(){this.emit("destroy");for(var a=this.windows,b=a.length;b--;)this.removeWindow(a[b]);this.windows=[];clearInterval(this._winInterval);a=e;do try{a.__flash_visibility&&
a.__flash_visibility.destroy()}catch(c){break}while(a!=a.top&&(a=a.parent));a=this._items;for(b in a)a[b]&&a[b].destroy&&a[b].destroy();s.destroy();v.destroy();this._items=this.items=this.events=this.byBN=null};b._etCallback?b._etCallback(p()):p()}})(Adform=window.Adform||{},window,document);