<?php

/**
 * This is the model base class for the table "source".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Source".
 *
 * Columns in table "source" available as properties of the model,
 * followed by relations of table "source" available as properties of the model.
 *
 * @property string $id
 * @property string $url
 * @property string $locationId
 * @property string $sourceGroupId
 *
 * @property SourceGroup $sourceGroup
 * @property Location $location
 */
abstract class BaseSource extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'source';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Source|Sources', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('url, locationId, sourceGroupId', 'required'),
			array('locationId, sourceGroupId', 'length', 'max'=>10),
			array('id, url, locationId, sourceGroupId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sourceGroup' => array(self::BELONGS_TO, 'SourceGroup', 'sourceGroupId'),
			'location' => array(self::BELONGS_TO, 'Location', 'locationId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'url' => Yii::t('app', 'Url'),
			'locationId' => null,
			'sourceGroupId' => null,
			'sourceGroup' => null,
			'location' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('locationId', $this->locationId);
		$criteria->compare('sourceGroupId', $this->sourceGroupId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}