<?php

/**
 * This is the model base class for the table "seoMapping".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SeoMapping".
 *
 * Columns in table "seoMapping" available as properties of the model,
 * followed by relations of table "seoMapping" available as properties of the model.
 *
 * @property string $id
 * @property string $page
 * @property string $seoId
 *
 * @property Seo $seo
 */
abstract class BaseSeoMapping extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'seoMapping';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SeoMapping|SeoMappings', $n);
	}

	public static function representingColumn() {
		return 'page';
	}

	public function rules() {
		return array(
			array('page, seoId', 'required'),
			array('page', 'length', 'max'=>8),
			array('seoId', 'length', 'max'=>10),
			array('id, page, seoId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'seo' => array(self::BELONGS_TO, 'Seo', 'seoId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'page' => Yii::t('app', 'Page'),
			'seoId' => null,
			'seo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('page', $this->page, true);
		$criteria->compare('seoId', $this->seoId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}