<?php

/**
 * This is the model base class for the table "county".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "County".
 *
 * Columns in table "county" available as properties of the model,
 * followed by relations of table "county" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $nameSlug
 *
 * @property Location[] $locations
 */
abstract class BaseCounty extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'county';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'County|Counties', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, nameSlug', 'required'),
			array('name, nameSlug', 'length', 'max'=>45),
            array('name', 'unique'),
			array('id, name, nameSlug', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'locations' => array(self::HAS_MANY, 'Location', 'countyId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'nameSlug' => Yii::t('app', 'Name Slug'),
			'locations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('nameSlug', $this->nameSlug, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}