<?php

/**
 * This is the model base class for the table "postalCity".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PostalCity".
 *
 * Columns in table "postalCity" available as properties of the model,
 * followed by relations of table "postalCity" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $nameSlug
 *
 * @property Location[] $locations
 */
abstract class BasePostalCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'postalCity';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PostalCity|PostalCities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, nameSlug', 'required'),
			array('name, nameSlug', 'length', 'max'=>50),
			array('id, name, nameSlug', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'locations' => array(self::HAS_MANY, 'Location', 'postalCityId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'nameSlug' => Yii::t('app', 'Name Slug'),
			'locations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('nameSlug', $this->nameSlug, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}