<?php

/**
 * This is the model base class for the table "mall".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mall".
 *
 * Columns in table "mall" available as properties of the model,
 * followed by relations of table "mall" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $nameSlug
 * @property string $seoId
 *
 * @property Location[] $locations
 * @property Seo $seo
 */
abstract class BaseMall extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mall';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mall|Malls', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, nameSlug', 'required'),
			array('name, nameSlug', 'length', 'max'=>255),
			array('seoId', 'length', 'max'=>10),
			array('seoId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, nameSlug, seoId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'locations' => array(self::HAS_MANY, 'Location', 'mallId'),
			'seo' => array(self::BELONGS_TO, 'Seo', 'seoId'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'nameSlug' => Yii::t('app', 'Name Slug'),
			'seoId' => null,
			'locations' => null,
			'seo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('nameSlug', $this->nameSlug, true);
		$criteria->compare('seoId', $this->seoId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}