EAS_resize_fif(true, 200, 75);document.writeln("<style type=\"text\/css\">");
document.writeln("body {");
document.writeln("        margin: 0;");
document.writeln("        padding: 0;");
document.writeln("         background-color: #fff;");
document.writeln("         font-family: verdana, arial, sans-serif; font-size: 12px;");
document.writeln("         font-weight: bold;");
document.writeln("}");
document.writeln("#ct {");
document.writeln("        border: 1px solid #eaeaea;");
document.writeln("        background: transparent url(\"http://cdn6.emediate.eu/media/5/8403/65628/norgeflagga_stor.png\") no-repeat;");
document.writeln("        background-position: 10px 0px;");
document.writeln("}");
document.writeln("#ct2 {");
document.writeln("        width: 198px;");
document.writeln("        height: 73px;");
document.writeln("}");
document.writeln(".right {");
document.writeln("        float: right;");
document.writeln("        height: 60px;");
document.writeln("        width: 100px;");
document.writeln("        background: transparent url(\"http://cdn6.emediate.eu/media/5/8403/65628/logo_mini.png\") no-repeat 4px 47px;");
document.writeln("        margin-right: 4px;");
document.writeln("        margin-top: 4px;");
document.writeln("        padding: 4px;");
document.writeln("}");
document.writeln(".right a {");
document.writeln("        color: #000000;");
document.writeln("        font-weight:normal;");
document.writeln("}");
document.writeln(".url_text {");
document.writeln("        padding-top:2px;");
document.writeln("        text-decoration: underline;");
document.writeln("        font-weight:normal;");
document.writeln("}");
document.writeln(".click_image {");
document.writeln("        height: 75px;");
document.writeln("        width: 200px;");
document.writeln("        position:absolute;");
document.writeln("        border:0px transparent none;");
document.writeln("        left:0px;");
document.writeln("        top:0px;");
document.writeln("        cursor:pointer;");
document.writeln("}");
document.writeln("<\/style>");
document.writeln("<div id=\"ct\">");
document.writeln("<div id=\"ct2\">");
document.writeln("<div class=\"right\">");
document.writeln("<span>V&auml;lbetalda<\/span>");
document.writeln("<div class=\"url_text\">");
document.writeln("                jobb i Norge");
document.writeln("<\/div>");
document.writeln("<\/div>");
document.writeln("<\/div>");
document.writeln("<\/div>");
document.writeln("<a target=\"_top\" href=\"http://ads.aftonbladet.se/eas/cu=174::camp=65628::no=131080::kw=link1-131080::cat1=11::cat2=5060::cat3=5060::kw2=a::EASTnp=np604|np3664|np3665|np3812|np3925|np3814|np3994|np4231|np4232|np4235::uuid=d85c5a92-b11a-11e3-8d3d-00259075ce4f::EASLink=http:\/\/jobb.blocket.se\/lediga_jobb_i_norge\/\"><img src=\"http://cdn6.emediate.eu/media/5/8403/65628/transparent.gif\" class=\"click_image\"><\/a>");
